import { DEMO_NOW, dayISO } from './data.js';

const HOUR=3600000, DAY=24*HOUR;
const iso=(d)=>new Date(d).toISOString();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed>>>0;return()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/4294967296}}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=(b.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return b[lo]+(b[hi]-b[lo])*(i-lo)}
function overlap(a,b,c,d){return new Date(a)<new Date(d)&&new Date(b)>new Date(c)}

export function ensureAdvancedState(data){
 data.qualityEvents=data.qualityEvents||[];data.capaActions=data.capaActions||[];data.sampleLocations=data.sampleLocations||[];data.custodyEvents=data.custodyEvents||[];data.sampleGroups=data.sampleGroups||[];data.lesTemplates=data.lesTemplates||[];data.guidedExecutions=data.guidedExecutions||[];data.msaStudies=data.msaStudies||[];data.uncertaintyBudgets=data.uncertaintyBudgets||[];data.referenceStandards=data.referenceStandards||[];data.inventoryItems=data.inventoryItems||[];data.inventoryReservations=data.inventoryReservations||[];data.externalLabs=data.externalLabs||[];data.externalJobs=data.externalJobs||[];data.settings=data.settings||{};data.settings.digitalTwin=data.settings.digitalTwin||{iterations:400,confidence:80,includePipeline:true};data.settings.qualityView=data.settings.qualityView||'open';data.settings.custodyProgramme=data.settings.custodyProgramme||'';data.settings.guidedLeg=data.settings.guidedLeg||'';data.settings.metrologyMethod=data.settings.metrologyMethod||'';data.settings.materialFilter=data.settings.materialFilter||'All';data.settings.externalCategory=data.settings.externalCategory||'All';
 if(!data.sampleLocations.length){data.sampleLocations.push(
  {id:'LOC-RECV',name:'Sample Receiving',type:'Receiving',condition:'Ambient'},
  {id:'LOC-QTN',name:'Quarantine Cabinet',type:'Quarantine',condition:'Controlled'},
  {id:'LOC-A01',name:'Sample Store A / Shelf 1',type:'Storage',condition:'23°C / <60%RH'},
  {id:'LOC-B02',name:'Sample Store B / Shelf 2',type:'Storage',condition:'Dry cabinet'},
  {id:'LOC-TEST',name:'Laboratory / In Test',type:'Execution',condition:'Method controlled'},
  {id:'LOC-RET',name:'Retention Archive',type:'Retention',condition:'Controlled'},
  {id:'LOC-DISP',name:'Disposed / Consumed',type:'Disposed',condition:'N/A'}
 );}
 if(!data.custodyEvents.length){let n=0;for(const d of (data.duts||[])){n++;const recv=new Date(DEMO_NOW.getTime()-(20+n%35)*DAY);const quarantined=n%37===0;const loc=quarantined?'LOC-QTN':n%5===0?'LOC-B02':'LOC-A01';data.custodyEvents.push({id:`CST-${String(n).padStart(4,'0')}`,dutId:d.id,type:'Received',from:'Supplier / build',to:'LOC-RECV',timestamp:iso(recv),actor:'Jordan Blake',condition:'Seal intact; visual inspection passed',status:'Complete'});data.custodyEvents.push({id:`CST-${String(n+1000).padStart(4,'0')}`,dutId:d.id,type:quarantined?'Quarantined':'Moved',from:'LOC-RECV',to:loc,timestamp:iso(new Date(recv.getTime()+2*HOUR)),actor:n%2?'Maya Patel':'Noah de Vries',condition:quarantined?'Awaiting serial-number clarification':'Stored per programme plan',status:'Complete'});d.currentLocation=loc;d.custodyStatus=quarantined?'Quarantine':'Available';d.receivedAt=iso(recv);}}
 if(!data.sampleGroups.length){for(const p of (data.programmes||[])){const members=(data.duts||[]).filter(d=>d.programmeId===p.id).map(d=>d.id);if(!members.length)continue;data.sampleGroups.push({id:`SG-${p.id.replace('VP-','')}-ROOT`,name:`${p.project} validation lot`,programmeId:p.id,parentGroupIds:[],memberIds:members,status:'Active',createdAt:dayISO(-30),purpose:'Original validation population',history:[{timestamp:dayISO(-30),action:'Group created',actor:'Jordan Blake',detail:`${members.length} received DUTs`} ]});}}
 if(!data.qualityEvents.length){const source=(data.issues||[]).slice(0,12);let n=0;for(const i of source){n++;const type=i.rootCause==='Bad Specification'?'Specification Deviation':i.severity==='High'?'NCR':'Deviation';const status=n%4===0?'CAPA Verification':n%3===0?'Investigation':n%5===0?'Closed':'Containment';data.qualityEvents.push({id:`QE-${String(n).padStart(3,'0')}`,type,sourceType:'Issue',sourceId:i.id,programmeId:i.programmeId,legId:i.legId||'',dutIds:(data.legs.find(l=>l.id===i.legId)?.dutIds||[]).slice(0,2),severity:i.severity==='High'?'Major':i.severity==='Medium'?'Minor':'Observation',status,detectedAt:i.reportedAt,owner:i.owner||'Demo Lab Manager',containment:`Contain affected ${i.legId||i.programmeId}; preserve evidence and stop disposition until reviewed.`,investigationMethod:n%3===0?'5 Why':n%3===1?'Fishbone':'Is / Is Not',rootCause:i.rootCause||'Under investigation',disposition:n%4===0?'Rework / retest':n%2?'Use as-is with justification':'Hold pending review',dueDate:dayISO(5+n),effectivenessStatus:status==='Closed'?'Effective':'Pending',closedAt:status==='Closed'?dayISO(-n):null});}
 }
 if(!data.capaActions.length){let n=0;for(const q of data.qualityEvents.filter(q=>['CAPA Verification','Closed'].includes(q.status)).slice(0,7)){n++;data.capaActions.push({id:`CAPA-${String(n).padStart(3,'0')}`,qualityEventId:q.id,actionType:n%3===0?'Preventive':n%2?'Corrective':'Systemic',description:n%3===0?'Add pre-test fixture verification and spare availability gate.':n%2?'Update controlled method and retrain qualified operators.':'Update specification review checklist and acceptance-criterion quality gate.',owner:data.staff[(n+4)%data.staff.length]?.name||'Quality Engineer',dueDate:dayISO(n+10),status:n%4===0?'Closed':'In Progress',effectivenessCriteria:'No repeat of same issue family in next 5 applicable test runs.',effectivenessStatus:n%4===0?'Effective':'Pending',verifiedAt:n%4===0?dayISO(-2):null});}}
 if(!data.lesTemplates.length){let n=0;for(const m of (data.methods||[]).filter(m=>m.active).slice(0,20)){const steps=[
   ['Verify controlled method / spec revision','Document','Confirm released method and specification are current.'],
   ['Verify DUT identity and chain of custody','Check','Scan/confirm DUTs, condition and storage release.'],
   ['Verify equipment readiness','Check','Calibration, maintenance, fixtures and consumables green.'],
   ['Perform setup and pre-test checks','Execution','Record setup parameters and baseline readings.'],
   ['Execute test / monitor live data','Execution','Capture instrument data and anomalies; exceptions trigger review.'],
   ['Review acceptance criteria','Review','Deterministic result evaluation and exception review.'],
   ['Close evidence package','Approval','Attach evidence, review exceptions and route report approval.']
  ];data.lesTemplates.push({id:`LES-TPL-${String(++n).padStart(3,'0')}`,methodId:m.id,revision:m.revision||'A',status:'Released',steps:steps.map((s,i)=>({id:`S${i+1}`,sequence:i+1,title:s[0],type:s[1],instruction:s[2],mandatory:true,requiresEvidence:[4,5,6].includes(i),requiresReview:i===5}))});}}
 if(!data.guidedExecutions.length){let n=0;for(const l of (data.legs||[]).filter(l=>l.status==='Completed').slice(0,12)){const t=data.lesTemplates.find(x=>x.methodId===l.methodId);if(!t)continue;n++;data.guidedExecutions.push({id:`LES-RUN-${String(n).padStart(3,'0')}`,legId:l.id,templateId:t.id,status:'Completed',startedAt:l.actualStart||dayISO(-20),completedAt:l.actualEnd||dayISO(-19),operatorId:l.staffId||data.staff[0]?.id,stepStates:t.steps.map((s,i)=>({stepId:s.id,status:'Completed',timestamp:l.actualEnd||dayISO(-19),value:i===4?'Live data captured':'OK',evidence:i>=4?`EVID-${l.id}-${i+1}`:'',exception:i===3&&n%4===0?'Setup repeated after connector check':''})),reviewBy:data.staff.find(s=>s.role?.includes('Engineer'))?.id||data.staff[0]?.id,reviewStatus:'Approved'});}}
 if(!data.referenceStandards.length){data.referenceStandards.push(
  {id:'STD-DCV-01',name:'10 V DC Reference',type:'Electrical Reference',serial:'REF-10017',traceability:'National metrology institute',dueDate:dayISO(180),status:'Valid',uncertainty:'1.2 µV/V'},
  {id:'STD-TMP-01',name:'PRT Reference Thermometer',type:'Temperature Reference',serial:'REF-22008',traceability:'ISO/IEC 17025 accredited provider',dueDate:dayISO(75),status:'Valid',uncertainty:'0.025 °C'},
  {id:'STD-FRC-01',name:'10 kN Load Cell Reference',type:'Force Reference',serial:'REF-33004',traceability:'ISO/IEC 17025 accredited provider',dueDate:dayISO(28),status:'Due Soon',uncertainty:'0.08% FS'},
  {id:'STD-ACC-01',name:'Reference Accelerometer',type:'Vibration Reference',serial:'REF-44012',traceability:'ISO/IEC 17025 accredited provider',dueDate:dayISO(210),status:'Valid',uncertainty:'1.1%'},
  {id:'STD-DIM-01',name:'Grade 0 Gauge Blocks',type:'Dimensional Reference',serial:'REF-55010',traceability:'National metrology institute',dueDate:dayISO(350),status:'Valid',uncertainty:'0.08 µm'}
 );}
 if(!data.msaStudies.length){const mids=['ELEC-001','ENV-TC-004','MECH-VIB-006','DIM-003','MECH-TEN-011','EMC-007'].filter(id=>data.methods.some(m=>m.id===id));let n=0;for(const id of mids){n++;const m=data.methods.find(x=>x.id===id),eq=data.equipment.find(e=>e.type===m.equipmentType);const grr=[7.8,11.2,5.6,16.4,8.9,13.1][n-1]||9;data.msaStudies.push({id:`MSA-${String(n).padStart(3,'0')}`,methodId:id,equipmentId:eq?.id||'',studyType:'Gage R&R',date:dayISO(-20-n*7),parts:10,operators:3,repeats:2,repeatabilityPct:Math.round(grr*.65*10)/10,reproducibilityPct:Math.round(grr*.35*10)/10,totalGrrPct:grr,ndc:grr<10?8:grr<20?5:3,status:grr<10?'Acceptable':grr<30?'Conditionally Acceptable':'Unacceptable',owner:'Priya Shah'});}}
 if(!data.uncertaintyBudgets.length){let n=0;for(const s of data.msaStudies.slice(0,6)){const m=data.methods.find(x=>x.id===s.methodId);n++;const comps=[{source:'Reference standard',type:'B',stdUncertainty:0.18},{source:'Resolution',type:'B',stdUncertainty:0.12},{source:'Repeatability',type:'A',stdUncertainty:0.22},{source:'Environment',type:'B',stdUncertainty:0.10}];const uc=Math.sqrt(comps.reduce((a,c)=>a+c.stdUncertainty**2,0));data.uncertaintyBudgets.push({id:`UNC-${String(n).padStart(3,'0')}`,methodId:s.methodId,equipmentId:s.equipmentId,measurand:m?.category==='Temperature'?'Temperature':m?.category==='Electrical'?'Voltage':'Measured response',unit:m?.category==='Temperature'?'°C':'% of reading',components:comps,combinedUncertainty:Math.round(uc*100)/100,k:2,expandedUncertainty:Math.round(uc*2*100)/100,status:n%5===0?'Review Due':'Released',reviewDue:dayISO(60+n*12)});}}
 for(const u of data.uncertaintyBudgets){if(!Array.isArray(u.referenceStandardIds)||!u.referenceStandardIds.length){const m=data.methods.find(x=>x.id===u.methodId),cat=m?.category||'';u.referenceStandardIds=[/Temperature|Environmental/.test(cat)?'STD-TMP-01':/Electrical|EMC/.test(cat)?'STD-DCV-01':/Vibration|Shock/.test(cat)?'STD-ACC-01':/Dimensional/.test(cat)?'STD-DIM-01':'STD-FRC-01'];}}
 // Historical as-found OOT example used by the metrology impact-analysis workbench; a later valid calibration remains current.
 if(!data.calibrations.some(c=>c.id==='CAL-OOT-DEMO')){const eq=data.equipment.find(e=>e.id==='OSC-01');if(eq)data.calibrations.push({id:'CAL-OOT-DEMO',equipmentId:eq.id,calibrationDate:dayISO(-340,9),dueDate:dayISO(-250,17),certificateNumber:'CERT-OOT-DEMO-OSC01',provider:'Internal Metrology',result:'Pass after adjustment',comments:'Historical demo as-found excursion for retrospective impact analysis.',certificatePath:'OSC-01-certificate.pdf',uncertainty:'Per certificate',asFound:'Out of tolerance: +1.8% amplitude error',asLeft:'Within tolerance after adjustment',measurementTable:[{point:'1 V',asFound:'1.018 V',asLeft:'1.000 V'}]});}
 if(!data.inventoryItems.length){const defs=[
  ['FIX-TC-01','Thermal chamber DUT harness','Fixture',2,1,14,680,['ENV-TC-004','ENV-HU-003']],['FIX-VIB-01','Vibration fixture plate - sensor family','Fixture',2,1,21,1850,['MECH-VIB-006']],['FIX-EMC-01','EMC bulk-current injection fixture','Fixture',1,1,30,2400,['EMC-007']],['FIX-PRS-01','Pressure manifold fixture','Fixture',1,1,28,3200,['PRS-010']],
  ['CON-001','High-temp connector set','Consumable',42,20,10,18,['ENV-TC-004','ENV-HU-003']],['CON-002','Vibration thread-lock kit','Consumable',18,8,7,12,['MECH-VIB-006']],['CON-003','EMC ferrite / cable kit','Consumable',12,6,14,45,['EMC-007']],['CON-004','Seal / O-ring set','Consumable',24,12,14,8,['PRS-010','MECH-DUR-009']],['CON-005','Witness labels / tamper seals','Consumable',120,40,5,1.2,[]],
  ['SPR-TC-01','Chamber circulation fan','Spare',1,1,35,950,[]],['SPR-VIB-01','Vibration amplifier module','Spare',0,1,45,6800,[]],['SPR-DAQ-01','DAQ input module','Spare',2,1,21,1400,[]],['SPR-PSU-01','Bench PSU module','Spare',3,1,14,520,[]],
  ['MAT-001','Epoxy mounting compound','Consumable',8,4,10,55,['MAT-004']],['MAT-002','Tensile coupon grip inserts','Consumable',14,6,21,75,['MECH-TEN-011']],['MAT-003','Microscope sample stubs','Consumable',55,20,10,2.5,['FA-002']],['MAT-004','Humidity indicator cards','Consumable',40,15,7,3,['ENV-HU-003']],['MAT-005','Calibration witness stickers','Consumable',85,30,7,0.8,[]]
  ];let n=0;for(const [id,name,type,onHand,reorder,lead,cost,methods] of defs){data.inventoryItems.push({id,name,type,onHand,reorderPoint:reorder,leadTimeDays:lead,unitCost:cost,compatibleMethodIds:methods,location:type==='Fixture'?'Fixture Store F1':type==='Spare'?'Maintenance Spares':'Consumables Store',status:onHand<=0?'Stockout':onHand<=reorder?'Reorder':'Available',criticality:type==='Fixture'?'High':type==='Spare'?'Medium':'Normal',lastCount:dayISO(-(++n%6))});}}
 for(const i of data.inventoryItems){if(i.id==='SPR-TC-01')i.supportsEquipmentTypes=['Climatic Chamber','Thermal Shock Chamber'];if(i.id==='SPR-VIB-01')i.supportsEquipmentTypes=['Vibration System'];if(i.id==='SPR-DAQ-01')i.supportsEquipmentTypes=['DAQ System'];if(i.id==='SPR-PSU-01')i.supportsEquipmentTypes=['Electrical Bench'];}
 if(!data.inventoryReservations.length){let n=0;for(const l of (data.legs||[]).filter(l=>!['Completed','Cancelled'].includes(l.status)).slice(0,20)){const matches=data.inventoryItems.filter(i=>(i.compatibleMethodIds||[]).includes(l.methodId));for(const item of matches.slice(0,1)){n++;data.inventoryReservations.push({id:`RES-${String(n).padStart(3,'0')}`,itemId:item.id,legId:l.id,quantity:item.type==='Consumable'?Math.min(4,l.dutIds?.length||1):1,status:'Reserved',requiredBy:l.plannedStart||l.requestedDate});}}}
 if(!data.externalLabs.length){data.externalLabs.push(
  {id:'EXT-001',name:'Apex Environmental Labs',categories:['Environmental','Reliability'],accreditation:'ISO/IEC 17025 scope: temperature, humidity, ingress',turnaroundDays:8,expediteDays:4,baseCost:2800,qualityScore:94,onTimePct:92,capacityPerWeek:4,status:'Approved',location:'Eindhoven, NL'},
  {id:'EXT-002',name:'Vector EMC Services',categories:['EMC'],accreditation:'ISO/IEC 17025 scope: EMC immunity/emissions',turnaroundDays:10,expediteDays:5,baseCost:4200,qualityScore:97,onTimePct:95,capacityPerWeek:3,status:'Approved',location:'Düsseldorf, DE'},
  {id:'EXT-003',name:'Nordic Dynamics Test Centre',categories:['Mechanical','Vibration','Shock'],accreditation:'ISO/IEC 17025 scope: vibration/shock',turnaroundDays:7,expediteDays:3,baseCost:3600,qualityScore:91,onTimePct:89,capacityPerWeek:5,status:'Approved',location:'Hamburg, DE'},
  {id:'EXT-004',name:'Metrix Failure Analysis',categories:['Failure Analysis','Material','Dimensional'],accreditation:'ISO/IEC 17025 selected dimensional scope; specialist FA',turnaroundDays:6,expediteDays:3,baseCost:2200,qualityScore:90,onTimePct:93,capacityPerWeek:6,status:'Conditional',location:'Leuven, BE'}
 );}
 if(!data.externalJobs.length){const candidates=(data.legs||[]).filter(l=>!['Completed','Cancelled'].includes(l.status)).slice(0,3);let n=0;for(const l of candidates){const cat=data.methods.find(m=>m.id===l.methodId)?.category;const lab=data.externalLabs.find(x=>x.categories.includes(cat));if(!lab)continue;n++;data.externalJobs.push({id:`EXTJOB-${String(n).padStart(3,'0')}`,legId:l.id,labId:lab.id,status:n===1?'Quote Requested':'Planned',quoteCost:lab.baseCost+(l.dutIds?.length||1)*35,shipDate:dayISO(2+n),expectedReturn:dayISO(2+n+lab.turnaroundDays),evidenceStatus:'Pending',purchaseOrder:n===2?'PO-DEMO-2048':'',tracking:n===2?'DHL-DEMO-001':'',reviewStatus:'Pending'});}}
 return data;
}

export function qualitySummary(data){ensureAdvancedState(data);const open=data.qualityEvents.filter(q=>q.status!=='Closed'),maj=open.filter(q=>['Major','Critical'].includes(q.severity)),over=open.filter(q=>q.dueDate&&new Date(q.dueDate)<DEMO_NOW),capa=data.capaActions.filter(c=>c.status!=='Closed'),effective=data.capaActions.filter(c=>c.effectivenessStatus==='Effective').length;return{open:open.length,major:maj.length,overdue:over.length,capaOpen:capa.length,effectivenessPct:Math.round(effective/Math.max(1,data.capaActions.length)*100),closed:data.qualityEvents.filter(q=>q.status==='Closed').length};}
export function qualityEventFromIssue(data,issueId){ensureAdvancedState(data);const existing=data.qualityEvents.find(q=>q.sourceType==='Issue'&&q.sourceId===issueId);if(existing)return existing;const i=data.issues.find(x=>x.id===issueId);if(!i)return null;const id=`QE-${String(data.qualityEvents.length+1).padStart(3,'0')}`;const q={id,type:i.severity==='High'?'NCR':'Deviation',sourceType:'Issue',sourceId:i.id,programmeId:i.programmeId,legId:i.legId||'',dutIds:(data.legs.find(l=>l.id===i.legId)?.dutIds||[]).slice(0,3),severity:i.severity==='High'?'Major':'Minor',status:'Containment',detectedAt:i.reportedAt,owner:i.owner||data.settings.actor,containment:'Contain affected work and preserve evidence.',investigationMethod:'5 Why',rootCause:'Under investigation',disposition:'Hold pending review',dueDate:dayISO(7),effectivenessStatus:'Pending'};data.qualityEvents.push(q);return q;}
export function addCapa(data,qualityEventId,description,owner){ensureAdvancedState(data);const id=`CAPA-${String(data.capaActions.length+1).padStart(3,'0')}`;const c={id,qualityEventId,actionType:'Corrective',description,owner,dueDate:dayISO(14),status:'Open',effectivenessCriteria:'No recurrence in next 5 applicable test runs.',effectivenessStatus:'Pending'};data.capaActions.push(c);const q=data.qualityEvents.find(x=>x.id===qualityEventId);if(q)q.status='CAPA';return c;}
export function qualityHoldForLeg(data,legId){ensureAdvancedState(data);return data.qualityEvents.find(q=>q.legId===legId&&q.status!=='Closed'&&['Major','Critical'].includes(q.severity))||null;}

export function currentCustody(data,dutId){ensureAdvancedState(data);const events=data.custodyEvents.filter(e=>e.dutId===dutId).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp));const e=events[0],dut=data.duts.find(d=>d.id===dutId);return{location:e?.to||dut?.currentLocation||'Unknown',status:dut?.custodyStatus||'Unknown',lastEvent:e,events};}
export function custodySummary(data,programmeId=''){ensureAdvancedState(data);const duts=data.duts.filter(d=>!programmeId||d.programmeId===programmeId);const rows=duts.map(d=>({dut:d,...currentCustody(data,d.id)}));return{total:rows.length,available:rows.filter(r=>r.status==='Available').length,quarantine:rows.filter(r=>r.status==='Quarantine').length,inTest:rows.filter(r=>r.location==='LOC-TEST').length,retained:rows.filter(r=>r.location==='LOC-RET').length,rows};}
export function moveDut(data,dutId,to,type='Moved',actor=data.settings.actor,condition='No abnormality observed'){ensureAdvancedState(data);const c=currentCustody(data,dutId),dut=data.duts.find(d=>d.id===dutId);if(!dut)return null;const ev={id:`CST-${String(data.custodyEvents.length+1).padStart(4,'0')}`,dutId,type,from:c.location,to,timestamp:new Date().toISOString(),actor,condition,status:'Complete'};data.custodyEvents.push(ev);dut.currentLocation=to;dut.custodyStatus=to==='LOC-QTN'?'Quarantine':to==='LOC-DISP'?'Disposed':to==='LOC-TEST'?'In Test':'Available';dut.history=dut.history||[];dut.history.push({timestamp:ev.timestamp,event:`Custody ${type}`,detail:`${c.location} → ${to}`});return ev;}
export function custodyReadyForLeg(data,leg){ensureAdvancedState(data);const bad=(leg.dutIds||[]).map(id=>({id,c:currentCustody(data,id)})).filter(x=>!['Available','In Test'].includes(x.c.status)||x.c.location==='LOC-QTN'||x.c.location==='LOC-DISP');return{ok:bad.length===0,bad,reason:bad.length?`${bad.length} DUT(s) are quarantined, disposed or otherwise not released by chain-of-custody.`:null};}

export function sampleGroupSummary(data,programmeId=''){ensureAdvancedState(data);const groups=data.sampleGroups.filter(g=>!programmeId||g.programmeId===programmeId);return{groups,active:groups.filter(g=>g.status==='Active').length,members:[...new Set(groups.filter(g=>g.status==='Active').flatMap(g=>g.memberIds||[]))].length};}
export function splitSampleGroup(data,groupId,memberIds,name='Split population'){ensureAdvancedState(data);const src=data.sampleGroups.find(g=>g.id===groupId);if(!src)return null;const chosen=[...new Set((memberIds||[]).filter(id=>(src.memberIds||[]).includes(id)))];if(!chosen.length||chosen.length>=(src.memberIds||[]).length)return null;src.memberIds=src.memberIds.filter(id=>!chosen.includes(id));src.history=src.history||[];src.history.push({timestamp:new Date().toISOString(),action:'Population split',actor:data.settings.actor,detail:`${chosen.length} DUTs split into new group`});const g={id:`SG-${String(data.sampleGroups.length+1).padStart(3,'0')}`,name,programmeId:src.programmeId,parentGroupIds:[src.id],memberIds:chosen,status:'Active',createdAt:new Date().toISOString(),purpose:'Split validation population',history:[{timestamp:new Date().toISOString(),action:'Created from split',actor:data.settings.actor,detail:`Source ${src.id} · ${chosen.length} DUTs`} ]};data.sampleGroups.push(g);return g;}
export function mergeSampleGroups(data,groupIds,name='Merged population'){ensureAdvancedState(data);const src=data.sampleGroups.filter(g=>groupIds.includes(g.id)&&g.status==='Active');if(src.length<2||new Set(src.map(g=>g.programmeId)).size!==1)return null;const members=[...new Set(src.flatMap(g=>g.memberIds||[]))];for(const g of src){g.status='Merged';g.history=g.history||[];g.history.push({timestamp:new Date().toISOString(),action:'Merged',actor:data.settings.actor,detail:`Merged into ${name}`});}const g={id:`SG-${String(data.sampleGroups.length+1).padStart(3,'0')}`,name,programmeId:src[0].programmeId,parentGroupIds:src.map(g=>g.id),memberIds:members,status:'Active',createdAt:new Date().toISOString(),purpose:'Merged validation population',history:[{timestamp:new Date().toISOString(),action:'Merged group created',actor:data.settings.actor,detail:`Sources ${src.map(x=>x.id).join(', ')}`} ]};data.sampleGroups.push(g);return g;}

export function templateForMethod(data,methodId){ensureAdvancedState(data);return data.lesTemplates.find(t=>t.methodId===methodId&&t.status==='Released')||null;}
export function startGuidedExecution(data,legId,operatorId){ensureAdvancedState(data);const leg=data.legs.find(l=>l.id===legId),tpl=leg&&templateForMethod(data,leg.methodId);if(!leg||!tpl)return null;let ex=data.guidedExecutions.find(x=>x.legId===legId&&x.status!=='Completed');if(ex)return ex;ex={id:`LES-RUN-${String(data.guidedExecutions.length+1).padStart(3,'0')}`,legId,templateId:tpl.id,status:'In Progress',startedAt:new Date().toISOString(),operatorId,stepStates:tpl.steps.map(s=>({stepId:s.id,status:'Pending',timestamp:null,value:'',evidence:'',exception:''})),reviewStatus:'Pending'};data.guidedExecutions.push(ex);return ex;}
export function completeGuidedStep(data,executionId,stepId,{value='OK',evidence='',exception=''}={}){ensureAdvancedState(data);const ex=data.guidedExecutions.find(x=>x.id===executionId);if(!ex)return null;const s=ex.stepStates.find(x=>x.stepId===stepId);if(!s)return null;s.status='Completed';s.timestamp=new Date().toISOString();s.value=value;s.evidence=evidence;s.exception=exception;if(exception){const leg=data.legs.find(l=>l.id===ex.legId);data.qualityEvents.push({id:`QE-${String(data.qualityEvents.length+1).padStart(3,'0')}`,type:'Execution Deviation',sourceType:'LES Step',sourceId:`${executionId}:${stepId}`,programmeId:leg?.programmeId||'',legId:leg?.id||'',dutIds:(leg?.dutIds||[]).slice(0,3),severity:'Minor',status:'Containment',detectedAt:new Date().toISOString(),owner:data.settings.actor,containment:'Review exception before continuing/closing execution.',investigationMethod:'Review by exception',rootCause:'Under investigation',disposition:'Hold step review',dueDate:dayISO(3),effectivenessStatus:'Pending'});}if(ex.stepStates.every(x=>x.status==='Completed')){ex.status='Awaiting Review';ex.completedAt=new Date().toISOString();}return ex;}
export function executionReadiness(data,leg){ensureAdvancedState(data);const c=custodyReadyForLeg(data,leg),inv=inventoryReadiness(data,leg),q=qualityHoldForLeg(data,leg.id);return{ok:c.ok&&inv.ok&&!q,reasons:[c.reason,inv.reason,q?`Quality hold ${q.id}: ${q.type} (${q.severity})`:null].filter(Boolean)};}

export function guidedReviewReadiness(data,executionId){ensureAdvancedState(data);const ex=data.guidedExecutions.find(x=>x.id===executionId),tpl=data.lesTemplates.find(x=>x.id===ex?.templateId);if(!ex||!tpl)return{ok:false,reasons:['Execution/template not found.']};const missing=tpl.steps.filter(s=>s.mandatory&&ex.stepStates.find(x=>x.stepId===s.id)?.status!=='Completed');const openExceptions=data.qualityEvents.filter(q=>q.sourceType==='LES Step'&&String(q.sourceId||'').startsWith(`${ex.id}:`)&&q.status!=='Closed');return{ok:missing.length===0&&openExceptions.length===0,reasons:[missing.length?`${missing.length} mandatory step(s) incomplete.`:null,openExceptions.length?`${openExceptions.length} execution exception(s) still require disposition.`:null].filter(Boolean),missing,openExceptions};}
export function approveGuidedExecution(data,executionId,reviewerId){ensureAdvancedState(data);const r=guidedReviewReadiness(data,executionId),ex=data.guidedExecutions.find(x=>x.id===executionId);if(!r.ok)return{ok:false,reasons:r.reasons,execution:ex};ex.reviewStatus='Approved';ex.reviewBy=reviewerId;ex.reviewedAt=new Date().toISOString();ex.status='Completed';const leg=data.legs.find(l=>l.id===ex.legId),res=data.results.filter(x=>x.legId===leg?.id);if(leg){if(res.some(x=>x.status==='FAIL'))leg.status='Failed';else if(res.length)leg.status='Completed';else leg.status='Awaiting Review';}return{ok:true,reasons:[],execution:ex};}

function methodStats(data,methodId){const runs=(data.testRuns||[]).filter(r=>r.methodId===methodId&&r.status==='Completed'),hours=runs.map(r=>Number(r.actualHours)||0).filter(x=>x>0),std=runs.map(r=>Number(r.standardHours)||0).filter(x=>x>0),ratios=runs.map(r=>r.standardHours>0?(Number(r.actualHours)||0)/r.standardHours:1).filter(x=>x>0);const issues=(data.issues||[]).filter(i=>runs.some(r=>r.id===i.testRunId));return{runs,hours,std,ratios,medianHours:median(hours),p80Ratio:percentile(ratios,.8)||1,issueRate:issues.length/Math.max(1,runs.length),failRate:runs.filter(r=>r.outcome==='FAIL').length/Math.max(1,runs.length),reworkRate:runs.filter(r=>r.outcome==='REWORK').length/Math.max(1,runs.length)};}
export function digitalTwinForecast(data,{iterations,programmeId='',includePipeline}={}){ensureAdvancedState(data);iterations=clamp(Number(iterations)||data.settings.digitalTwin.iterations||400,100,2000);const programs=data.programmes.filter(p=>!programmeId||p.id===programmeId);const rr=rng(8675309+hash(programmeId||'portfolio')+iterations);const results=[];for(const p of programs){const legs=data.legs.filter(l=>l.programmeId===p.id).sort((a,b)=>a.sequence-b.sequence),samples=[];for(let k=0;k<iterations;k++){const simEnd={};let finish=DEMO_NOW.getTime();for(const l of legs){if(l.actualEnd){simEnd[l.id]=new Date(l.actualEnd).getTime();finish=Math.max(finish,simEnd[l.id]);continue;}if(l.executionMode==='External'){const e=new Date(l.plannedEnd||data.externalJobs.find(j=>j.legId===l.id)?.expectedReturn||l.dueDate).getTime();simEnd[l.id]=e;finish=Math.max(finish,e);continue;}const m=data.methods.find(x=>x.id===l.methodId),pred=Math.max(DEMO_NOW.getTime(),...(l.predecessorIds||[]).map(id=>simEnd[id]||DEMO_NOW.getTime())),baseline=l.plannedStart?new Date(l.plannedStart).getTime():Math.max(DEMO_NOW.getTime(),new Date(l.sampleReadyDate||DEMO_NOW).getTime()),base=Math.max(baseline,pred),stat=methodStats(data,l.methodId),planned=Math.max(1,(l.plannedEnd&&l.plannedStart?(new Date(l.plannedEnd)-new Date(l.plannedStart))/HOUR:(m?.setupHours||0)+(m?.executionHours||8)+(m?.teardownHours||0)+(m?.analysisHours||0))),spread=Math.max(.9,stat.p80Ratio||1),tri=.82+rr()*(spread+.3-.82),issue=rr()<stat.issueRate?1+(rr()*Math.max(4,stat.issueRate*48))/planned:1,fail=rr()<stat.failRate?1.18:1,rework=rr()<stat.reworkRate?1.12:1,dur=planned*tri*issue*fail*rework;simEnd[l.id]=base+dur*HOUR;finish=Math.max(finish,simEnd[l.id]);}samples.push(finish);}const due=new Date(p.dueDate).getTime(),p50=percentile(samples,.5),p80=percentile(samples,.8),p95=percentile(samples,.95),onTime=samples.filter(x=>x<=due).length/samples.length*100;results.push({programmeId:p.id,project:p.project,dueDate:p.dueDate,p50:iso(p50),p80:iso(p80),p95:iso(p95),onTimePct:Math.round(onTime),risk:onTime>=80?'Low':onTime>=60?'Medium':'High',iterations,slipP80Days:Math.max(0,Math.round((p80-due)/DAY*10)/10)});}const portfolioOnTime=results.length?Math.round(results.reduce((a,r)=>a+r.onTimePct,0)/results.length):100;return{results,portfolioOnTime,iterations,atRisk:results.filter(r=>r.onTimePct<80).length,critical:results.filter(r=>r.onTimePct<60).length,includePipeline:includePipeline??data.settings.digitalTwin.includePipeline};}

export function metrologySummary(data){ensureAdvancedState(data);const badMsa=data.msaStudies.filter(x=>x.status==='Unacceptable'),cond=data.msaStudies.filter(x=>x.status==='Conditionally Acceptable'),uncDue=data.uncertaintyBudgets.filter(x=>x.status!=='Released'||new Date(x.reviewDue)<new Date(DEMO_NOW.getTime()+30*DAY)),stdDue=data.referenceStandards.filter(x=>new Date(x.dueDate)<new Date(DEMO_NOW.getTime()+60*DAY));return{msa:data.msaStudies.length,badMsa:badMsa.length,conditional:cond.length,uncertainty:data.uncertaintyBudgets.length,uncertaintyDue:uncDue.length,standards:data.referenceStandards.length,standardsDue:stdDue.length};}
export function metrologyReadyForMethod(data,methodId){ensureAdvancedState(data);const studies=data.msaStudies.filter(x=>x.methodId===methodId).sort((a,b)=>new Date(b.date)-new Date(a.date)),msa=studies[0],unc=data.uncertaintyBudgets.find(x=>x.methodId===methodId),refs=(unc?.referenceStandardIds||[]).map(id=>data.referenceStandards.find(r=>r.id===id)).filter(Boolean),expired=refs.filter(r=>new Date(r.dueDate)<DEMO_NOW);return{ok:(!msa||msa.status!=='Unacceptable')&&(!unc||unc.status==='Released')&&!expired.length,msa,unc,refs,reasons:[msa?.status==='Unacceptable'?`MSA ${msa.id} is unacceptable (${msa.totalGrrPct}% Gage R&R).`:null,unc&&unc.status!=='Released'?`Uncertainty budget ${unc.id} requires review.`:null,...expired.map(r=>`Reference standard ${r.id} is past its traceability due date.`)].filter(Boolean)};}
export function metrologyImpactAnalysis(data,equipmentId){ensureAdvancedState(data);const cals=data.calibrations.filter(c=>c.equipmentId===equipmentId&&c.result!=='Scheduled').sort((a,b)=>new Date(a.calibrationDate)-new Date(b.calibrationDate)),oot=[...cals].reverse().find(c=>c.asFound&&!/within tolerance|within spec|acceptable/i.test(c.asFound));if(!oot)return{equipmentId,oot:null,runs:[],requirements:[],decision:'No historical as-found OOT record detected.'};const idx=cals.indexOf(oot),prev=idx>0?cals[idx-1]:null,start=prev?new Date(prev.calibrationDate):new Date(new Date(oot.calibrationDate).getTime()-365*DAY),end=new Date(oot.calibrationDate),runs=(data.testRuns||[]).filter(r=>r.equipmentId===equipmentId&&r.actualEnd&&new Date(r.actualEnd)>=start&&new Date(r.actualEnd)<=end),reqIds=[...new Set(runs.flatMap(r=>data.legs.find(l=>l.id===r.legId)?.requirementIds||[]))];return{equipmentId,oot,previousCalibration:prev,runs,requirements:reqIds.map(id=>data.requirements.find(r=>r.id===id)).filter(Boolean),decision:runs.length?`${runs.length} historical run(s) fall inside the potential impact interval and require documented technical review.`:'No test runs fall within the potential impact interval.'};}
export function addMsaStudy(data,{methodId,equipmentId,totalGrrPct,owner}){ensureAdvancedState(data);const g=Number(totalGrrPct);const x={id:`MSA-${String(data.msaStudies.length+1).padStart(3,'0')}`,methodId,equipmentId,studyType:'Gage R&R',date:new Date().toISOString(),parts:10,operators:3,repeats:2,repeatabilityPct:Math.round(g*.65*10)/10,reproducibilityPct:Math.round(g*.35*10)/10,totalGrrPct:g,ndc:g<10?8:g<20?5:3,status:g<10?'Acceptable':g<30?'Conditionally Acceptable':'Unacceptable',owner};data.msaStudies.push(x);return x;}

export function inventoryReadiness(data,leg){ensureAdvancedState(data);const req=(data.inventoryItems||[]).filter(i=>(i.compatibleMethodIds||[]).includes(leg.methodId));const bad=[];for(const item of req){const needed=item.type==='Consumable'?Math.min(4,leg.dutIds?.length||1):1;const reserved=item.type==='Consumable'?(data.inventoryReservations||[]).filter(r=>r.itemId===item.id&&r.legId!==leg.id&&r.status==='Reserved').reduce((a,r)=>a+Number(r.quantity||0),0):0;const avail=Number(item.onHand||0)-reserved;if(avail<needed)bad.push({item,needed,available:Math.max(0,avail)});}return{ok:bad.length===0,bad,reason:bad.length?`Material/fixture shortage: ${bad.map(x=>`${x.item.id} need ${x.needed}, available ${x.available}`).join('; ')}`:null};}
export function inventorySummary(data){ensureAdvancedState(data);const stockout=data.inventoryItems.filter(i=>Number(i.onHand)<=0),reorder=data.inventoryItems.filter(i=>Number(i.onHand)<=Number(i.reorderPoint)),value=data.inventoryItems.reduce((a,i)=>a+Number(i.onHand||0)*Number(i.unitCost||0),0);const blocked=data.legs.filter(l=>!['Completed','Cancelled'].includes(l.status)&&!inventoryReadiness(data,l).ok);return{items:data.inventoryItems.length,stockout:stockout.length,reorder:reorder.length,value:Math.round(value),blockedLegs:blocked.length,blocked};}
export function reserveInventory(data,legId,itemId,quantity){ensureAdvancedState(data);let r=data.inventoryReservations.find(x=>x.legId===legId&&x.itemId===itemId);if(!r){r={id:`RES-${String(data.inventoryReservations.length+1).padStart(3,'0')}`,itemId,legId,quantity:Number(quantity),status:'Reserved',requiredBy:data.legs.find(l=>l.id===legId)?.plannedStart||dayISO(1)};data.inventoryReservations.push(r);}else r.quantity=Number(quantity);return r;}

export function assetHealth(data,eqId){ensureAdvancedState(data);const eq=data.equipment.find(e=>e.id===eqId);if(!eq)return null;const pol=data.maintenancePolicies?.find(p=>p.equipmentId===eqId),events=(data.maintenance||[]).filter(m=>m.equipmentId===eqId),issues=(data.issues||[]).filter(i=>{const run=data.testRuns.find(r=>r.id===i.testRunId);return run?.equipmentId===eqId||i.equipmentId===eqId;}),alerts=(data.liveAlerts||[]).filter(a=>{const s=data.liveSessions?.find(x=>x.id===a.sessionId),l=data.legs.find(x=>x.id===s?.legId);return l?.equipmentId===eqId;}),cals=(data.calibrations||[]).filter(c=>c.equipmentId===eqId&&c.result!=='Scheduled').sort((a,b)=>new Date(b.calibrationDate)-new Date(a.calibrationDate)),latest=cals[0];const riskBase={Low:15,Medium:35,High:60,Critical:80};let risk=Number.isFinite(Number(pol?.failureRisk))?Number(pol.failureRisk):(riskBase[pol?.failureRisk]??10);risk+=events.filter(e=>e.type==='Breakdown'&&new Date(e.start)>new Date(DEMO_NOW.getTime()-365*DAY)).length*15;risk+=issues.filter(i=>new Date(i.reportedAt)>new Date(DEMO_NOW.getTime()-90*DAY)).length*4;risk+=alerts.filter(a=>new Date(a.createdAt||a.timestamp)>new Date(DEMO_NOW.getTime()-30*DAY)).length*3;if(latest&&latest.asFound&&!/within/i.test(latest.asFound))risk+=20;if(pol?.conditionScore!=null)risk+=(100-Number(pol.conditionScore))*.25;risk=clamp(Math.round(risk),0,100);const daysToService=pol?.nextDueDate?Math.round((new Date(pol.nextDueDate)-DEMO_NOW)/DAY):999,predictedDays=Math.max(3,Math.round((100-risk)*1.4)),spares=(data.inventoryItems||[]).filter(i=>i.type==='Spare'&&(i.supportsEquipmentTypes||[]).includes(eq.type)),spareReady=spares.some(i=>Number(i.onHand)>0);return{eq,risk,health:100-risk,band:risk>=70?'High':risk>=45?'Medium':'Low',predictedFailureWindowDays:predictedDays,daysToService,action:risk>=70?(spareReady?'Bring service forward and reserve available critical spare / backup capacity':'Bring service forward; procure critical spare or reserve backup/outsourced capacity'):risk>=45?'Increase condition checks and align calibration + maintenance':'Continue optimized preventive plan',signals:{breakdowns:events.filter(e=>e.type==='Breakdown').length,issues:issues.length,alerts:alerts.length,conditionScore:pol?.conditionScore??100,spareReady,spares:spares.map(i=>i.id)}};}
export function predictiveAssetSummary(data){ensureAdvancedState(data);const rows=data.equipment.filter(e=>!['Retired','Out of Service'].includes(e.status)).map(e=>assetHealth(data,e.id)).filter(Boolean).sort((a,b)=>b.risk-a.risk);return{rows,high:rows.filter(r=>r.band==='High').length,medium:rows.filter(r=>r.band==='Medium').length,avgHealth:Math.round(rows.reduce((a,r)=>a+r.health,0)/Math.max(1,rows.length)),top:rows.slice(0,8)};}

export function externalAlternatives(data,legId){ensureAdvancedState(data);const leg=data.legs.find(l=>l.id===legId),m=leg&&data.methods.find(x=>x.id===leg.methodId);if(!leg||!m)return[];return data.externalLabs.filter(l=>l.categories.includes(m.category)&&l.status!=='Suspended').map(l=>{const cost=Math.round(l.baseCost+(leg.dutIds?.length||1)*35),returnDate=new Date(DEMO_NOW.getTime()+l.turnaroundDays*DAY);return{lab:l,cost,returnDate:iso(returnDate),score:Math.round(l.qualityScore*.45+l.onTimePct*.35+Math.max(0,100-l.turnaroundDays*5)*.2)}}).sort((a,b)=>b.score-a.score);}
export function externalSummary(data){ensureAdvancedState(data);return{labs:data.externalLabs.length,approved:data.externalLabs.filter(l=>l.status==='Approved').length,openJobs:data.externalJobs.filter(j=>!['Completed','Cancelled'].includes(j.status)).length,spend:data.externalJobs.reduce((a,j)=>a+Number(j.quoteCost||0),0),late:data.externalJobs.filter(j=>j.expectedReturn&&new Date(j.expectedReturn)<DEMO_NOW&&j.status!=='Completed').length};}
export function outsourceLeg(data,legId,labId){ensureAdvancedState(data);const leg=data.legs.find(l=>l.id===legId),lab=data.externalLabs.find(x=>x.id===labId);if(!leg||!lab)return null;let job=data.externalJobs.find(j=>j.legId===legId&&j.status!=='Cancelled');if(!job){job={id:`EXTJOB-${String(data.externalJobs.length+1).padStart(3,'0')}`,legId,labId,status:'Planned',quoteCost:Math.round(lab.baseCost+(leg.dutIds?.length||1)*35),shipDate:dayISO(1),expectedReturn:dayISO(1+lab.turnaroundDays),evidenceStatus:'Pending',purchaseOrder:`PO-DEMO-${3000+data.externalJobs.length}`,tracking:'Pending',reviewStatus:'Pending'};data.externalJobs.push(job);}else{job.labId=labId;job.quoteCost=job.quoteCost||Math.round(lab.baseCost+(leg.dutIds?.length||1)*35);job.shipDate=job.shipDate||dayISO(1);job.expectedReturn=job.expectedReturn||dayISO(1+lab.turnaroundDays);if(job.status==='Quote Requested')job.status='Planned';}leg.externalLabId=labId;leg.externalJobId=job.id;leg.executionMode='External';leg.plannedStart=job.shipDate;leg.plannedEnd=job.expectedReturn;leg.equipmentId=null;leg.staffId=null;leg.status='Planned';data.bookings=(data.bookings||[]).filter(b=>b.legId!==legId);return job;}

function jaccard(a,b){const A=new Set(a),B=new Set(b),u=new Set([...A,...B]),i=[...A].filter(x=>B.has(x));return u.size?i.length/u.size:0}
export function programmeSimilarity(data,targetProgrammeId){ensureAdvancedState(data);const t=data.programmes.find(p=>p.id===targetProgrammeId);if(!t)return[];const tm=data.legs.filter(l=>l.programmeId===t.id).map(l=>l.methodId),tc=data.legs.filter(l=>l.programmeId===t.id).map(l=>data.methods.find(m=>m.id===l.methodId)?.category).filter(Boolean);return data.programmes.filter(p=>p.id!==t.id).map(p=>{const pm=data.legs.filter(l=>l.programmeId===p.id).map(l=>l.methodId),pc=data.legs.filter(l=>l.programmeId===p.id).map(l=>data.methods.find(m=>m.id===l.methodId)?.category).filter(Boolean),method=jaccard(tm,pm),cat=jaccard(tc,pc),product=(p.product&&t.product&&p.product.split(' ')[0]===t.product.split(' ')[0])?1:0,score=Math.round((method*.6+cat*.3+product*.1)*100);return{programme:p,score,methodOverlap:Math.round(method*100),categoryOverlap:Math.round(cat*100),methods:pm}}).sort((a,b)=>b.score-a.score);}
export function knowledgeRecommendation(data,{programmeId='',methodIds=[]}={}){ensureAdvancedState(data);let source;if(programmeId)source=programmeSimilarity(data,programmeId)[0];else{const candidates=data.programmes.map(p=>{const mids=data.legs.filter(l=>l.programmeId===p.id).map(l=>l.methodId);return{programme:p,score:Math.round(jaccard(methodIds,mids)*100),methods:mids}}).sort((a,b)=>b.score-a.score);source=candidates[0];}if(!source)return null;const p=source.programme||source.programme,legs=data.legs.filter(l=>l.programmeId===p.id).sort((a,b)=>a.sequence-b.sequence);const durations=legs.map(l=>methodStats(data,l.methodId).medianHours||((data.methods.find(m=>m.id===l.methodId)?.executionHours)||8));const issues=data.issues.filter(i=>i.programmeId===p.id);return{sourceProgrammeId:p.id,sourceProject:p.project,similarity:source.score||0,recommendedMethods:[...new Set(legs.map(l=>l.methodId))],typicalLegs:legs.length,typicalDuts:data.duts.filter(d=>d.programmeId===p.id).length,medianMethodHours:Math.round(median(durations)*10)/10,topLessons:Object.entries(issues.reduce((a,i)=>(a[i.issueType]=(a[i.issueType]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name,count])=>({name,count}))};}

export function advancedReadiness(data,leg){ensureAdvancedState(data);const custody=custodyReadyForLeg(data,leg),inventory=inventoryReadiness(data,leg),met=metrologyReadyForMethod(data,leg.methodId),quality=qualityHoldForLeg(data,leg.id);return{ok:custody.ok&&inventory.ok&&met.ok&&!quality,custody,inventory,metrology:met,quality,reasons:[custody.reason,inventory.reason,...met.reasons,quality?`Open ${quality.severity} quality event ${quality.id} holds execution.`:null].filter(Boolean)};}
