import { BUILD, DATASET_VERSION, VERSION, preferenceDefinitions, vehicleProfiles } from './config.js';
import { TravelDataClient } from './travel-data.js';
import { createCanonicalPlan, normalizeTripInput } from './canonical-plan-engine.js';
import { validateCanonicalPlan } from './validator.js';
import { liveProviders, runEnrichmentPipeline } from './enrichment.js';
import { buildGpx, downloadGpx } from './gpx-generator.js';
import { renderMap } from './map-view.js';
import { deleteTrip, loadTrips, saveTrip } from './storage.js';

const $=id=>document.getElementById(id);const data=new TravelDataClient();let currentPlan=null,currentDestination=null;
const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(text,tone=''){const el=$('status');el.textContent=text;el.dataset.tone=tone}
function setToday(){if(!$('startDate').value){const d=new Date();d.setDate(d.getDate()+14);$('startDate').value=d.toISOString().slice(0,10)}}
function renderPreferences(){const box=$('preferenceGrid');box.innerHTML=preferenceDefinitions.map(([id,label])=>`<label class="pref"><span>${html(label)}</span><input data-pref="${id}" type="range" min="0" max="3" step="1" value="${id==='natuur'||id==='motor'?2:0}"><b id="pref-${id}">${id==='natuur'||id==='motor'?2:0}</b></label>`).join('');box.querySelectorAll('[data-pref]').forEach(x=>x.addEventListener('input',()=>{$(`pref-${x.dataset.pref}`).textContent=x.value}))}
function syncVehicleDefaults(){const p=vehicleProfiles[$('transport').value];if(!$('fuelRangeKm').dataset.user)$('fuelRangeKm').value=p.defaultFuelRangeKm;const dims=['vehicleHeightM','vehicleLengthM','vehicleWeightKg','vehicleMaxSpeedKmh'];const defaults=$('transport').value==='motorhome'?[3.1,7.2,3500,100]:$('transport').value==='caravan'?[2.7,11.5,3200,90]:[1.8,4.5,1800,130];dims.forEach((id,i)=>{if(!$(id).dataset.user)$(id).value=defaults[i]})}
function readTrip(){const prefs={},selected=[];document.querySelectorAll('[data-pref]').forEach(x=>{prefs[x.dataset.pref]=Number(x.value);if(Number(x.value)>0)selected.push(x.dataset.pref)});return normalizeTripInput({origin:$('origin').value.trim(),destinationQuery:$('destinationQuery').value.trim(),startDate:$('startDate').value,days:Number($('days').value),budget:Number($('budget').value),transport:$('transport').value,tripStructure:$('tripStructure').value,routeTopology:$('routeTopology').value,tripPace:$('tripPace').value,maxDrive:Number($('maxDrive').value),maxChanges:Number($('maxChanges').value),accommodationType:$('accommodationType').value,comfort:$('comfort').value,adults:Number($('adults').value),children:Number($('children').value),routeStyle:$('routeStyle').value,fuelRangeKm:Number($('fuelRangeKm').value),vehicleMaxSpeedKmh:Number($('vehicleMaxSpeedKmh').value),vehicleHeightM:Number($('vehicleHeightM').value),vehicleLengthM:Number($('vehicleLengthM').value),vehicleWeightKg:Number($('vehicleWeightKg').value),strictBudget:$('strictBudget').checked,strictDrive:$('strictDrive').checked,strictChanges:$('strictChanges').checked,liveData:$('liveData').checked,preferences:selected,preferenceWeights:prefs})}
function chooseDestination(query){const rows=data.search(query,20);if(!rows.length)return null;const q=query.toLowerCase();return rows.find(r=>r.name.toLowerCase()===q)||rows.find(r=>r.searchTerms?.some(s=>String(s).toLowerCase()===q))||rows[0]}
function diagnosticView(f){if(!f){$('diagnostics').innerHTML='';return}$('diagnostics').innerHTML=`<div class="diagnostic"><strong>${html(f.code)}</strong><p>${html(f.reason)}</p><dl><dt>Constraint</dt><dd>${html(f.constraint)}</dd><dt>Actual</dt><dd>${html(JSON.stringify(f.actual))}</dd><dt>Permitted</dt><dd>${html(JSON.stringify(f.permitted))}</dd>${f.calculation?`<dt>Calculation</dt><dd>${html(f.calculation)}</dd>`:''}</dl>${(f.possibleSolutions||[]).length?`<h4>Mogelijke aanpassing</h4><ul>${f.possibleSolutions.map(x=>`<li>${html(x)}</li>`).join('')}</ul>`:''}</div>`}
function overnightLabel(n){return n.state==='SPECIFIC_LIVE_ACCOMMODATION'?`${n.property.name} · live geverifieerd`:`${n.canonicalOvernightName} · geplande accommodatiezone`}
function overnightSearch(n){return n.state==='PLANNED_ACCOMMODATION_ZONE'&&n.externalSearchUrl?`<a class="night-search" href="${html(n.externalSearchUrl)}" target="_blank" rel="noopener noreferrer">Zoek verblijf in deze zone ↗</a>`:''}
function renderPlan(plan){currentPlan=plan;$('emptyPlan').classList.add('hidden');$('planView').classList.remove('hidden');$('tripTitle').textContent=`${plan.destinationName} · ${plan.days.length} dagen`;$('tripMeta').textContent=`${plan.structure==='base'?'Slimme uitvalsbasis':'Roadtrip'} · ${plan.topology} · ${plan.routing.status==='live'?'live route':'offline route-inschatting'}`;const v=validateCanonicalPlan(plan);plan.validation=v;$('validation').innerHTML=v.valid?`<div class="valid">✓ CanonicalPlan geldig · ${v.metrics.nights} nachten · ${v.metrics.offlinePois} offline POI’s</div>`:`<div class="invalid">${v.errors.map(e=>html(e.code)).join(' · ')}</div>`;$('summary').innerHTML=`<div><strong>${Math.round(v.metrics.totalDistanceKm||0)} km</strong><small>reisafstand</small></div><div><strong>${plan.accommodationChanges}</strong><small>accommodatiewissels</small></div><div><strong>€${plan.budget.total}</strong><small>offline budgetraming</small></div><div><strong>${plan.offlinePois.length}</strong><small>offline POI’s</small></div>`;$('enrichment').innerHTML=Object.entries(plan.enrichment||{}).map(([k,val])=>`<span><b>${html(k)}</b> ${html(val)}</span>`).join('');$('days').innerHTML=plan.days.map(d=>{const night=plan.overnights.find(n=>n.afterDay===d.day);return`<article class="panel day"><div class="day-head"><div><p class="eyebrow">DAG ${d.day} · ${html(d.date)}</p><h3>${html(d.typeLabel)} · ${html(d.from)} → ${html(d.to)}</h3></div><span>${Math.round(d.distanceKm)} km · ${Number(d.driveHours).toFixed(1)} h</span></div><p>${html(d.primaryPlan)}</p>${(d.offlinePois||[]).length?`<div class="chips">${d.offlinePois.map(p=>`<span>● ${html(p.name)}</span>`).join('')}</div>`:''}${night?`<div class="night"><strong>Nacht ${night.night}</strong><span>${html(overnightLabel(night))}${overnightSearch(night)}</span></div>`:''}<small class="source">${html(d.routeSource)}${d.transportMode&&d.transportMode!=='road'?` · ${html(d.transportMode)}`:''}</small></article>`}).join('');$('mapCaption').textContent=`${plan.days.length} dagen · ${plan.offlinePois.length} POI’s · ${plan.overnights.length} nachten`;renderMap($('map'),plan);diagnosticView(null)}
async function buildPlanFromForm(e){e?.preventDefault();status('Offline reis bouwen…','working');diagnosticView(null);const trip=readTrip();const summary=chooseDestination(trip.destinationQuery);if(!summary){diagnosticView({code:'DESTINATION_NOT_IN_OFFLINE_CATALOG',reason:'Geen passende offline regio gevonden.',constraint:'destination',actual:trip.destinationQuery,permitted:'offline region',possibleSolutions:['Kies een regio uit de bestemmingslijst.']});status('Geen geldig plan','error');return}currentDestination=await data.getRegion(summary.id);const result=createCanonicalPlan(trip,currentDestination,data);if(!result.ok){diagnosticView(result.failure);status('Geen geldig plan','error');return}const structural=validateCanonicalPlan(result.plan);if(!structural.valid){diagnosticView({code:'INTERNAL_SOLVER_FAILURE',reason:'De solver produceerde een plan dat de autoritatieve validator niet accepteert.',constraint:'canonical-validator',actual:structural.errors.map(x=>x.code),permitted:'zero validation errors',possibleSolutions:['Bewaar deze diagnostics en meld de fout.']});status('Interne solverfout','error');return}renderPlan(result.plan);status('Offline plan klaar','ok');if(!trip.liveData)return;status('Live verrijking…','working');const enriched=await runEnrichmentPipeline(result.plan,liveProviders,(stage,p)=>{renderPlan(p);status(`Live ${stage} verwerkt…`,'working')});renderPlan(enriched);status('Plan klaar','ok')}
function renderSaved(){const rows=loadTrips();$('savedTrips').innerHTML=rows.length?rows.map((p,i)=>`<div class="saved"><button data-load="${i}"><strong>${html(p.destinationName)}</strong><small>${p.days.length} dagen · ${html(p.trip.startDate)}</small></button><button class="danger" data-delete="${html(p.createdAt)}">×</button></div>`).join(''):'<p class="muted">Nog geen opgeslagen reizen.</p>';$('savedTrips').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>renderPlan(rows[Number(b.dataset.load)]));$('savedTrips').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{deleteTrip(b.dataset.delete);renderSaved()})}
async function init(){setToday();renderPreferences();syncVehicleDefaults();status('Offline catalogus laden…','working');await data.init();const stats=data.stats();$('datasetStats').textContent=`Dataset ${DATASET_VERSION} · ${stats.countries} landen · ${stats.regions} regio’s · ${stats.pois} POI’s · ${stats.accommodationZones} accommodatiezones`;const dest=$('destinationList');dest.innerHTML=data.index.regions.map(r=>`<option value="${html(r.name)}">${html(r.country)}</option>`).join('');const origins=$('originList');origins.innerHTML=[...(data.index.originPlaces||[]),...(data.index.baseIndex||[])].map(p=>`<option value="${html(p.name)}"></option>`).join('');$('headerVersion').textContent=`v${VERSION} · b${BUILD}`;$('versionLabel').textContent=`ReisSlim v${VERSION} · Build ${BUILD}`;$('planForm').addEventListener('submit',buildPlanFromForm);$('transport').addEventListener('change',syncVehicleDefaults);['fuelRangeKm','vehicleHeightM','vehicleLengthM','vehicleWeightKg','vehicleMaxSpeedKmh'].forEach(id=>$(id).addEventListener('input',()=>{$(id).dataset.user='1'}));$('gpxBtn').onclick=()=>currentPlan&&downloadGpx(currentPlan);$('saveTripBtn').onclick=()=>{if(currentPlan){saveTrip(currentPlan);renderSaved();status('Reis opgeslagen','ok')}};$('newTripBtn').onclick=()=>{currentPlan=null;$('planView').classList.add('hidden');$('emptyPlan').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};renderSaved();status('Gereed','ok');if('serviceWorker'in navigator)navigator.serviceWorker.register(`service-worker.js?v=${BUILD}`).catch(()=>{});}
init().catch(err=>{console.error(err);status('Startfout','error');diagnosticView({code:'APP_START_FAILURE',reason:err.message,constraint:'startup',actual:err.message,permitted:'offline data available',possibleSolutions:['Controleer of de data-*.json bestanden zijn meegekopieerd.']})});
