import { BUILD, DATASET_VERSION, VERSION, preferenceDefinitions, vehicleProfiles } from './config.js';
import { TravelDataClient } from './travel-data.js';
import { createCanonicalPlan, normalizeTripInput } from './canonical-plan-engine.js';
import { validateCanonicalPlan } from './validator.js';
import { discoverDestinations } from './destination-discovery.js';
import { liveProviders, runEnrichmentPipeline } from './enrichment.js';
import { downloadGpx } from './gpx-generator.js';
import { renderDestinationComparisonMap, renderMap } from './map-view.js';
import { deleteTrip, loadTrips, saveTrip } from './storage.js';
import { annotatePlanContext, summarizePlanContext } from './trip-context.js';

const $=id=>document.getElementById(id);
const data=new TravelDataClient();
let currentPlan=null,currentDestination=null,currentShortlist=[],discoveryCompareIds=new Set(),activeDiscoveryTrip=null;
const imageCache=new Map();
const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=value=>{try{const u=new URL(String(value||''));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
function status(text,tone=''){const el=$('status');el.textContent=text;el.dataset.tone=tone}
function setToday(){if(!$('startDate').value){const d=new Date();d.setDate(d.getDate()+14);$('startDate').value=d.toISOString().slice(0,10)}}
function renderPreferences(){const box=$('preferenceGrid');box.innerHTML=preferenceDefinitions.map(([id,label])=>`<label class="pref"><span>${html(label)}</span><input data-pref="${id}" type="range" min="0" max="3" step="1" value="${id==='natuur'||id==='motor'?2:0}"><b id="pref-${id}">${id==='natuur'||id==='motor'?2:0}</b></label>`).join('');box.querySelectorAll('[data-pref]').forEach(x=>x.addEventListener('input',()=>{$(`pref-${x.dataset.pref}`).textContent=x.value}))}
function syncVehicleDefaults(){const p=vehicleProfiles[$('transport').value];if(!$('fuelRangeKm').dataset.user)$('fuelRangeKm').value=p.defaultFuelRangeKm;const dims=['vehicleHeightM','vehicleLengthM','vehicleWeightKg','vehicleMaxSpeedKmh'];const defaults=$('transport').value==='motorhome'?[3.1,7.2,3500,100]:$('transport').value==='caravan'?[2.7,11.5,3200,90]:[1.8,4.5,1800,130];dims.forEach((id,i)=>{if(!$(id).dataset.user)$(id).value=defaults[i]})}
function readTrip(){const prefs={},selected=[];document.querySelectorAll('[data-pref]').forEach(x=>{prefs[x.dataset.pref]=Number(x.value);if(Number(x.value)>0)selected.push(x.dataset.pref)});return normalizeTripInput({origin:$('origin').value.trim(),destinationQuery:$('destinationQuery').value.trim(),startDate:$('startDate').value,days:Number($('days').value),budget:Number($('budget').value),transport:$('transport').value,tripStructure:$('tripStructure').value,routeTopology:$('routeTopology').value,tripPace:$('tripPace').value,maxDrive:Number($('maxDrive').value),maxChanges:Number($('maxChanges').value),accommodationType:$('accommodationType').value,comfort:$('comfort').value,adults:Number($('adults').value),children:Number($('children').value),routeStyle:$('routeStyle').value,fuelRangeKm:Number($('fuelRangeKm').value),vehicleMaxSpeedKmh:Number($('vehicleMaxSpeedKmh').value),vehicleHeightM:Number($('vehicleHeightM').value),vehicleLengthM:Number($('vehicleLengthM').value),vehicleWeightKg:Number($('vehicleWeightKg').value),strictBudget:$('strictBudget').checked,strictDrive:$('strictDrive').checked,strictChanges:$('strictChanges').checked,liveData:$('liveData').checked,preferences:selected,preferenceWeights:prefs})}
function chooseDestination(query){const rows=data.search(query,20);if(!rows.length)return null;const q=query.toLowerCase();return rows.find(r=>r.name.toLowerCase()===q)||rows.find(r=>r.searchTerms?.some(s=>String(s).toLowerCase()===q))||rows[0]}
function diagnosticView(f){if(!f){$('diagnostics').innerHTML='';return}$('diagnostics').innerHTML=`<div class="diagnostic"><strong>${html(f.code)}</strong><p>${html(f.reason)}</p><dl><dt>Constraint</dt><dd>${html(f.constraint)}</dd><dt>Actual</dt><dd>${html(JSON.stringify(f.actual))}</dd><dt>Permitted</dt><dd>${html(JSON.stringify(f.permitted))}</dd>${f.calculation?`<dt>Calculation</dt><dd>${html(f.calculation)}</dd>`:''}</dl>${(f.possibleSolutions||[]).length?`<h4>Mogelijke aanpassing</h4><ul>${f.possibleSolutions.map(x=>`<li>${html(x)}</li>`).join('')}</ul>`:''}</div>`}
function overnightLabel(n){return n.state==='SPECIFIC_LIVE_ACCOMMODATION'?`${n.property.name} · live geverifieerd`:`${n.canonicalOvernightName} · geplande accommodatiezone`}
function overnightSearch(n){return n.state==='PLANNED_ACCOMMODATION_ZONE'&&n.externalSearchUrl?`<a class="night-search" href="${html(n.externalSearchUrl)}" target="_blank" rel="noopener noreferrer">Zoek verblijf in deze zone ↗</a>`:''}
function hideDiscovery(){currentShortlist=[];$('discoveryView')?.classList.add('hidden')}
function hidePlan(){currentPlan=null;$('planView').classList.add('hidden')}
function showEmpty(){hideDiscovery();hidePlan();$('emptyPlan').classList.remove('hidden')}
function routeRoadLabels(day){
  const seen=new Set(),rows=[];
  for(const step of day.roadDetails||[]){const label=[step.ref,step.name].filter(Boolean).join(' · ').trim();if(!label||seen.has(label))continue;seen.add(label);rows.push(label);if(rows.length>=8)break}
  return rows;
}
function dayContextHtml(day,night){
  const pois=day.offlinePois||[],rests=day.plannedStops||[],roads=routeRoadLabels(day),cities=(day.routeCities||[]).filter(Boolean);
  const restLine=rests.length?rests.map(x=>`${x.name}${x.approxAfterKm?` (±${x.approxAfterKm} km)`:''}`).join(' · '):Number(day.plannedRestCount||0)>0?`${day.plannedRestCount} geplande rijpauze${day.plannedRestCount===1?'':'s'}; specifieke stop wordt onderweg/live verfijnd`:'Geen extra rijpauze nodig volgens voertuigprofiel';
  return `<div class="day-detail-grid"><div><b>POI / beleven</b><span>${pois.length?pois.map(p=>html(p.name)).join(' · '):'Geen extra POI op deze etappe'}</span></div><div><b>Rust / koffie</b><span>${html(restLine)}</span></div><div><b>Steden / routepunten</b><span>${html(cities.join(' → ')||`${day.from} → ${day.to}`)}</span></div>${roads.length?`<div><b>Wegen</b><span>${roads.map(html).join(' · ')}</span></div>`:''}${night?`<div><b>Accommodatie</b><span>${html(overnightLabel(night))}${overnightSearch(night)}</span></div>`:''}</div>`;
}
function renderPlan(plan){
  annotatePlanContext(plan,data);currentPlan=plan;hideDiscovery();$('emptyPlan').classList.add('hidden');$('planView').classList.remove('hidden');$('tripTitle').textContent=`${plan.destinationName} · ${plan.days.length} dagen`;$('tripMeta').textContent=`${plan.structure==='base'?'Slimme uitvalsbasis':'Roadtrip'} · ${plan.topology} · ${plan.routing.status==='live'?'live wegroute':'offline route-inschatting'}`;
  const v=validateCanonicalPlan(plan),context=summarizePlanContext(plan);plan.validation=v;$('validation').innerHTML=v.valid?`<div class="valid">✓ CanonicalPlan geldig · ${v.metrics.nights} nachten · ${v.metrics.offlinePois} offline POI’s</div>`:`<div class="invalid">${v.errors.map(e=>html(e.code)).join(' · ')}</div>`;
  $('summary').innerHTML=`<div><strong>${Math.round(v.metrics.totalDistanceKm||0)} km</strong><small>reisafstand</small></div><div><strong>${context.plannedRestCount}</strong><small>geplande rijpauzes</small></div><div><strong>${context.nightCount}</strong><small>overnachtingen</small></div><div><strong>${context.poiCount}</strong><small>POI’s in dagplan</small></div>`;
  $('enrichment').innerHTML=Object.entries(plan.enrichment||{}).map(([k,val])=>`<span><b>${html(k)}</b> ${html(val)}</span>`).join('');
  $('days').innerHTML=plan.days.map(d=>{const night=plan.overnights.find(n=>n.afterDay===d.day);return`<article class="panel day"><div class="day-head"><div><p class="eyebrow">DAG ${d.day} · ${html(d.date)}</p><h3>${html(d.typeLabel)} · ${html(d.from)} → ${html(d.to)}</h3></div><span>${Math.round(d.distanceKm)} km · ${Number(d.driveHours).toFixed(1)} h</span></div><p>${html(d.primaryPlan)}</p>${dayContextHtml(d,night)}<small class="source">${html(d.routeSource)}${d.transportMode&&d.transportMode!=='road'?` · ${html(d.transportMode)}`:''}</small></article>`}).join('');
  $('mapCaption').textContent=`${plan.days.length} dagen · ${context.poiCount} POI’s · ${context.plannedRestCount} rijpauzes · ${plan.overnights.length} nachten · ${plan.trip?.liveData!==false?'OpenStreetMap-context indien online':'volledig offline weergave'}`;renderMap($('map'),plan,{liveBasemap:plan.trip?.liveData!==false});diagnosticView(null)
}
function cardFallback(candidate){const tags=candidate.tags||[];return tags.includes('mountains')?'🏔️':tags.includes('coast')?'🌊':tags.includes('culture')?'🏛️':tags.includes('desert')?'🏜️':'🌿'}
function proposalDayRows(candidate){
  const plan=candidate.plan;
  return plan.days.map(day=>{const night=plan.overnights.find(n=>n.afterDay===day.day),rests=day.plannedStops||[],pois=day.offlinePois||[];return `<div class="proposal-day-row"><b>D${day.day}</b><div><strong>${html(day.from)} → ${html(day.to)}</strong><small>${Math.round(day.distanceKm)} km · ${Number(day.driveHours).toFixed(1)} u</small>${pois.length?`<span><i>POI</i> ${pois.map(p=>html(p.name)).join(' · ')}</span>`:''}<span><i>Rust</i> ${rests.length?rests.map(r=>html(r.name)).join(' · '):Number(day.plannedRestCount||0)>0?`${day.plannedRestCount} geplande pauze${day.plannedRestCount===1?'':'s'}`:'geen extra rijpauze'}</span>${night?`<span><i>Nacht</i> ${html(night.state==='SPECIFIC_LIVE_ACCOMMODATION'?night.property?.name:night.canonicalOvernightName)}</span>`:''}</div></div>`}).join('');
}
function proposalContext(candidate){return candidate.context||summarizePlanContext(candidate.plan)}
function renderComparisonTable(){
  const rows=currentShortlist,host=$('discoveryComparison');if(!rows.length){host.innerHTML='<p class="muted">Geen voorstellen om te vergelijken.</p>';return}
  host.innerHTML=`<table class="option-table"><thead><tr><th>#</th><th>Bestemming</th><th>Match</th><th>Reis</th><th>POI</th><th>Rust</th><th>Overnachting</th><th>Zwaarste dag</th><th>Budget</th><th></th></tr></thead><tbody>${rows.map(c=>{const ctx=proposalContext(c);return`<tr><td><b>${c.rank}</b></td><td><strong>${html(c.name)}</strong><small>${html(c.country)}</small></td><td><strong>${c.score}/100</strong></td><td>${Math.round(c.totalDistanceKm)} km</td><td><strong>${ctx.poiCount}</strong><small>${ctx.pois.slice(0,2).map(p=>html(p.name)).join(' · ')}</small></td><td><strong>${ctx.plannedRestCount}</strong><small>${ctx.restStops.slice(0,2).map(r=>html(r.name)).join(' · ')||'voertuigprofiel'}</small></td><td><strong>${ctx.nightCount} nachten</strong><small>${ctx.overnightNames.slice(0,2).map(html).join(' · ')}</small></td><td>${c.maxDayDrive.toFixed(1)} u</td><td>€${c.estimate}</td><td><button class="table-plan-button" type="button" data-select-destination="${html(c.id)}">Plan</button></td></tr>`}).join('')}</tbody></table>`;
}
function wireDiscoveryActions(){document.querySelectorAll('[data-select-destination]').forEach(b=>b.addEventListener('click',()=>selectDiscoveryDestination(b.dataset.selectDestination)))}
function renderDiscovery(result,trip){
  activeDiscoveryTrip=trip;currentShortlist=result.shortlist;currentPlan=null;$('emptyPlan').classList.add('hidden');$('planView').classList.add('hidden');$('discoveryView').classList.remove('hidden');
  $('discoveryTitle').textContent=`Beste roadtrips vanaf ${result.origin.name}`;$('discoveryMeta').textContent=`${currentShortlist.length} haalbare voorstellen · ${result.evaluated} regio’s vooraf beoordeeld · iedere optie bevat een geldig dag-, POI-, rust- en overnachtingsplan`;
  $('destinationCards').innerHTML=currentShortlist.map(c=>{const ctx=proposalContext(c);return`<article class="destination-card" data-destination-id="${html(c.id)}"><div class="destination-photo"><div class="destination-photo-fallback">${cardFallback(c)}</div><img data-destination-image="${html(c.id)}" alt="${html(c.name)}" loading="lazy"><span class="rank-badge">#${c.rank}</span><span class="score-badge">${c.score}/100</span><a data-image-credit="${html(c.id)}" class="image-credit hidden" target="_blank" rel="noopener noreferrer">Wikimedia ↗</a></div><div class="destination-card-body"><p class="eyebrow">${html(c.country)}</p><h3>${html(c.name)}</h3><p class="destination-reason">${html(c.reason)}</p><div class="destination-metrics"><span><b>${Math.round(c.totalDistanceKm)} km</b><small>totale reis</small></span><span><b>€${c.estimate}</b><small>raming</small></span><span><b>${c.maxDayDrive.toFixed(1)} u</b><small>zwaarste rijdag</small></span></div><div class="proposal-context"><div><b>POI · ${ctx.poiCount}</b><span>${ctx.pois.slice(0,3).map(p=>html(p.name)).join(' · ')||'—'}</span></div><div><b>Rust · ${ctx.plannedRestCount}</b><span>${ctx.restStops.slice(0,3).map(r=>html(r.name)).join(' · ')||'Pauzes volgens voertuigprofiel'}</span></div><div><b>Accommodatie · ${ctx.nightCount} nachten</b><span>${ctx.overnightNames.slice(0,3).map(html).join(' · ')||'Geen overnachting'}</span></div></div><details class="proposal-day-details"><summary>Dag-voor-dag voorstel</summary><div class="proposal-day-list">${proposalDayRows(c)}</div></details><div class="chips">${(c.tags||[]).slice(0,5).map(t=>`<span>${html(t)}</span>`).join('')}</div><div class="destination-actions"><button class="primary small" type="button" data-select-destination="${html(c.id)}">Kies deze reis</button></div></div></article>`}).join('');
  renderComparisonTable();renderDestinationComparisonMap($('discoveryMap'),result.origin,currentShortlist,{liveBasemap:trip.liveData!==false});wireDiscoveryActions();diagnosticView(null);hydrateDiscoveryImages(currentShortlist,trip.liveData);
}
async function hydrateDiscoveryImages(rows,enabled=true){if(!enabled)return;await Promise.all(rows.map(async c=>{let image=imageCache.get(c.id);if(image===undefined){try{image=await liveProviders.images({destinationName:c.name,destinationId:c.id,destinationAnchorName:c.anchor?.name,destinationCountry:c.country});imageCache.set(c.id,image||null)}catch{imageCache.set(c.id,null);image=null}}if(!image?.url)return;const id=CSS.escape(c.id),img=document.querySelector(`[data-destination-image="${id}"]`),credit=document.querySelector(`[data-image-credit="${id}"]`);if(!img)return;img.onload=()=>img.classList.add('loaded');img.onerror=()=>img.removeAttribute('src');img.src=safeUrl(image.url);if(credit&&image.source){credit.href=safeUrl(image.sourceUrl)||'https://commons.wikimedia.org/';credit.classList.remove('hidden')}}))}
async function selectDiscoveryDestination(id){const candidate=currentShortlist.find(c=>c.id===id);if(!candidate)return;$('destinationQuery').value=candidate.name;updateSubmitLabel();currentDestination=await data.getRegion(candidate.id);renderPlan(candidate.plan);status('Offline plan klaar','ok');if(!activeDiscoveryTrip?.liveData)return;status('Live verrijking…','working');const enriched=await runEnrichmentPipeline(candidate.plan,liveProviders,(stage,p)=>{renderPlan(p);status(`Live ${stage} verwerkt…`,'working')});renderPlan(enriched);status('Plan klaar','ok')}
async function discoverFromForm(trip){status('Beste offline roadtrips zoeken…','working');const result=await discoverDestinations(trip,data,{limit:6,prefilter:42});if(!result.ok){diagnosticView(result.failure);status('Geen haalbare voorstellen','error');return}renderDiscovery(result,trip);status(`${result.shortlist.length} reisvoorstellen klaar`,'ok')}
async function buildPlanFromForm(e){e?.preventDefault();diagnosticView(null);const trip=readTrip();if(!trip.destinationQuery){await discoverFromForm(trip);return}status('Offline reis bouwen…','working');hideDiscovery();const summary=chooseDestination(trip.destinationQuery);if(!summary){diagnosticView({code:'DESTINATION_NOT_IN_OFFLINE_CATALOG',reason:'Geen passende offline regio gevonden.',constraint:'destination',actual:trip.destinationQuery,permitted:'offline region',possibleSolutions:['Laat bestemming leeg voor de beste voorstellen.','Kies een regio uit de bestemmingslijst.']});status('Geen geldig plan','error');return}currentDestination=await data.getRegion(summary.id);const result=createCanonicalPlan(trip,currentDestination,data);if(result.ok)annotatePlanContext(result.plan,data);if(!result.ok){diagnosticView(result.failure);status('Geen geldig plan','error');return}const structural=validateCanonicalPlan(result.plan);if(!structural.valid){diagnosticView({code:'INTERNAL_SOLVER_FAILURE',reason:'De solver produceerde een plan dat de autoritatieve validator niet accepteert.',constraint:'canonical-validator',actual:structural.errors.map(x=>x.code),permitted:'zero validation errors',possibleSolutions:['Bewaar deze diagnostics en meld de fout.']});status('Interne solverfout','error');return}renderPlan(result.plan);status('Offline plan klaar','ok');if(!trip.liveData)return;status('Live verrijking…','working');const enriched=await runEnrichmentPipeline(result.plan,liveProviders,(stage,p)=>{renderPlan(p);status(`Live ${stage} verwerkt…`,'working')});renderPlan(enriched);status('Plan klaar','ok')}
function updateSubmitLabel(){const blank=!$('destinationQuery').value.trim();$('planSubmit').textContent=blank?'Vind beste roadtrips':'Bouw reisplan';$('destinationHint').textContent=blank?'Leeg = ReisSlim vergelijkt de beste haalbare bestemmingen vanaf je vertrekpunt.':'Deze regio wordt direct gepland.'}
function renderSaved(){const rows=loadTrips();$('savedTrips').innerHTML=rows.length?rows.map((p,i)=>`<div class="saved"><button data-load="${i}"><strong>${html(p.destinationName)}</strong><small>${p.days.length} dagen · ${html(p.trip.startDate)}</small></button><button class="danger" data-delete="${html(p.createdAt)}">×</button></div>`).join(''):'<p class="muted">Nog geen opgeslagen reizen.</p>';$('savedTrips').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>renderPlan(rows[Number(b.dataset.load)]));$('savedTrips').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{deleteTrip(b.dataset.delete);renderSaved()})}
async function init(){setToday();renderPreferences();syncVehicleDefaults();status('Offline catalogus laden…','working');await data.init();const stats=data.stats();$('datasetStats').textContent=`Dataset ${DATASET_VERSION} · ${stats.countries} landen · ${stats.regions} regio’s · ${stats.pois} POI’s · ${stats.accommodationZones} accommodatiezones`;const dest=$('destinationList');dest.innerHTML=data.index.regions.map(r=>`<option value="${html(r.name)}">${html(r.country)}</option>`).join('');const origins=$('originList');origins.innerHTML=[...(data.index.originPlaces||[]),...(data.index.baseIndex||[])].map(p=>`<option value="${html(p.name)}"></option>`).join('');$('headerVersion').textContent=`v${VERSION} · b${BUILD}`;$('versionLabel').textContent=`ReisSlim v${VERSION} · Build ${BUILD}`;$('planForm').addEventListener('submit',buildPlanFromForm);$('transport').addEventListener('change',syncVehicleDefaults);$('destinationQuery').addEventListener('input',updateSubmitLabel);['fuelRangeKm','vehicleHeightM','vehicleLengthM','vehicleWeightKg','vehicleMaxSpeedKmh'].forEach(id=>$(id).addEventListener('input',()=>{$(id).dataset.user='1'}));$('gpxBtn').onclick=()=>currentPlan&&downloadGpx(currentPlan);$('saveTripBtn').onclick=()=>{if(currentPlan){saveTrip(currentPlan);renderSaved();status('Reis opgeslagen','ok')}};$('newTripBtn').onclick=()=>{$('destinationQuery').value='';showEmpty();updateSubmitLabel();window.scrollTo({top:0,behavior:'smooth'})};renderSaved();updateSubmitLabel();status('Gereed','ok');if('serviceWorker'in navigator)navigator.serviceWorker.register(`service-worker.js?v=${BUILD}`).catch(()=>{});}
init().catch(err=>{console.error(err);status('Startfout','error');diagnosticView({code:'APP_START_FAILURE',reason:err.message,constraint:'startup',actual:err.message,permitted:'offline data available',possibleSolutions:['Controleer of de data-*.json bestanden zijn meegekopieerd.']})});
