function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function round(v){return Math.round((num(v))*100)/100}
function sum(xs){return xs.reduce((a,b)=>a+num(b),0)}

export function ensureCostFramework(data){
 data.settings=data.settings||{};
 data.settings.costFramework=data.settings.costFramework||{currency:'EUR',overheadPct:12,contingencyPct:8,defaultStaffRate:92,defaultEquipmentRate:45,defaultConsumablesPerDut:6};
 const cf=data.settings.costFramework;
 const roleRate=(role='')=>/manager/i.test(role)?135:/engineer|specialist/i.test(role)?118:/technician/i.test(role)?82:cf.defaultStaffRate;
 for(const s of data.staff||[]) if(!Number.isFinite(Number(s.costRatePerHour))) s.costRatePerHour=roleRate(s.role);
 const typeRate=(type='')=>/EMC/i.test(type)?210:/Vibration/i.test(type)?165:/Climatic|Thermal Shock/i.test(type)?125:/Reliability|Pressure|Durability/i.test(type)?110:/X-Ray/i.test(type)?145:/Electrical|Oscilloscope|DAQ|HIL/i.test(type)?58:/Microscope|Dimensional|Material|Thermal Camera/i.test(type)?72:cf.defaultEquipmentRate;
 for(const e of data.equipment||[]) if(!Number.isFinite(Number(e.chargeRatePerHour))) e.chargeRatePerHour=typeRate(e.type);
 for(const m of data.methods||[]){
   if(!Number.isFinite(Number(m.consumablesPerDut)))m.consumablesPerDut=/EMC|Material|Failure Analysis/i.test(m.category)?18:/Environmental|Reliability|Durability/i.test(m.category)?10:cf.defaultConsumablesPerDut;
   if(!Number.isFinite(Number(m.fixedConsumables)))m.fixedConsumables=/Failure Analysis/i.test(m.category)?85:/EMC/i.test(m.category)?55:20;
   if(!Number.isFinite(Number(m.externalCost)))m.externalCost=/X-Ray/i.test(m.id)?160:0;
   if(!Number.isFinite(Number(m.costRiskPct)))m.costRiskPct=Math.round(Math.max(4,Math.abs((num(m.avgActualFactor,1)-1))*100));
 }
 for(const d of data.devTasks||[]){if(!Number.isFinite(Number(d.fixtureCost)))d.fixtureCost=350+num(d.estimatedTechnicianHours)*8;if(!Number.isFinite(Number(d.externalCost)))d.externalCost=/Pressure|EMC/i.test((d.requiredSkills||[]).join(' '))?600:120;}
 for(const p of data.programmes||[]){if(!Number.isFinite(Number(p.budget)))p.budget=0;}
 return data;
}

export function currency(data,value,compact=false){const cur=data.settings?.costFramework?.currency||'EUR';const n=num(value);try{return new Intl.NumberFormat(undefined,{style:'currency',currency:cur,maximumFractionDigits:compact?0:2,notation:compact&&Math.abs(n)>=10000?'compact':'standard'}).format(n)}catch{return `${cur} ${n.toFixed(compact?0:2)}`}}

export function attendedHours(method,totalHours=null){if(!method)return 0;const setup=num(method.setupHours),tear=num(method.teardownHours),analysis=num(method.analysisHours),exec=num(method.executionHours);return method.continuousStaffing?num(totalHours,setup+exec+tear+analysis):setup+tear+analysis;}

export function developmentCost(data,dev){if(!dev)return {labour:0,fixture:0,external:0,total:0};const engineers=(data.staff||[]).filter(s=>/engineer|specialist|manager/i.test(s.role||'')),techs=(data.staff||[]).filter(s=>/technician/i.test(s.role||''));const er=engineers.length?sum(engineers.map(s=>s.costRatePerHour))/engineers.length:num(data.settings?.costFramework?.defaultStaffRate,92)*1.2;const tr=techs.length?sum(techs.map(s=>s.costRatePerHour))/techs.length:num(data.settings?.costFramework?.defaultStaffRate,92)*.85;const labour=num(dev.estimatedEngineeringHours)*er+num(dev.estimatedTechnicianHours)*tr,fixture=num(dev.fixtureCost),external=num(dev.externalCost);return {labour:round(labour),fixture:round(fixture),external:round(external),total:round(labour+fixture+external)};}

export function estimateLegCost(data,leg,{useActual=false}={}){ensureCostFramework(data);const method=(data.methods||[]).find(m=>m.id===leg.methodId);if(!method)return {labour:0,equipment:0,consumables:0,external:0,development:0,overhead:0,contingency:0,total:0,currency:data.settings.costFramework.currency};const booking=(data.bookings||[]).find(b=>b.legId===leg.id);const assigned=(data.staff||[]).find(s=>s.id===(leg.staffId||booking?.staffId));const eq=(data.equipment||[]).find(e=>e.id===(leg.equipmentId||booking?.equipmentId))||(data.equipment||[]).find(e=>e.type===method.equipmentType);const standardWall=num(method.setupHours)+num(method.executionHours)+num(method.teardownHours)+num(method.analysisHours);const run=(data.testRuns||[]).filter(r=>r.legId===leg.id&&r.status==='Completed').sort((a,b)=>new Date(b.actualEnd)-new Date(a.actualEnd))[0];const wall=useActual&&run?num(run.actualHours,standardWall):(booking?.start&&booking?.end?Math.max(standardWall,(new Date(booking.end)-new Date(booking.start))/3600000):standardWall);const staffH=useActual&&run?Math.min(wall,method.continuousStaffing?wall:attendedHours(method)):attendedHours(method,wall);const rate=num(assigned?.costRatePerHour,data.settings.costFramework.defaultStaffRate),eqRate=num(eq?.chargeRatePerHour,data.settings.costFramework.defaultEquipmentRate);const labour=staffH*rate*num(method.staffing,1),equipment=wall*eqRate,consumables=num(method.fixedConsumables)+num(method.consumablesPerDut)*num(leg.dutIds?.length),external=num(method.externalCost),dev=developmentCost(data,(data.devTasks||[]).find(d=>d.id===leg.developmentTaskId)).total;const direct=labour+equipment+consumables+external+dev;const overhead=direct*num(data.settings.costFramework.overheadPct)/100,contingency=useActual?0:(direct+overhead)*num(data.settings.costFramework.contingencyPct)/100;return {labour:round(labour),equipment:round(equipment),consumables:round(consumables),external:round(external),development:round(dev),overhead:round(overhead),contingency:round(contingency),total:round(direct+overhead+contingency),wallHours:round(wall),staffHours:round(staffH),equipmentId:eq?.id||null,staffId:assigned?.id||null,currency:data.settings.costFramework.currency};}

export function programmeCost(data,programmeId){ensureCostFramework(data);const legs=(data.legs||[]).filter(l=>l.programmeId===programmeId);const estimates=legs.map(l=>estimateLegCost(data,l));const actuals=legs.map(l=>estimateLegCost(data,l,{useActual:true}));const p=(data.programmes||[]).find(x=>x.id===programmeId);const sumKey=(rows,k)=>round(sum(rows.map(x=>x[k])));const estimated={labour:sumKey(estimates,'labour'),equipment:sumKey(estimates,'equipment'),consumables:sumKey(estimates,'consumables'),external:sumKey(estimates,'external'),development:sumKey(estimates,'development'),overhead:sumKey(estimates,'overhead'),contingency:sumKey(estimates,'contingency'),total:sumKey(estimates,'total')};const completedIds=new Set(legs.filter(l=>l.status==='Completed').map(l=>l.id));const actualRows=legs.map((l,i)=>completedIds.has(l.id)?actuals[i]:null).filter(Boolean);const actualToDate=sumKey(actualRows,'total');const remaining=round(sum(legs.map((l,i)=>completedIds.has(l.id)?0:estimates[i].total)));const forecast=round(actualToDate+remaining);const budget=num(p?.budget)||round(estimated.total*1.08);return {programmeId,estimated,actualToDate,remaining,forecast,budget,variance:round(forecast-budget),variancePct:budget?round((forecast-budget)/budget*100):0,legs:legs.map((l,i)=>({leg:l,estimate:estimates[i],actual:completedIds.has(l.id)?actuals[i]:null}))};}

export function portfolioCost(data){ensureCostFramework(data);const programmes=(data.programmes||[]).map(p=>({...programmeCost(data,p.id),programme:p}));const keys=['labour','equipment','consumables','external','development','overhead','contingency'];const breakdown=Object.fromEntries(keys.map(k=>[k,round(sum(programmes.map(x=>x.estimated[k]))) ]));return {programmes,totalBudget:round(sum(programmes.map(x=>x.budget))),totalForecast:round(sum(programmes.map(x=>x.forecast))),variance:round(sum(programmes.map(x=>x.forecast-x.budget))),breakdown,development:breakdown.development,equipment:breakdown.equipment,labour:breakdown.labour};}

export function methodCost(data,methodId,dutCount=8){const m=(data.methods||[]).find(x=>x.id===methodId);if(!m)return null;const fake={id:'COST-PREVIEW',methodId,dutIds:Array.from({length:Math.max(1,dutCount)},(_,i)=>`D${i+1}`),staffId:null,equipmentId:null,developmentTaskId:null};return estimateLegCost(data,fake);}
