import { DEMO_NOW } from './data.js';
import { ensureCostFramework, estimateLegCost, portfolioCost } from './costs.js';

function overlap(a,b,c,d){return new Date(a)<new Date(d)&&new Date(b)>new Date(c);}
export function calibrationAt(data,eqId,at=DEMO_NOW,{allowScheduled=false}={}){const when=new Date(at);return data.calibrations.filter(c=>c.equipmentId===eqId&&new Date(c.calibrationDate)<=when&&(allowScheduled||c.result!=='Scheduled')).sort((a,b)=>new Date(b.calibrationDate)-new Date(a.calibrationDate))[0]||null;}
export function nextScheduledCalibration(data,eqId,at=DEMO_NOW){const when=new Date(at);return data.calibrations.filter(c=>c.equipmentId===eqId&&c.result==='Scheduled'&&new Date(c.calibrationDate)>when).sort((a,b)=>new Date(a.calibrationDate)-new Date(b.calibrationDate))[0]||null;}
export function calibrationStatus(eq,data,at=DEMO_NOW){if(!eq.calibrationRequired)return {label:'Not required',tone:'grey',days:null,calibration:null};const c=calibrationAt(data,eq.id,at);if(!c)return {label:'Missing',tone:'red',days:null,calibration:null};const days=Math.ceil((new Date(c.dueDate)-new Date(at))/86400000);if(days<0)return {label:'Expired',tone:'red',days,calibration:c};const thresholds=(data.settings?.calibrationWarningDays||[60,30,14,7]).filter(Number.isFinite);const urgent=Math.min(...thresholds,7),warn=Math.max(...thresholds,60);if(days<=urgent)return {label:`Due ${days}d`,tone:'red',days,calibration:c};if(days<=warn)return {label:`Due ${days}d`,tone:'amber',days,calibration:c};return {label:'Valid',tone:'green',days,calibration:c};}

export function recomputeRequirementStatuses(data){
 for(const r of data.requirements){
  const legs=data.legs.filter(l=>r.testLegIds?.includes(l.id)||l.requirementIds?.includes(r.id));
  if(!legs.length){r.status='Not Covered';continue;}
  if(legs.some(l=>l.blockingReason)){r.status='Blocked';continue;}
  const res=data.results.filter(x=>legs.some(l=>l.id===x.legId));
  if(res.some(x=>x.status==='FAIL')){r.status='Failed';continue;}
  const completed=legs.filter(l=>l.status==='Completed');
  if(completed.length===legs.length&&res.length){r.status='Verified';continue;}
  if(completed.length>0){r.status='Partially Verified';continue;}
  if(legs.some(l=>l.status==='In Progress')){r.status='In Progress';continue;}
  r.status='Planned';
 }
 return data;
}

export function kpis(data){
 const req=data.requirements,total=req.length,covered=req.filter(r=>r.status!=='Not Covered').length,verified=req.filter(r=>r.status==='Verified').length,failed=req.filter(r=>r.status==='Failed').length,criticalOutstanding=req.filter(r=>r.criticality==='Critical'&&!['Verified'].includes(r.status)).length;
 const testsOpen=data.legs.filter(l=>!['Completed','Cancelled'].includes(l.status)).length,inProgress=data.legs.filter(l=>l.status==='In Progress').length,overdue=data.legs.filter(l=>l.plannedEnd&&new Date(l.plannedEnd)>new Date(l.dueDate)).length;
 const completed=data.legs.filter(l=>l.actualStart&&l.actualEnd),turn=completed.map(l=>(new Date(l.actualEnd)-new Date(l.actualStart))/3600000),avg=turn.length?turn.reduce((a,b)=>a+b,0)/turn.length:0;const median=turn.length?[...turn].sort((a,b)=>a-b)[Math.floor(turn.length/2)]:0;
 const onTime=data.programmes.filter(p=>p.forecastCompletion&&new Date(p.forecastCompletion)<=new Date(p.dueDate)).length;
 const util=resourceUtilisation(data);
 const devOpen=data.devTasks.filter(d=>!d.completeDate&&d.status!=='Complete');
 return {activeProgrammes:data.programmes.filter(p=>p.status!=='Closed').length,testsOpen,inProgress,overdue,atRisk:data.programmes.filter(p=>['At Risk','Late','Blocked'].includes(p.scheduleRisk)).length,
  reqCoverage:Math.round(covered/total*100),reqVerified:Math.round(verified/total*100),reqFailed:failed,reqUncovered:total-covered,criticalOutstanding,
  onTimePct:Math.round(onTime/Math.max(1,data.programmes.length)*100),avgTurnaround:Math.round(avg*10)/10,medianTurnaround:Math.round(median*10)/10,
  equipmentUtil:util.equipmentAvg,staffUtil:util.staffAvg,devHours:devOpen.reduce((s,d)=>s+d.estimatedEngineeringHours+d.estimatedTechnicianHours,0),devQueue:devOpen.length};
}

export function resourceUtilisation(data,days=28){const start=DEMO_NOW,end=new Date(DEMO_NOW.getTime()+days*86400000);const totalHours=days*24;
 const eqs=data.equipment.map(e=>{const h=data.bookings.filter(b=>b.equipmentId===e.id&&overlap(b.start,b.end,start,end)).reduce((s,b)=>s+(Math.min(new Date(b.end),end)-Math.max(new Date(b.start),start))/3600000,0);return {id:e.id,name:e.name,type:e.type,hours:Math.max(0,h),pct:Math.min(100,Math.round(Math.max(0,h)/totalHours*100))};});
 const staff=data.staff.map(s=>{const h=data.bookings.filter(b=>b.staffId===s.id&&overlap(b.start,b.staffEnd||b.end,start,end)).reduce((x,b)=>x+(Math.min(new Date(b.staffEnd||b.end),end)-Math.max(new Date(b.start),start))/3600000,0);const avail=days/7*5*8;return {id:s.id,name:s.name,hours:Math.max(0,h),pct:Math.min(100,Math.round(Math.max(0,h)/Math.max(1,avail)*100))};});
 return {equipment:eqs,staff,equipmentAvg:Math.round(eqs.reduce((s,x)=>s+x.pct,0)/Math.max(1,eqs.length)),staffAvg:Math.round(staff.reduce((s,x)=>s+x.pct,0)/Math.max(1,staff.length))};}

export function categoryMetrics(data){return [...new Set(data.methods.map(m=>m.category))].map(cat=>{const mids=new Set(data.methods.filter(m=>m.category===cat).map(m=>m.id));const legs=data.legs.filter(l=>mids.has(l.methodId));const open=legs.filter(l=>l.status!=='Completed').length,late=legs.filter(l=>l.plannedEnd&&new Date(l.plannedEnd)>new Date(l.dueDate)).length;const hours=legs.filter(l=>l.plannedStart).reduce((s,l)=>{const m=data.methods.find(x=>x.id===l.methodId);return s+(m?m.executionHours+m.setupHours+m.teardownHours+m.analysisHours:0)},0);return {category:cat,open,late,upcomingHours:Math.round(hours),utilisation:Math.min(100,Math.round(hours/(28*24)*100))};}).sort((a,b)=>b.upcomingHours-a.upcomingHours);}

export function bottlenecks(data){
 const counts={}; const add=(k,v=1)=>counts[k]=(counts[k]||0)+v;
 for(const l of data.legs){const txt=(l.blockingReason||'')+' '+(l.planExplanation||[]).join(' ');if(/calibration/i.test(txt))add('Calibration');if(/occupied|capacity|booked/i.test(txt))add('Equipment capacity');if(/breakdown|maintenance|unavailable: /i.test(txt))add('Equipment unavailable');if(/missing qualification|no independently qualified|lacks the required method|qualification bottleneck|only one .*qualified/i.test(txt))add('Qualification');if(/staff.*unavailable|another booking/i.test(txt))add('Staff availability');if(/development/i.test(txt))add('Test development');if(/predecessor/i.test(txt))add('Predecessor dependency');}
 const util=resourceUtilisation(data,14);for(const e of util.equipment.filter(x=>x.pct>=70))add(`${e.type} capacity`,Math.ceil(e.pct/20));
 const dev=data.devTasks.filter(d=>!d.completeDate&&d.status!=='Complete').length;if(dev)add('Test Development Engineering',dev);
 const singlePoint=data.methods.filter(m=>data.staff.filter(s=>s.qualifications.some(q=>q.methodId===m.id&&['Independent','Reviewer','Trainer/Expert'].includes(q.level))).length===1);if(singlePoint.length)add('Single-point competency',singlePoint.length);
 return Object.entries(counts).map(([name,score])=>({name,score,detail:bottleneckDetail(name,data,score)})).sort((a,b)=>b.score-a.score).slice(0,8);
}
function bottleneckDetail(name,data,score){if(name.includes('Development'))return `${data.devTasks.filter(d=>!d.completeDate).length} method-development items open; engineering effort is on the critical path.`;if(name.includes('Calibration'))return `${data.equipment.filter(e=>calibrationStatus(e,data).tone==='red').length} assets expired/due within 7 days; planned tests may be blocked.`;if(name.includes('Single-point'))return `${score} test methods rely on a single independently qualified person.`;if(name.includes('capacity'))return `High scheduled utilisation or unmet demand is constraining throughput.`;if(name.includes('Qualification'))return `Required authorisations narrow the set of feasible staff assignments.`;return `${score} current/forecast constraints detected from planned work.`;}

export function skillsRisks(data){const rows=data.methods.map(m=>{const people=data.staff.filter(s=>s.qualifications.some(q=>q.methodId===m.id&&['Independent','Reviewer','Trainer/Expert'].includes(q.level)&&new Date(q.expires)>DEMO_NOW));return {methodId:m.id,name:m.name,count:people.length,people:people.map(x=>x.name).join(', ')}});return rows.filter(r=>r.count<=1).sort((a,b)=>a.count-b.count);}

export function runDiagnostics(data){const checks=[];const push=(name,ok,detail)=>checks.push({name,ok,detail});
 const ids={programmes:new Set(data.programmes.map(x=>x.id)),methods:new Set(data.methods.map(x=>x.id)),legs:new Set(data.legs.map(x=>x.id)),equipment:new Set(data.equipment.map(x=>x.id)),staff:new Set(data.staff.map(x=>x.id)),duts:new Set(data.duts.map(x=>x.id))};
 const orphanLegs=data.legs.filter(l=>!ids.programmes.has(l.programmeId)||!ids.methods.has(l.methodId)||l.dutIds.some(d=>!ids.duts.has(d)));push('Orphaned record references',orphanLegs.length===0,orphanLegs.length?`${orphanLegs.length} invalid leg references`:'All canonical references resolve');
 let eqOver=0,stOver=0;for(let i=0;i<data.bookings.length;i++)for(let j=i+1;j<data.bookings.length;j++){const a=data.bookings[i],b=data.bookings[j];if(a.equipmentId===b.equipmentId&&overlap(a.start,a.end,b.start,b.end))eqOver++;if(a.staffId===b.staffId&&overlap(a.start,a.staffEnd||a.end,b.start,b.staffEnd||b.end))stOver++;}push('Equipment booking overlaps',eqOver===0,eqOver?`${eqOver} overlaps detected`:'No prohibited double bookings');push('Staff booking overlaps',stOver===0,stOver?`${stOver} overlaps detected`:'No prohibited double bookings');
 const invalidCal=data.bookings.filter(b=>{const e=data.equipment.find(x=>x.id===b.equipmentId);if(!e||!e.calibrationRequired)return false;const c=calibrationAt(data,e.id,b.start,{allowScheduled:true});return !c||new Date(c.dueDate)<new Date(b.end);});push('Calibration validity in future plan',invalidCal.length===0,invalidCal.length?`${invalidCal.length} bookings extend beyond calibration validity at their effective use date`:'All scheduled calibrated assets remain valid through use, including planned recalibrations');
 const unqual=data.bookings.filter(b=>{const l=data.legs.find(x=>x.id===b.legId),s=data.staff.find(x=>x.id===b.staffId),m=data.methods.find(x=>x.id===l?.methodId);return !l||!s||!m||!(s.equipmentQualifications||[]).includes(m.equipmentType)||!s.qualifications.some(q=>q.methodId===l.methodId&&['Independent','Reviewer','Trainer/Expert'].includes(q.level)&&new Date(q.expires)>new Date(b.start));});push('Qualified staff allocations',unqual.length===0,unqual.length?`${unqual.length} unqualified allocations`:'Every planned operator is independently qualified');
 const crit=data.requirements.filter(r=>r.criticality==='Critical'&&r.status==='Not Covered');push('Critical requirement coverage',crit.length===0,crit.length?`${crit.length} critical requirements uncovered`:'All critical requirements have test coverage');
 const missingDur=data.methods.filter(m=>![m.executionHours,m.setupHours,m.teardownHours].every(Number.isFinite));push('Test-library durations',missingDur.length===0,missingDur.length?`${missingDur.length} methods missing duration data`:'All active methods have deterministic planning durations');
 const depCycles=detectCycles(data.legs);push('Dependency graph',depCycles.length===0,depCycles.length?`Cycle detected: ${depCycles[0].join(' -> ')}`:'No impossible dependency cycles');
 const pf=data.results.filter(r=>r.resultType==='numeric'&&(((r.lowerLimit!=null&&r.value<r.lowerLimit)||(r.upperLimit!=null&&r.value>r.upperLimit))?r.status!=='FAIL':r.status!=='PASS'));push('Deterministic result evaluation',pf.length===0,pf.length?`${pf.length} numeric result status mismatches`:'Numeric pass/fail agrees with limits');
 const counts={programmes:data.programmes.length,requirements:data.requirements.length,legs:data.legs.length,duts:data.duts.length,methods:data.methods.length,equipment:data.equipment.length,staff:data.staff.length,calibrations:data.calibrations.length};push('Demo dataset scale',counts.programmes>=8&&counts.requirements>=50&&counts.legs>=40&&counts.duts>=80&&counts.methods>=25&&counts.equipment>=20&&counts.staff>=12&&counts.calibrations>=30,JSON.stringify(counts));
 const specBad=(data.specifications||[]).filter(sp=>!ids.programmes.has(sp.programmeId)||(sp.linkedRequirementIds||[]).some(id=>!data.requirements.some(r=>r.id===id))||(sp.linkedMethodIds||[]).some(id=>!ids.methods.has(id)));push('Specification traceability',specBad.length===0,specBad.length?`${specBad.length} specification links are invalid`:`${(data.specifications||[]).length} specifications link cleanly to programmes, requirements and methods`);
 const badDisrupt=(data.disruptions||[]).filter(d=>d.programmeId&&!ids.programmes.has(d.programmeId)||d.legId&&!ids.legs.has(d.legId)||d.effectiveUntil&&new Date(d.effectiveUntil)<new Date(d.reportedAt));push('Operational disruption inputs',badDisrupt.length===0,badDisrupt.length?`${badDisrupt.length} invalid disruption records`:`${(data.disruptions||[]).filter(d=>d.status==='Active').length} active delay/issue constraints are structurally valid`);
 const roots=new Set(['Bad Specification','Test Execution','Sample / DUT','Equipment / Facility','Planning / Resource','Test Method / Development']);const badIssues=(data.issues||[]).filter(i=>!ids.programmes.has(i.programmeId)||!roots.has(i.rootCause));push('Lessons-learned issue classification',badIssues.length===0,badIssues.length?`${badIssues.length} issues have invalid programme/root-cause classification`:`${(data.issues||[]).length} issues are classified for automatic lessons learned`);
 push('Period KPI history',(data.testRuns||[]).length>=50,`${(data.testRuns||[]).length} canonical test-run records available for week/month/custom-period analytics`);
 ensureCostFramework(data);const costBad=(data.legs||[]).filter(l=>{const c=estimateLegCost(data,l);return !Number.isFinite(c.total)||c.total<0||['labour','equipment','consumables','external','development','overhead','contingency'].some(k=>!Number.isFinite(c[k])||c[k]<0)});push('Test cost framework',costBad.length===0,costBad.length?`${costBad.length} legs have invalid cost components`:`${data.legs.length} test legs have deterministic non-negative cost breakdowns`);
 const port=portfolioCost(data);push('Programme cost roll-up',Number.isFinite(port.totalForecast)&&port.totalForecast>=0&&port.programmes.length===data.programmes.length,`${port.programmes.length} programmes roll up to forecast ${Math.round(port.totalForecast)}`);
 const samplePlanBad=(data.legs||[]).filter(l=>l.status!=='Completed'&&l.plannedStart&&l.sampleReadyDate&&new Date(l.plannedStart)<new Date(l.sampleReadyDate));push('Sample-ready planning constraint',samplePlanBad.length===0,samplePlanBad.length?`${samplePlanBad.length} planned legs start before samples are ready`:'Every planned leg respects its sample-ready input');
 const unreleasedScheduled=(data.legs||[]).filter(l=>l.plannedStart&&((data.programmes.find(p=>p.id===l.programmeId)?.gateStatus||'Released')!=='Released'||((data.specifications||[]).some(s=>s.programmeId===l.programmeId)&&!(data.specifications||[]).some(s=>s.programmeId===l.programmeId&&s.status==='Released'))));push('Programme/specification release gates',unreleasedScheduled.length===0,unreleasedScheduled.length?`${unreleasedScheduled.length} unreleased legs consume future capacity`:'Unreleased programmes/specifications do not consume committed future capacity');
 const pass=checks.filter(c=>c.ok).length;return {checks,pass,fail:checks.length-pass,overall:pass===checks.length?'PASS':'FAIL'};}
function detectCycles(legs){const graph=Object.fromEntries(legs.map(l=>[l.id,l.predecessorIds||[]]));const state={},path=[];function dfs(n){if(state[n]===1)return [...path,n];if(state[n]===2)return null;state[n]=1;path.push(n);for(const p of graph[n]||[]){const r=dfs(p);if(r)return r;}path.pop();state[n]=2;return null;}for(const n of Object.keys(graph)){const r=dfs(n);if(r)return [r];}return [];}

function periodBounds(start,end){const s=new Date(start||DEMO_NOW),e=new Date(end||DEMO_NOW);if(/^\d{4}-\d{2}-\d{2}$/.test(String(start||'')))s.setUTCHours(0,0,0,0);if(/^\d{4}-\d{2}-\d{2}$/.test(String(end||'')))e.setUTCHours(23,59,59,999);return s<=e?[s,e]:[e,s];}
function inPeriod(x,start,end){if(!x)return false;const d=new Date(x);return d>=start&&d<=end;}
function overlapHours(a,b,start,end){if(!a||!b)return 0;const s=Math.max(new Date(a).getTime(),start.getTime()),e=Math.min(new Date(b).getTime(),end.getTime());return Math.max(0,(e-s)/3600000);}
function medianOf(vals){if(!vals.length)return 0;const a=[...vals].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}

export function periodMetrics(data,start,end){
 const [s,e]=periodBounds(start,end);const runs=(data.testRuns||[]).filter(r=>inPeriod(r.actualEnd,s,e));const issues=(data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e));const futureBookings=(data.bookings||[]).filter(b=>new Date(b.start)>=DEMO_NOW&&overlap(b.start,b.end,s,e));
 const completed=runs.length,pass=runs.filter(r=>r.outcome==='PASS').length,rework=runs.filter(r=>r.outcome==='REWORK').length,failed=runs.filter(r=>r.outcome==='FAIL').length;
 const onTime=runs.filter(r=>r.plannedEnd&&new Date(r.actualEnd)<=new Date(r.plannedEnd)).length;const actualHours=runs.reduce((a,r)=>a+(Number(r.actualHours)||0),0),standardHours=runs.reduce((a,r)=>a+(Number(r.standardHours)||0),0),turn=runs.map(r=>Number(r.actualHours)||0).filter(Number.isFinite);
 const specIssues=issues.filter(i=>i.rootCause==='Bad Specification').length,execIssues=issues.filter(i=>i.rootCause==='Test Execution').length,delayHours=issues.reduce((a,i)=>a+(Number(i.delayHours)||0),0);
 const eqRows=(data.equipment||[]).map(eq=>{const hist=runs.filter(r=>r.equipmentId===eq.id).reduce((a,r)=>a+(Number(r.actualHours)||0),0);const fut=futureBookings.filter(b=>b.equipmentId===eq.id).reduce((a,b)=>a+overlapHours(b.start,b.end,s,e),0);const days=Math.max(1,(e-s)/86400000+1),avail=days*24;return{id:eq.id,name:eq.name,type:eq.type,hours:hist+fut,pct:Math.min(100,Math.round((hist+fut)/avail*100))};});
 const staffRows=(data.staff||[]).map(st=>{const hist=runs.filter(r=>r.staffId===st.id).reduce((a,r)=>{const m=data.methods.find(x=>x.id===r.methodId);return a+(m?.continuousStaffing?Number(r.actualHours)||0:(m?.setupHours||0)+(m?.teardownHours||0)+(m?.analysisHours||0))},0);const fut=futureBookings.filter(b=>b.staffId===st.id).reduce((a,b)=>a+overlapHours(b.start,b.staffEnd||b.end,s,e),0);const days=Math.max(1,(e-s)/86400000+1),avail=days/7*5*8;return{id:st.id,name:st.name,hours:hist+fut,pct:Math.min(100,Math.round((hist+fut)/Math.max(1,avail)*100))};});
 const reqEvidence=new Set();for(const r of runs){const leg=data.legs.find(l=>l.id===r.legId);for(const id of leg?.requirementIds||[])reqEvidence.add(id);}
 return {start:s.toISOString(),end:e.toISOString(),completed,pass,failed,rework,passRate:Math.round(pass/Math.max(1,completed)*100),onTimePct:Math.round(onTime/Math.max(1,completed)*100),avgTurnaround:Math.round((turn.reduce((a,b)=>a+b,0)/Math.max(1,turn.length))*10)/10,medianTurnaround:Math.round(medianOf(turn)*10)/10,actualHours:Math.round(actualHours),standardHours:Math.round(standardHours),durationVariancePct:Math.round((actualHours-standardHours)/Math.max(1,standardHours)*100),issues:issues.length,specIssues,execIssues,specIssuePct:Math.round(specIssues/Math.max(1,issues.length)*100),execIssuePct:Math.round(execIssues/Math.max(1,issues.length)*100),issueDelayHours:Math.round(delayHours),requirementEvidence:reqEvidence.size,equipmentUtil:Math.round(eqRows.reduce((a,x)=>a+x.pct,0)/Math.max(1,eqRows.length)),staffUtil:Math.round(staffRows.reduce((a,x)=>a+x.pct,0)/Math.max(1,staffRows.length)),equipment:eqRows,staff:staffRows,runs,periodIssues:issues};
}

function bucketStart(date,mode){const d=new Date(date);d.setUTCHours(0,0,0,0);if(mode==='week'){const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);}else if(mode==='month')d.setUTCDate(1);return d;}
function bucketKey(date,mode){const d=bucketStart(date,mode);return d.toISOString().slice(0,10);}
export function periodTrend(data,start,end){const [s,e]=periodBounds(start,end),days=Math.max(1,Math.ceil((e-s)/86400000));const mode=days<=35?'day':days<=140?'week':'month';const rows=new Map();let d=bucketStart(s,mode);while(d<=e){const key=d.toISOString().slice(0,10);rows.set(key,{key,date:key,completed:0,pass:0,fail:0,issues:0,delayHours:0});if(mode==='day')d=new Date(d.getTime()+86400000);else if(mode==='week')d=new Date(d.getTime()+7*86400000);else{d=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1));}}
 for(const r of (data.testRuns||[]).filter(r=>inPeriod(r.actualEnd,s,e))){const x=rows.get(bucketKey(r.actualEnd,mode));if(x){x.completed++;if(r.outcome==='PASS')x.pass++;if(r.outcome==='FAIL')x.fail++;}}
 for(const i of (data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e))){const x=rows.get(bucketKey(i.reportedAt,mode));if(x){x.issues++;x.delayHours+=Number(i.delayHours)||0;}}
 return {mode,rows:[...rows.values()]};
}

export function issueAnalytics(data,start,end){const [s,e]=periodBounds(start,end),issues=(data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e));const group=(key)=>{const m={};for(const i of issues){const k=i[key]||'Unclassified';m[k]=m[k]||{name:k,count:0,delayHours:0,severe:0,lesson:i.lesson||''};m[k].count++;m[k].delayHours+=Number(i.delayHours)||0;if(i.severity==='High')m[k].severe++;if(!m[k].lesson&&i.lesson)m[k].lesson=i.lesson;}return Object.values(m).sort((a,b)=>b.count-a.count||b.delayHours-a.delayHours)};const topTypes=group('issueType'),rootCauses=group('rootCause');const total=issues.length;
 const lessons=topTypes.slice(0,6).map((x,idx)=>({rank:idx+1,issue:x.name,occurrences:x.count,share:Math.round(x.count/Math.max(1,total)*100),delayHours:Math.round(x.delayHours),priority:x.count>=Math.max(3,total*.18)||x.delayHours>=48?'High':x.count>=2?'Medium':'Low',lesson:x.lesson||`Review recurring ${x.name.toLowerCase()} and standardise preventive controls.`}));
 return {issues,total,topTypes,rootCauses,lessons,testExecution:issues.filter(i=>i.rootCause==='Test Execution').length,badSpecification:issues.filter(i=>i.rootCause==='Bad Specification').length};
}
