import { DEMO_NOW } from './data.js';
import { ensureCostFramework, estimateLegCost, portfolioCost } from './costs.js';
import { ensureOperationsState, capacityForecast, maintenanceSummary, AUDIT_STANDARDS, auditScore } from './operations.js';
import { ensureTimeLearningState, efficiencyMetrics, operationalRecommendations, serviceSynergy } from './intelligence.js';
import { ensureLiveState } from './live.js';
import { ensureWorkflowState, detectRecurringLessons, escalationSummary } from './workflow.js';
import { ensureAdvancedState, digitalTwinForecast, predictiveAssetSummary, programmeSimilarity } from './advanced.js';
import { ensurePrototypeState } from './prototypes.js';

function overlap(a,b,c,d){return new Date(a)<new Date(d)&&new Date(b)>new Date(c);}
export function calibrationAt(data,eqId,at=DEMO_NOW,{allowScheduled=false}={}){const when=new Date(at);return data.calibrations.filter(c=>c.equipmentId===eqId&&new Date(c.calibrationDate)<=when&&(allowScheduled||c.result!=='Scheduled')).sort((a,b)=>new Date(b.calibrationDate)-new Date(a.calibrationDate))[0]||null;}
export function nextScheduledCalibration(data,eqId,at=DEMO_NOW){const when=new Date(at);return data.calibrations.filter(c=>c.equipmentId===eqId&&c.result==='Scheduled'&&new Date(c.calibrationDate)>when).sort((a,b)=>new Date(a.calibrationDate)-new Date(b.calibrationDate))[0]||null;}
export function calibrationStatus(eq,data,at=DEMO_NOW){if(!eq.calibrationRequired)return {label:'Not required',tone:'grey',days:null,calibration:null};const c=calibrationAt(data,eq.id,at);if(!c)return {label:'Missing',tone:'red',days:null,calibration:null};const days=Math.ceil((new Date(c.dueDate)-new Date(at))/86400000);if(days<0)return {label:'Expired',tone:'red',days,calibration:c};const thresholds=(data.settings?.calibrationWarningDays||[60,30,14,7]).filter(Number.isFinite);const urgent=Math.min(...thresholds,7),warn=Math.max(...thresholds,60);if(days<=urgent)return {label:`Due ${days}d`,tone:'red',days,calibration:c};if(days<=warn)return {label:`Due ${days}d`,tone:'amber',days,calibration:c};return {label:'Valid',tone:'green',days,calibration:c};}

export function recomputeRequirementStatuses(data){
 for(const r of data.requirements){
  const legs=data.legs.filter(l=>r.testLegIds?.includes(l.id)||l.requirementIds?.includes(r.id));
  if(!legs.length){r.status='Not Covered';continue;}
  if(legs.some(l=>l.blockingReason)){r.status='Blocked';continue;}
  const res=data.results.filter(x=>legs.some(l=>l.id===x.legId));
  if(res.some(x=>x.status==='FAIL')){r.status='Failed';continue;}
  const completed=legs.filter(l=>l.status==='Completed');
  if(completed.length===legs.length&&res.length){r.status='Verified';continue;}
  if(completed.length>0){r.status='Partially Verified';continue;}
  if(legs.some(l=>l.status==='In Progress')){r.status='In Progress';continue;}
  r.status='Planned';
 }
 return data;
}

export function kpis(data){
 const req=data.requirements,total=req.length,covered=req.filter(r=>r.status!=='Not Covered').length,verified=req.filter(r=>r.status==='Verified').length,failed=req.filter(r=>r.status==='Failed').length,criticalOutstanding=req.filter(r=>r.criticality==='Critical'&&!['Verified'].includes(r.status)).length;
 const testsOpen=data.legs.filter(l=>!['Completed','Cancelled'].includes(l.status)).length,inProgress=data.legs.filter(l=>l.status==='In Progress').length,overdue=data.legs.filter(l=>l.plannedEnd&&new Date(l.plannedEnd)>new Date(l.dueDate)).length;
 const completed=data.legs.filter(l=>l.actualStart&&l.actualEnd),turn=completed.map(l=>(new Date(l.actualEnd)-new Date(l.actualStart))/3600000),avg=turn.length?turn.reduce((a,b)=>a+b,0)/turn.length:0;const median=turn.length?[...turn].sort((a,b)=>a-b)[Math.floor(turn.length/2)]:0;
 const onTime=data.programmes.filter(p=>p.forecastCompletion&&new Date(p.forecastCompletion)<=new Date(p.dueDate)).length;
 const util=resourceUtilisation(data);
 const devOpen=data.devTasks.filter(d=>!d.completeDate&&d.status!=='Complete');
 return {activeProgrammes:data.programmes.filter(p=>p.status!=='Closed').length,testsOpen,inProgress,overdue,atRisk:data.programmes.filter(p=>['At Risk','Late','Blocked'].includes(p.scheduleRisk)).length,
  reqCoverage:Math.round(covered/total*100),reqVerified:Math.round(verified/total*100),reqFailed:failed,reqUncovered:total-covered,criticalOutstanding,
  onTimePct:Math.round(onTime/Math.max(1,data.programmes.length)*100),avgTurnaround:Math.round(avg*10)/10,medianTurnaround:Math.round(median*10)/10,
  equipmentUtil:util.equipmentAvg,staffUtil:util.staffAvg,devHours:devOpen.reduce((s,d)=>s+d.estimatedEngineeringHours+d.estimatedTechnicianHours,0),devQueue:devOpen.length};
}

export function resourceUtilisation(data,days=28){const start=DEMO_NOW,end=new Date(DEMO_NOW.getTime()+days*86400000);const totalHours=days*24;
 const eqs=data.equipment.map(e=>{const h=data.bookings.filter(b=>b.equipmentId===e.id&&overlap(b.start,b.end,start,end)).reduce((s,b)=>s+(Math.min(new Date(b.end),end)-Math.max(new Date(b.start),start))/3600000,0);return {id:e.id,name:e.name,type:e.type,hours:Math.max(0,h),pct:Math.min(100,Math.round(Math.max(0,h)/totalHours*100))};});
 const staff=data.staff.map(s=>{const h=data.bookings.filter(b=>b.staffId===s.id&&overlap(b.start,b.staffEnd||b.end,start,end)).reduce((x,b)=>x+(Math.min(new Date(b.staffEnd||b.end),end)-Math.max(new Date(b.start),start))/3600000,0);const avail=days/7*5*8;return {id:s.id,name:s.name,hours:Math.max(0,h),pct:Math.min(100,Math.round(Math.max(0,h)/Math.max(1,avail)*100))};});
 return {equipment:eqs,staff,equipmentAvg:Math.round(eqs.reduce((s,x)=>s+x.pct,0)/Math.max(1,eqs.length)),staffAvg:Math.round(staff.reduce((s,x)=>s+x.pct,0)/Math.max(1,staff.length))};}

export function categoryMetrics(data){return [...new Set(data.methods.map(m=>m.category))].map(cat=>{const mids=new Set(data.methods.filter(m=>m.category===cat).map(m=>m.id));const legs=data.legs.filter(l=>mids.has(l.methodId));const open=legs.filter(l=>l.status!=='Completed').length,late=legs.filter(l=>l.plannedEnd&&new Date(l.plannedEnd)>new Date(l.dueDate)).length;const hours=legs.filter(l=>l.plannedStart).reduce((s,l)=>{const m=data.methods.find(x=>x.id===l.methodId);return s+(m?m.executionHours+m.setupHours+m.teardownHours+m.analysisHours:0)},0);return {category:cat,open,late,upcomingHours:Math.round(hours),utilisation:Math.min(100,Math.round(hours/(28*24)*100))};}).sort((a,b)=>b.upcomingHours-a.upcomingHours);}

export function bottlenecks(data){
 const counts={}; const add=(k,v=1)=>counts[k]=(counts[k]||0)+v;
 for(const l of data.legs){const txt=(l.blockingReason||'')+' '+(l.planExplanation||[]).join(' ');if(/calibration/i.test(txt))add('Calibration');if(/occupied|capacity|booked/i.test(txt))add('Equipment capacity');if(/breakdown|maintenance|unavailable: /i.test(txt))add('Equipment unavailable');if(/missing qualification|no independently qualified|lacks the required method|qualification bottleneck|only one .*qualified/i.test(txt))add('Qualification');if(/staff.*unavailable|another booking/i.test(txt))add('Staff availability');if(/development/i.test(txt))add('Test development');if(/predecessor/i.test(txt))add('Predecessor dependency');}
 const util=resourceUtilisation(data,14);for(const e of util.equipment.filter(x=>x.pct>=70))add(`${e.type} capacity`,Math.ceil(e.pct/20));
 const dev=data.devTasks.filter(d=>!d.completeDate&&d.status!=='Complete').length;if(dev)add('Test Development Engineering',dev);
 const singlePoint=data.methods.filter(m=>data.staff.filter(s=>s.qualifications.some(q=>q.methodId===m.id&&['Independent','Reviewer','Trainer/Expert'].includes(q.level))).length===1);if(singlePoint.length)add('Single-point competency',singlePoint.length);
 return Object.entries(counts).map(([name,score])=>({name,score,detail:bottleneckDetail(name,data,score)})).sort((a,b)=>b.score-a.score).slice(0,8);
}
function bottleneckDetail(name,data,score){if(name.includes('Development'))return `${data.devTasks.filter(d=>!d.completeDate).length} method-development items open; engineering effort is on the critical path.`;if(name.includes('Calibration'))return `${data.equipment.filter(e=>calibrationStatus(e,data).tone==='red').length} assets expired/due within 7 days; planned tests may be blocked.`;if(name.includes('Single-point'))return `${score} test methods rely on a single independently qualified person.`;if(name.includes('capacity'))return `High scheduled utilisation or unmet demand is constraining throughput.`;if(name.includes('Qualification'))return `Required authorisations narrow the set of feasible staff assignments.`;return `${score} current/forecast constraints detected from planned work.`;}

export function skillsRisks(data){const rows=data.methods.map(m=>{const people=data.staff.filter(s=>s.qualifications.some(q=>q.methodId===m.id&&['Independent','Reviewer','Trainer/Expert'].includes(q.level)&&new Date(q.expires)>DEMO_NOW));return {methodId:m.id,name:m.name,count:people.length,people:people.map(x=>x.name).join(', ')}});return rows.filter(r=>r.count<=1).sort((a,b)=>a.count-b.count);}

export function runDiagnostics(data){ensureAdvancedState(data);ensurePrototypeState(data);ensureOperationsState(data);ensureTimeLearningState(data);ensureLiveState(data);ensureWorkflowState(data);detectRecurringLessons(data);const checks=[];const push=(name,ok,detail)=>checks.push({name,ok,detail});
 const ids={programmes:new Set(data.programmes.map(x=>x.id)),methods:new Set(data.methods.map(x=>x.id)),legs:new Set(data.legs.map(x=>x.id)),equipment:new Set(data.equipment.map(x=>x.id)),staff:new Set(data.staff.map(x=>x.id)),duts:new Set(data.duts.map(x=>x.id))};
 const orphanLegs=data.legs.filter(l=>!ids.programmes.has(l.programmeId)||!ids.methods.has(l.methodId)||l.dutIds.some(d=>!ids.duts.has(d)));push('Orphaned record references',orphanLegs.length===0,orphanLegs.length?`${orphanLegs.length} invalid leg references`:'All canonical references resolve');
 let eqOver=0,stOver=0;for(let i=0;i<data.bookings.length;i++)for(let j=i+1;j<data.bookings.length;j++){const a=data.bookings[i],b=data.bookings[j];if(a.equipmentId===b.equipmentId&&overlap(a.start,a.end,b.start,b.end))eqOver++;if(a.staffId===b.staffId&&overlap(a.start,a.staffEnd||a.end,b.start,b.staffEnd||b.end))stOver++;}push('Equipment booking overlaps',eqOver===0,eqOver?`${eqOver} overlaps detected`:'No prohibited double bookings');push('Staff booking overlaps',stOver===0,stOver?`${stOver} overlaps detected`:'No prohibited double bookings');
 const invalidCal=data.bookings.filter(b=>{const e=data.equipment.find(x=>x.id===b.equipmentId);if(!e||!e.calibrationRequired)return false;const c=calibrationAt(data,e.id,b.start,{allowScheduled:true});return !c||new Date(c.dueDate)<new Date(b.end);});push('Calibration validity in future plan',invalidCal.length===0,invalidCal.length?`${invalidCal.length} bookings extend beyond calibration validity at their effective use date`:'All scheduled calibrated assets remain valid through use, including planned recalibrations');
 const unqual=data.bookings.filter(b=>{const l=data.legs.find(x=>x.id===b.legId),s=data.staff.find(x=>x.id===b.staffId),m=data.methods.find(x=>x.id===l?.methodId);return !l||!s||!m||!(s.equipmentQualifications||[]).includes(m.equipmentType)||!s.qualifications.some(q=>q.methodId===l.methodId&&['Independent','Reviewer','Trainer/Expert'].includes(q.level)&&new Date(q.expires)>new Date(b.start));});push('Qualified staff allocations',unqual.length===0,unqual.length?`${unqual.length} unqualified allocations`:'Every planned operator is independently qualified');
 const crit=data.requirements.filter(r=>r.criticality==='Critical'&&r.status==='Not Covered');push('Critical requirement coverage',crit.length===0,crit.length?`${crit.length} critical requirements uncovered`:'All critical requirements have test coverage');
 const missingDur=data.methods.filter(m=>![m.executionHours,m.setupHours,m.teardownHours].every(Number.isFinite));push('Test-library durations',missingDur.length===0,missingDur.length?`${missingDur.length} methods missing duration data`:'All active methods have deterministic planning durations');
 const depCycles=detectCycles(data.legs);push('Dependency graph',depCycles.length===0,depCycles.length?`Cycle detected: ${depCycles[0].join(' -> ')}`:'No impossible dependency cycles');
 const pf=data.results.filter(r=>r.resultType==='numeric'&&(((r.lowerLimit!=null&&r.value<r.lowerLimit)||(r.upperLimit!=null&&r.value>r.upperLimit))?r.status!=='FAIL':r.status!=='PASS'));push('Deterministic result evaluation',pf.length===0,pf.length?`${pf.length} numeric result status mismatches`:'Numeric pass/fail agrees with limits');
 const counts={programmes:data.programmes.length,requirements:data.requirements.length,legs:data.legs.length,duts:data.duts.length,methods:data.methods.length,equipment:data.equipment.length,staff:data.staff.length,calibrations:data.calibrations.length};push('Demo dataset scale',counts.programmes>=8&&counts.requirements>=50&&counts.legs>=40&&counts.duts>=80&&counts.methods>=25&&counts.equipment>=20&&counts.staff>=12&&counts.calibrations>=30,JSON.stringify(counts));
 const specBad=(data.specifications||[]).filter(sp=>!ids.programmes.has(sp.programmeId)||(sp.linkedRequirementIds||[]).some(id=>!data.requirements.some(r=>r.id===id))||(sp.linkedMethodIds||[]).some(id=>!ids.methods.has(id)));push('Specification traceability',specBad.length===0,specBad.length?`${specBad.length} specification links are invalid`:`${(data.specifications||[]).length} specifications link cleanly to programmes, requirements and methods`);
 const badDisrupt=(data.disruptions||[]).filter(d=>d.programmeId&&!ids.programmes.has(d.programmeId)||d.legId&&!ids.legs.has(d.legId)||d.effectiveUntil&&new Date(d.effectiveUntil)<new Date(d.reportedAt));push('Operational disruption inputs',badDisrupt.length===0,badDisrupt.length?`${badDisrupt.length} invalid disruption records`:`${(data.disruptions||[]).filter(d=>d.status==='Active').length} active delay/issue constraints are structurally valid`);
 const roots=new Set(['Bad Specification','Test Execution','Sample / DUT','Equipment / Facility','Planning / Resource','Test Method / Development']);const badIssues=(data.issues||[]).filter(i=>!ids.programmes.has(i.programmeId)||!roots.has(i.rootCause));push('Lessons-learned issue classification',badIssues.length===0,badIssues.length?`${badIssues.length} issues have invalid programme/root-cause classification`:`${(data.issues||[]).length} issues are classified for automatic lessons learned`);
 push('Period KPI history',(data.testRuns||[]).length>=50,`${(data.testRuns||[]).length} canonical test-run records available for week/month/custom-period analytics`);
 ensureCostFramework(data);const costBad=(data.legs||[]).filter(l=>{const c=estimateLegCost(data,l);return !Number.isFinite(c.total)||c.total<0||['labour','equipment','consumables','external','development','overhead','contingency'].some(k=>!Number.isFinite(c[k])||c[k]<0)});push('Test cost framework',costBad.length===0,costBad.length?`${costBad.length} legs have invalid cost components`:`${data.legs.length} test legs have deterministic non-negative cost breakdowns`);
 const port=portfolioCost(data);push('Programme cost roll-up',Number.isFinite(port.totalForecast)&&port.totalForecast>=0&&port.programmes.length===data.programmes.length,`${port.programmes.length} programmes roll up to forecast ${Math.round(port.totalForecast)}`);
 const samplePlanBad=(data.legs||[]).filter(l=>l.status!=='Completed'&&l.plannedStart&&l.sampleReadyDate&&new Date(l.plannedStart)<new Date(l.sampleReadyDate));push('Sample-ready planning constraint',samplePlanBad.length===0,samplePlanBad.length?`${samplePlanBad.length} planned legs start before samples are ready`:'Every planned leg respects its sample-ready input');
 const unreleasedScheduled=(data.legs||[]).filter(l=>l.plannedStart&&((data.programmes.find(p=>p.id===l.programmeId)?.gateStatus||'Released')!=='Released'||((data.specifications||[]).some(s=>s.programmeId===l.programmeId)&&!(data.specifications||[]).some(s=>s.programmeId===l.programmeId&&s.status==='Released'))));push('Programme/specification release gates',unreleasedScheduled.length===0,unreleasedScheduled.length?`${unreleasedScheduled.length} unreleased legs consume future capacity`:'Unreleased programmes/specifications do not consume committed future capacity');
 const auditStatuses=new Set(['Not Audited','Conform','OFI','Minor','Major','N/A']);const auditBad=(data.audits||[]).filter(a=>!AUDIT_STANDARDS[a.standard]||!Array.isArray(a.items)||a.items.some(i=>!auditStatuses.has(i.status)||!i.reference||!i.title)||!Number.isFinite(auditScore(a).score));push('Audit workbench integrity',auditBad.length===0,auditBad.length?`${auditBad.length} audit records are structurally invalid`:`${(data.audits||[]).length} audit records across ${Object.keys(AUDIT_STANDARDS).length} supported readiness frameworks`);
 const oppBad=(data.opportunities||[]).filter(o=>!o.id||!o.name||!Number.isFinite(Number(o.probability))||Number(o.probability)<0||Number(o.probability)>100||new Date(o.expectedStart)>=new Date(o.dueDate)||(o.similarProgrammeId&&!ids.programmes.has(o.similarProgrammeId))||(o.expectedMethodIds||[]).some(mid=>!ids.methods.has(mid)));push('Potential-project demand inputs',oppBad.length===0,oppBad.length?`${oppBad.length} pipeline projects have invalid probability/date/reference inputs`:`${(data.opportunities||[]).length} potential projects are valid for probability-weighted capacity forecasting`);
 const cfCommitted=capacityForecast(data,12,'committed'),cfWeighted=capacityForecast(data,12,'weighted'),cfFull=capacityForecast(data,12,'full'),pipe=x=>x.weeks.reduce((a,w)=>a+w.pipelineEq+w.pipelineStaff,0);const cfOk=cfWeighted.weeks.length===12&&cfWeighted.weeks.every(w=>Number.isFinite(w.equipmentGapHours)&&Number.isFinite(w.staffGapHours))&&pipe(cfCommitted)<=pipe(cfWeighted)&&pipe(cfWeighted)<=pipe(cfFull);push('Future capacity forecast model',cfOk,cfOk?`12-week committed / weighted / full-pipeline scenarios reconcile; weighted demand ${Math.round(pipe(cfWeighted))}h`:'Capacity scenario ordering or forecast values are invalid');
 const polIds=new Set((data.maintenancePolicies||[]).map(p=>p.id));const maintBad=(data.maintenancePolicies||[]).filter(p=>!ids.equipment.has(p.equipmentId)||!Number.isFinite(Number(p.durationHours))||Number(p.durationHours)<=0||!Number.isFinite(Number(p.intervalDays))||Number(p.intervalDays)<=0||!p.nextDueDate);const pmBad=(data.maintenance||[]).filter(m=>m.policyId&&(!polIds.has(m.policyId)||!ids.equipment.has(m.equipmentId)||new Date(m.start)>=new Date(m.end)));push('Maintenance policy integrity',maintBad.length===0&&pmBad.length===0,(maintBad.length||pmBad.length)?`${maintBad.length} invalid policies / ${pmBad.length} invalid planned events`:`${(data.maintenancePolicies||[]).length} asset policies and ${(data.maintenance||[]).filter(m=>m.policyId).length} planned PM windows are valid`);
 const pmOverlap=(data.maintenance||[]).filter(m=>m.policyId).filter(m=>(data.bookings||[]).some(b=>b.locked&&b.equipmentId===m.equipmentId&&overlap(m.start,m.end,b.start,b.end)));const ms=maintenanceSummary(data,90);push('Maintenance versus locked work',pmOverlap.length===0,pmOverlap.length?`${pmOverlap.length} planned PM windows overlap locked equipment bookings`:`${ms.due.length} due items can be managed without conflicting with locked work`);
 const timedRuns=(data.testRuns||[]).filter(r=>r.actualEnd);const badTime=timedRuns.filter(r=>['actualSetupHours','actualExecutionHours','actualTeardownHours','actualAnalysisHours','queueHours','reworkHours'].some(k=>!Number.isFinite(Number(r[k]))||Number(r[k])<0));push('Actual test-time accounting',badTime.length===0,badTime.length?`${badTime.length} completed runs have invalid time components`:`${timedRuns.length} completed runs carry setup / execution / teardown / analysis / queue / rework time`);
 const learned=(data.methods||[]).filter(m=>Number(m.learningRuns)>=3);const learnedBad=learned.filter(m=>['learnedSetupHours','learnedExecutionHours','learnedTeardownHours','learnedAnalysisHours','learnedTotalHours'].some(k=>!Number.isFinite(Number(m[k]))||Number(m[k])<0));push('Learning-based planning standards',learnedBad.length===0&&learned.length>0,learnedBad.length?`${learnedBad.length} learned method standards are invalid`:`${learned.length} methods have evidence-based learned planning durations`);
 const eff=efficiencyMetrics(data,new Date(DEMO_NOW.getTime()-120*86400000),DEMO_NOW);const effKeys=['productiveTestPct','executionSharePct','setupPct','analysisPct','teardownPct','queueLossPct','reworkBurdenPct','handsOnPct','firstTimeRightPct','automationLeveragePct','developmentEfficiencyPct'];const effBad=effKeys.filter(k=>!Number.isFinite(Number(eff[k]))||Number(eff[k])<0||(k!=='developmentEfficiencyPct'&&Number(eff[k])>100));push('Laboratory efficiency metrics',effBad.length===0,effBad.length?`Invalid efficiency measures: ${effBad.join(', ')}`:`${effKeys.length} closed-loop efficiency KPIs reconcile to actual time records`);
 const liveBad=(data.liveSessions||[]).filter(x=>!ids.legs.has(x.legId)||!ids.methods.has(x.methodId)||!Array.isArray(x.channels)||!Array.isArray(x.readings)||x.readings.some(r=>!r.timestamp||typeof r.values!=='object'));const ruleBad=(data.liveAlertRules||[]).filter(r=>!r.id||!r.sessionId||!r.channel||(!Number.isFinite(Number(r.zScore))&&!Number.isFinite(Number(r.rateLimit))&&r.min==null&&r.max==null));push('Live test-data monitor integrity',liveBad.length===0&&ruleBad.length===0,(liveBad.length||ruleBad.length)?`${liveBad.length} sessions / ${ruleBad.length} alert rules invalid`:`${(data.liveSessions||[]).length} live sessions and ${(data.liveAlertRules||[]).length} configurable anomaly rules are valid`);
 const reportBad=(data.testReports||[]).filter(r=>!ids.legs.has(r.legId)||!ids.programmes.has(r.programmeId));push('Automated test-report traceability',reportBad.length===0,reportBad.length?`${reportBad.length} automated reports have broken source links`:`${(data.testReports||[]).length} generated report records retain programme/leg traceability`);
 const cf=data.costFramework||{};const skillBad=Object.entries(cf.skillRates||{}).filter(([,v])=>!Number.isFinite(Number(v))||Number(v)<0),methodCostBad=Object.entries(cf.methodOverrides||{}).filter(([id,v])=>!ids.methods.has(id)||['labourRate','equipmentRate','fixedConsumables','consumablesPerDut','externalCost'].some(k=>v[k]!=null&&(!Number.isFinite(Number(v[k]))||Number(v[k])<0)));push('Granular test / skill cost definitions',skillBad.length===0&&methodCostBad.length===0,(skillBad.length||methodCostBad.length)?`${skillBad.length} skill rates / ${methodCostBad.length} test overrides invalid`:`${Object.keys(cf.skillRates||{}).length} skill rates and ${Object.keys(cf.methodOverrides||{}).length} test-specific overrides are valid`);
 const synergy=serviceSynergy(data,120),rec=operationalRecommendations(data);push('Calibration-maintenance synergy engine',Array.isArray(synergy)&&synergy.every(x=>Number.isFinite(Number(x.avoidedDowntimeHours||0))),`${synergy.length} combined service opportunities evaluated`);push('Automated operational recommendations',rec.length>0&&rec.every(r=>r.title&&r.detail&&r.solution&&r.impact),rec.length?`${rec.length} evidence-backed bottleneck/issue solutions proposed`:'No operational recommendations generated');
 const popBad=(data.legs||[]).filter(l=>!Array.isArray(l.dutIds)||l.dutIds.some(id=>!ids.duts.has(id)));push('Multi-leg DUT population model',popBad.length===0,popBad.length?`${popBad.length} legs have invalid DUT populations`:`${data.legs.length} legs preserve explicit DUT populations and genealogy`);
 const depBad=(data.legs||[]).filter(l=>(l.predecessorIds||[]).some(id=>!ids.legs.has(id)||data.legs.find(x=>x.id===id)?.programmeId!==l.programmeId));push('Validation dependency graph integrity',depBad.length===0,depBad.length?`${depBad.length} legs have invalid cross-programme/missing predecessors`:`${data.legs.reduce((a,l)=>a+(l.predecessorIds?.length||0),0)} dependency links form a valid programme graph`);
 const esc=escalationSummary(data),escalationRuleBad=(data.escalationRules||[]).filter(r=>!r.id||!['Low','Medium','High','Critical'].includes(r.severity)||!Array.isArray(r.notifyRoles)||!Number.isFinite(Number(r.slaMinutes)));push('Escalation framework integrity',escalationRuleBad.length===0,escalationRuleBad.length?`${escalationRuleBad.length} escalation rules invalid`:`${data.escalationRules.length} severity rules · ${esc.open} open operational events`);
 const eventBad=(data.operationalEvents||[]).filter(e=>!e.id||!e.sourceType||!e.severity||!e.status||(e.programmeId&&!ids.programmes.has(e.programmeId))||(e.legId&&!ids.legs.has(e.legId)));push('Exception-to-action traceability',eventBad.length===0,eventBad.length?`${eventBad.length} operational events have broken links`:`${(data.operationalEvents||[]).length} escalation events retain programme/leg traceability`);
 const lessonBad=(data.lessonsLearned||[]).filter(l=>!l.id||!l.lesson||!l.source||(l.methodId&&!ids.methods.has(l.methodId))||(l.sourceIssueIds||[]).some(id=>!(data.issues||[]).some(i=>i.id===id)));push('Lessons-learned provenance',lessonBad.length===0,lessonBad.length?`${lessonBad.length} lessons have invalid provenance`:`${(data.lessonsLearned||[]).length} manual/automatic lessons retain source evidence`);
 const qualityBad=(data.qualityEvents||[]).filter(q=>!q.id||!q.type||!q.status||(q.programmeId&&!ids.programmes.has(q.programmeId))||(q.legId&&!ids.legs.has(q.legId))||(q.dutIds||[]).some(id=>!ids.duts.has(id)));const capaBad=(data.capaActions||[]).filter(c=>!c.id||!c.qualityEventId||!(data.qualityEvents||[]).some(q=>q.id===c.qualityEventId)||!c.description||!c.owner);push('Deviation / NCR / CAPA traceability',qualityBad.length===0&&capaBad.length===0,(qualityBad.length||capaBad.length)?`${qualityBad.length} quality events / ${capaBad.length} CAPA actions have invalid links`:`${(data.qualityEvents||[]).length} quality events and ${(data.capaActions||[]).length} CAPA actions retain source and ownership traceability`);
 const locIds=new Set((data.sampleLocations||[]).map(x=>x.id));const custodyBad=(data.custodyEvents||[]).filter(e=>!e.id||!ids.duts.has(e.dutId)||!locIds.has(e.to)||(e.from&&e.from!=='Supplier / build'&&!locIds.has(e.from)));const custodyMismatch=(data.duts||[]).filter(d=>{const ev=(data.custodyEvents||[]).filter(e=>e.dutId===d.id).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))[0];return ev&&d.currentLocation&&ev.to!==d.currentLocation;});push('DUT chain-of-custody integrity',custodyBad.length===0&&custodyMismatch.length===0,(custodyBad.length||custodyMismatch.length)?`${custodyBad.length} invalid custody events / ${custodyMismatch.length} current-location mismatches`:`${(data.custodyEvents||[]).length} custody events preserve DUT location/status genealogy`);
 const tplBad=(data.lesTemplates||[]).filter(t=>!t.id||!ids.methods.has(t.methodId)||!Array.isArray(t.steps)||!t.steps.length||new Set(t.steps.map(x=>x.id)).size!==t.steps.length);const execBad=(data.guidedExecutions||[]).filter(e=>!e.id||!ids.legs.has(e.legId)||!(data.lesTemplates||[]).some(t=>t.id===e.templateId)||!Array.isArray(e.stepStates));push('Guided LES execution integrity',tplBad.length===0&&execBad.length===0,(tplBad.length||execBad.length)?`${tplBad.length} templates / ${execBad.length} executions invalid`:`${(data.lesTemplates||[]).length} released LES templates · ${(data.guidedExecutions||[]).length} guided executions trace to controlled test legs`);
 const twinA=digitalTwinForecast(data,{iterations:200}),twinB=digitalTwinForecast(data,{iterations:200});const twinBad=twinA.results.filter((r,i)=>!(new Date(r.p50)<=new Date(r.p80)&&new Date(r.p80)<=new Date(r.p95))||r.onTimePct<0||r.onTimePct>100||JSON.stringify(r)!==JSON.stringify(twinB.results[i]));push('Probabilistic planning digital twin',twinBad.length===0&&twinA.results.length===data.programmes.length,twinBad.length?`${twinBad.length} forecast rows violate percentile/determinism bounds`:`${twinA.results.length} programmes have deterministic P50/P80/P95 and on-time probability forecasts`);
 const msaBad=(data.msaStudies||[]).filter(m=>!m.id||!ids.methods.has(m.methodId)||(m.equipmentId&&!ids.equipment.has(m.equipmentId))||!Number.isFinite(Number(m.totalGrrPct))||Number(m.totalGrrPct)<0);const uncBad=(data.uncertaintyBudgets||[]).filter(u=>!u.id||!ids.methods.has(u.methodId)||(u.equipmentId&&!ids.equipment.has(u.equipmentId))||!Number.isFinite(Number(u.expandedUncertainty))||Number(u.expandedUncertainty)<0||!Number.isFinite(Number(u.k))||Number(u.k)<=0);const refBad=(data.referenceStandards||[]).filter(r=>!r.id||!r.name||!r.dueDate);push('Metrology / MSA integrity',msaBad.length===0&&uncBad.length===0&&refBad.length===0,(msaBad.length||uncBad.length||refBad.length)?`${msaBad.length} MSA / ${uncBad.length} uncertainty / ${refBad.length} reference-standard records invalid`:`${(data.msaStudies||[]).length} MSA studies · ${(data.uncertaintyBudgets||[]).length} uncertainty budgets · ${(data.referenceStandards||[]).length} reference standards valid`);
 const invIds=new Set((data.inventoryItems||[]).map(i=>i.id));const invBad=(data.inventoryItems||[]).filter(i=>!i.id||!['Fixture','Consumable','Spare'].includes(i.type)||!Number.isFinite(Number(i.onHand))||Number(i.onHand)<0);const resBad=(data.inventoryReservations||[]).filter(r=>!invIds.has(r.itemId)||!ids.legs.has(r.legId)||!Number.isFinite(Number(r.quantity))||Number(r.quantity)<=0);let fixtureOver=0;for(const f of (data.inventoryItems||[]).filter(i=>i.type==='Fixture')){const bs=(data.bookings||[]).filter(b=>(f.compatibleMethodIds||[]).includes(b.methodId));for(const b of bs){const simultaneous=bs.filter(x=>overlap(b.start,b.end,x.start,x.end)).length;if(simultaneous>Number(f.onHand||0)){fixtureOver++;break;}}}push('Fixtures / consumables / spares integrity',invBad.length===0&&resBad.length===0&&fixtureOver===0,(invBad.length||resBad.length||fixtureOver)?`${invBad.length} items / ${resBad.length} reservations invalid · ${fixtureOver} fixture-capacity conflicts`:`${(data.inventoryItems||[]).length} inventory items and ${(data.inventoryReservations||[]).length} reservations are valid; reusable fixture capacity is conflict-free`);
 const health=predictiveAssetSummary(data),healthBad=(health.rows||[]).filter(r=>!ids.equipment.has(r.eq.id)||!Number.isFinite(Number(r.risk))||Number(r.risk)<0||Number(r.risk)>100);push('Predictive equipment health model',healthBad.length===0,healthBad.length?`${healthBad.length} asset-health scores invalid`:`${health.rows.length} equipment assets have bounded health/risk forecasts`);
 const labIds=new Set((data.externalLabs||[]).map(x=>x.id));const jobBad=(data.externalJobs||[]).filter(j=>!j.id||!ids.legs.has(j.legId)||!labIds.has(j.labId));const outsourced=(data.legs||[]).filter(l=>l.executionMode==='External');const extBad=outsourced.filter(l=>!(data.externalJobs||[]).some(j=>j.legId===l.id)||data.bookings.some(b=>b.legId===l.id&&b.status!=='Completed'));push('External laboratory control',jobBad.length===0&&extBad.length===0,(jobBad.length||extBad.length)?`${jobBad.length} invalid external jobs / ${extBad.length} outsourced legs retain conflicting internal bookings`:`${(data.externalLabs||[]).length} external laboratories and ${(data.externalJobs||[]).length} controlled external jobs reconcile to internal planning`);
 const simTarget=data.programmes[0]?.id;const sim=simTarget?programmeSimilarity(data,simTarget):[];const simBad=sim.filter((r,i)=>!ids.programmes.has(r.programme?.id)||r.programme?.id===simTarget||!Number.isFinite(Number(r.score))||r.score<0||r.score>100||sim.findIndex(x=>x.programme?.id===r.programme?.id)!==i);push('Knowledge / programme-similarity graph',simBad.length===0&&(!simTarget||sim.length>0),simBad.length?`${simBad.length} similarity links invalid`:`${sim.length} comparable programmes scored with reusable method/lesson context`);
 const wiMissing=(data.methods||[]).filter(m=>m.active&&!(data.lesTemplates||[]).some(t=>t.methodId===m.id&&t.status==='Released'));push('Standard-test work instructions',wiMissing.length===0,wiMissing.length?`${wiMissing.length} released methods lack a controlled work instruction`:`${data.methods.filter(m=>m.active).length} released standard tests have controlled work instructions`);
 const prBad=(data.prototypeRequests||[]).filter(r=>!r.id||!r.name||!Number.isFinite(Number(r.quantity))||Number(r.quantity)<=0||(r.linkedProgrammeId&&!ids.programmes.has(r.linkedProgrammeId)));const linkBad=(data.prototypeRequests||[]).filter(r=>r.linkedProgrammeId&&(r.plannedReady||r.completedAt)).filter(r=>{const first=data.legs.filter(l=>l.programmeId===r.linkedProgrammeId).sort((a,b)=>(a.sequence||0)-(b.sequence||0))[0],ready=r.completedAt||r.plannedReady;return first&&ready&&new Date(first.sampleReadyDate||0)<new Date(ready)});push('Prototype-build / validation linkage',prBad.length===0&&linkBad.length===0,(prBad.length||linkBad.length)?`${prBad.length} invalid prototype requests / ${linkBad.length} validation readiness links inconsistent`:`${(data.prototypeRequests||[]).length} prototype requests are valid and linked builds constrain validation sample readiness`);
 const qEvidenceBad=(data.qualityEvents||[]).filter(q=>q.status==='Closed'&&!(q.evidenceRefs||[]).length),cEvidenceBad=(data.capaActions||[]).filter(c=>c.effectivenessStatus==='Effective'&&!(c.effectivenessEvidence||[]).length);push('Evidence-backed quality closure',qEvidenceBad.length===0&&cEvidenceBad.length===0,(qEvidenceBad.length||cEvidenceBad.length)?`${qEvidenceBad.length} closed quality events / ${cEvidenceBad.length} effective CAPAs lack evidence`:'Closed quality events and effective CAPAs retain objective evidence references');
 const pass=checks.filter(c=>c.ok).length;return {checks,pass,fail:checks.length-pass,overall:pass===checks.length?'PASS':'FAIL'};}
function detectCycles(legs){const graph=Object.fromEntries(legs.map(l=>[l.id,l.predecessorIds||[]]));const state={},path=[];function dfs(n){if(state[n]===1)return [...path,n];if(state[n]===2)return null;state[n]=1;path.push(n);for(const p of graph[n]||[]){const r=dfs(p);if(r)return r;}path.pop();state[n]=2;return null;}for(const n of Object.keys(graph)){const r=dfs(n);if(r)return [r];}return [];}

function periodBounds(start,end){const s=new Date(start||DEMO_NOW),e=new Date(end||DEMO_NOW);if(/^\d{4}-\d{2}-\d{2}$/.test(String(start||'')))s.setUTCHours(0,0,0,0);if(/^\d{4}-\d{2}-\d{2}$/.test(String(end||'')))e.setUTCHours(23,59,59,999);return s<=e?[s,e]:[e,s];}
function inPeriod(x,start,end){if(!x)return false;const d=new Date(x);return d>=start&&d<=end;}
function overlapHours(a,b,start,end){if(!a||!b)return 0;const s=Math.max(new Date(a).getTime(),start.getTime()),e=Math.min(new Date(b).getTime(),end.getTime());return Math.max(0,(e-s)/3600000);}
function medianOf(vals){if(!vals.length)return 0;const a=[...vals].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}

export function periodMetrics(data,start,end){
 const [s,e]=periodBounds(start,end);const runs=(data.testRuns||[]).filter(r=>inPeriod(r.actualEnd,s,e));const issues=(data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e));const futureBookings=(data.bookings||[]).filter(b=>new Date(b.start)>=DEMO_NOW&&overlap(b.start,b.end,s,e));
 const completed=runs.length,pass=runs.filter(r=>r.outcome==='PASS').length,rework=runs.filter(r=>r.outcome==='REWORK').length,failed=runs.filter(r=>r.outcome==='FAIL').length;
 const onTime=runs.filter(r=>r.plannedEnd&&new Date(r.actualEnd)<=new Date(r.plannedEnd)).length;const actualHours=runs.reduce((a,r)=>a+(Number(r.actualHours)||0),0),standardHours=runs.reduce((a,r)=>a+(Number(r.standardHours)||0),0),turn=runs.map(r=>Number(r.actualHours)||0).filter(Number.isFinite);
 const specIssues=issues.filter(i=>i.rootCause==='Bad Specification').length,execIssues=issues.filter(i=>i.rootCause==='Test Execution').length,delayHours=issues.reduce((a,i)=>a+(Number(i.delayHours)||0),0);
 const eqRows=(data.equipment||[]).map(eq=>{const hist=runs.filter(r=>r.equipmentId===eq.id).reduce((a,r)=>a+(Number(r.actualHours)||0),0);const fut=futureBookings.filter(b=>b.equipmentId===eq.id).reduce((a,b)=>a+overlapHours(b.start,b.end,s,e),0);const days=Math.max(1,(e-s)/86400000+1),avail=days*24;return{id:eq.id,name:eq.name,type:eq.type,hours:hist+fut,pct:Math.min(100,Math.round((hist+fut)/avail*100))};});
 const staffRows=(data.staff||[]).map(st=>{const hist=runs.filter(r=>r.staffId===st.id).reduce((a,r)=>{const m=data.methods.find(x=>x.id===r.methodId);return a+(m?.continuousStaffing?Number(r.actualHours)||0:(m?.setupHours||0)+(m?.teardownHours||0)+(m?.analysisHours||0))},0);const fut=futureBookings.filter(b=>b.staffId===st.id).reduce((a,b)=>a+overlapHours(b.start,b.staffEnd||b.end,s,e),0);const days=Math.max(1,(e-s)/86400000+1),avail=days/7*5*8;return{id:st.id,name:st.name,hours:hist+fut,pct:Math.min(100,Math.round((hist+fut)/Math.max(1,avail)*100))};});
 const reqEvidence=new Set();for(const r of runs){const leg=data.legs.find(l=>l.id===r.legId);for(const id of leg?.requirementIds||[])reqEvidence.add(id);}
 return {start:s.toISOString(),end:e.toISOString(),completed,pass,failed,rework,passRate:Math.round(pass/Math.max(1,completed)*100),onTimePct:Math.round(onTime/Math.max(1,completed)*100),avgTurnaround:Math.round((turn.reduce((a,b)=>a+b,0)/Math.max(1,turn.length))*10)/10,medianTurnaround:Math.round(medianOf(turn)*10)/10,actualHours:Math.round(actualHours),standardHours:Math.round(standardHours),durationVariancePct:Math.round((actualHours-standardHours)/Math.max(1,standardHours)*100),issues:issues.length,specIssues,execIssues,specIssuePct:Math.round(specIssues/Math.max(1,issues.length)*100),execIssuePct:Math.round(execIssues/Math.max(1,issues.length)*100),issueDelayHours:Math.round(delayHours),requirementEvidence:reqEvidence.size,equipmentUtil:Math.round(eqRows.reduce((a,x)=>a+x.pct,0)/Math.max(1,eqRows.length)),staffUtil:Math.round(staffRows.reduce((a,x)=>a+x.pct,0)/Math.max(1,staffRows.length)),equipment:eqRows,staff:staffRows,runs,periodIssues:issues};
}

function bucketStart(date,mode){const d=new Date(date);d.setUTCHours(0,0,0,0);if(mode==='week'){const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);}else if(mode==='month')d.setUTCDate(1);return d;}
function bucketKey(date,mode){const d=bucketStart(date,mode);return d.toISOString().slice(0,10);}
export function periodTrend(data,start,end){const [s,e]=periodBounds(start,end),days=Math.max(1,Math.ceil((e-s)/86400000));const mode=days<=35?'day':days<=140?'week':'month';const rows=new Map();let d=bucketStart(s,mode);while(d<=e){const key=d.toISOString().slice(0,10);rows.set(key,{key,date:key,completed:0,pass:0,fail:0,issues:0,delayHours:0});if(mode==='day')d=new Date(d.getTime()+86400000);else if(mode==='week')d=new Date(d.getTime()+7*86400000);else{d=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1));}}
 for(const r of (data.testRuns||[]).filter(r=>inPeriod(r.actualEnd,s,e))){const x=rows.get(bucketKey(r.actualEnd,mode));if(x){x.completed++;if(r.outcome==='PASS')x.pass++;if(r.outcome==='FAIL')x.fail++;}}
 for(const i of (data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e))){const x=rows.get(bucketKey(i.reportedAt,mode));if(x){x.issues++;x.delayHours+=Number(i.delayHours)||0;}}
 return {mode,rows:[...rows.values()]};
}

export function issueAnalytics(data,start,end){const [s,e]=periodBounds(start,end),issues=(data.issues||[]).filter(i=>inPeriod(i.reportedAt,s,e));const group=(key)=>{const m={};for(const i of issues){const k=i[key]||'Unclassified';m[k]=m[k]||{name:k,count:0,delayHours:0,severe:0,lesson:i.lesson||''};m[k].count++;m[k].delayHours+=Number(i.delayHours)||0;if(i.severity==='High')m[k].severe++;if(!m[k].lesson&&i.lesson)m[k].lesson=i.lesson;}return Object.values(m).sort((a,b)=>b.count-a.count||b.delayHours-a.delayHours)};const topTypes=group('issueType'),rootCauses=group('rootCause');const total=issues.length;
 const lessons=topTypes.slice(0,6).map((x,idx)=>({rank:idx+1,issue:x.name,occurrences:x.count,share:Math.round(x.count/Math.max(1,total)*100),delayHours:Math.round(x.delayHours),priority:x.count>=Math.max(3,total*.18)||x.delayHours>=48?'High':x.count>=2?'Medium':'Low',lesson:x.lesson||`Review recurring ${x.name.toLowerCase()} and standardise preventive controls.`}));
 return {issues,total,topTypes,rootCauses,lessons,testExecution:issues.filter(i=>i.rootCause==='Test Execution').length,badSpecification:issues.filter(i=>i.rootCause==='Bad Specification').length};
}
