import { DEMO_NOW } from './data.js';
const n=v=>Number(v)||0;
const mean=a=>a.reduce((x,y)=>x+y,0)/Math.max(1,a.length);
const sd=a=>{const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/Math.max(1,a.length));};
function channelDefaults(method){const cat=method?.category||'';if(/Temperature|Environmental|Humidity/.test(cat))return[{key:'temperature',name:'Chamber temperature',unit:'°C',target:125,min:120,max:130,sigma:1.2},{key:'dut_voltage',name:'DUT supply',unit:'V',target:12,min:11.5,max:12.5,sigma:.08},{key:'current',name:'DUT current',unit:'mA',target:42,min:35,max:50,sigma:2}];if(/Vibration|Mechanical|Shock/.test(cat))return[{key:'grms',name:'Vibration level',unit:'g RMS',target:18,min:16,max:20,sigma:.5},{key:'fixture_temp',name:'Fixture temperature',unit:'°C',target:36,min:15,max:55,sigma:2},{key:'dut_voltage',name:'DUT supply',unit:'V',target:12,min:11.5,max:12.5,sigma:.08}];return[{key:'voltage',name:'Measured voltage',unit:'V',target:10,min:8,max:14,sigma:.25},{key:'current',name:'Current',unit:'mA',target:35,min:25,max:45,sigma:2},{key:'temperature',name:'DUT temperature',unit:'°C',target:42,min:15,max:70,sigma:3}];}
export function ensureLiveState(data){data.liveSessions=data.liveSessions||[];data.liveAlertRules=data.liveAlertRules||[];data.liveAlerts=data.liveAlerts||[];data.testReports=data.testReports||[];if(!data.liveSessions.length){const candidates=(data.legs||[]).filter(l=>!['Completed','Cancelled','Failed'].includes(l.status)).slice(0,3);for(let i=0;i<candidates.length;i++){const l=candidates[i],m=data.methods.find(x=>x.id===l.methodId),channels=channelDefaults(m),id=`LIVE-${i+1}`;data.liveSessions.push({id,legId:l.id,programmeId:l.programmeId,methodId:l.methodId,status:i<2?'Streaming':'Paused',sourceType:'Demo simulator',sourceUrl:'',pollSeconds:3,startedAt:new Date(DEMO_NOW.getTime()-((i+1)*45*60000)).toISOString(),lastTick:null,channels,readings:[]});for(const c of channels)data.liveAlertRules.push({id:`RULE-${id}-${c.key}`,sessionId:id,channel:c.key,enabled:true,min:c.min,max:c.max,rateLimit:c.sigma*4,zScore:3,action:i===0?'Create issue':'Alert only',severity:'High'});for(let k=0;k<32;k++)ingestReading(data,id,generateValues(data.liveSessions.at(-1),k),new Date(DEMO_NOW.getTime()-(32-k)*180000).toISOString(),{evaluate:k>4});}}
 return data;}
function generateValues(s,idx,inject=false){const values={};for(let i=0;i<s.channels.length;i++){const c=s.channels[i],wave=Math.sin((idx+i*2)/4)*c.sigma*.7+Math.cos((idx+i)/7)*c.sigma*.25;let v=c.target+wave;if(inject&&i===0)v=c.max+c.sigma*5;if(!inject&&idx>0&&idx%29===0&&i===1)v=c.max+c.sigma*2.5;values[c.key]=Math.round(v*100)/100;}return values;}
function evaluateChannel(data,s,c,value,ts){const rule=data.liveAlertRules.find(r=>r.sessionId===s.id&&r.channel===c.key&&r.enabled);if(!rule)return null;const hist=s.readings.slice(-12).map(r=>n(r.values[c.key])).filter(Number.isFinite),prev=hist.at(-1),z=hist.length>=5&&sd(hist)>.0001?Math.abs((value-mean(hist))/sd(hist)):0,rate=prev==null?0:Math.abs(value-prev);let type='',message='';if(rule.min!=null&&value<Number(rule.min)){type='Low limit';message=`${c.name} ${value}${c.unit} below ${rule.min}${c.unit}`;}else if(rule.max!=null&&value>Number(rule.max)){type='High limit';message=`${c.name} ${value}${c.unit} above ${rule.max}${c.unit}`;}else if(rule.rateLimit&&rate>Number(rule.rateLimit)){type='Rate of change';message=`${c.name} changed ${rate.toFixed(2)}${c.unit} between samples`;}else if(rule.zScore&&z>Number(rule.zScore)){type='Statistical anomaly';message=`${c.name} z-score ${z.toFixed(1)} exceeds ${rule.zScore}`;}if(!type)return null;const duplicate=data.liveAlerts.find(a=>a.sessionId===s.id&&a.channel===c.key&&a.status==='Open'&&a.type===type&&new Date(ts)-new Date(a.timestamp)<15*60000);if(duplicate)return duplicate;const alert={id:`ALT-${String(data.liveAlerts.length+1).padStart(3,'0')}`,sessionId:s.id,legId:s.legId,programmeId:s.programmeId,channel:c.key,channelName:c.name,timestamp:ts,value,unit:c.unit,type,severity:rule.severity||'Medium',message,status:'Open',ruleId:rule.id,ackBy:null};data.liveAlerts.push(alert);if(rule.action==='Create issue'){const issue={id:`ISS-${String((data.issues||[]).length+1).padStart(3,'0')}`,reportedAt:ts,programmeId:s.programmeId,legId:s.legId,testRunId:null,specificationId:null,issueType:`Live anomaly · ${c.name}`,rootCause:'Test Execution',severity:alert.severity,delayHours:0,status:'Open',description:message,lesson:'Review live anomaly and containment before continuing the test.',correctiveAction:'Acknowledge alarm, assess DUT/test validity and disposition before continuing.',owner:data.settings?.actor||'Demo Lab Manager',liveAlertId:alert.id};data.issues.push(issue);alert.issueId=issue.id;}return alert;}
export function ingestReading(data,sessionId,values,timestamp=new Date().toISOString(),{evaluate=true}={}){ensureLiveState(data);const s=data.liveSessions.find(x=>x.id===sessionId);if(!s)return null;const row={timestamp,values:{...values}};if(evaluate)for(const c of s.channels)evaluateChannel(data,s,c,n(values[c.key]),timestamp);s.readings.push(row);if(s.readings.length>240)s.readings=s.readings.slice(-240);s.lastTick=timestamp;return row;}
export function simulateLiveTick(data,sessionId,{inject=false}={}){ensureLiveState(data);const s=data.liveSessions.find(x=>x.id===sessionId);if(!s||s.status!=='Streaming')return null;const idx=s.readings.length,ts=new Date().toISOString();return ingestReading(data,sessionId,generateValues(s,idx,inject),ts,{evaluate:true});}
export function liveSessionSummary(data,s){const alerts=data.liveAlerts.filter(a=>a.sessionId===s.id),open=alerts.filter(a=>a.status==='Open');const last=s.readings.at(-1);return{last,alerts:alerts.length,open:open.length,status:s.status,points:s.readings.length};}
export function acknowledgeAlert(data,id,actor='Demo Lab Manager'){const a=data.liveAlerts.find(x=>x.id===id);if(!a)return false;a.status='Acknowledged';a.ackBy=actor;a.ackAt=new Date().toISOString();return true;}
