import { validCoordinate } from './config.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const DAY_COLORS=Object.freeze(['#0f6b61','#3b72a8','#7a5dc7','#c95e42','#c58b2b','#2f7d62','#9a5b8f','#4a92b5','#a84f66','#557a46','#8059a8','#a66b3e']);
const instances=new WeakMap();
const keyOf=p=>p?.id||`${p?.name||''}:${Number(p?.lat).toFixed?.(4)},${Number(p?.lon).toFixed?.(4)}`;
const typeLabel=t=>({park:'Park / natuur','mountain-village':'Bergplaats','viewpoint':'Uitzichtpunt','attraction':'Bezienswaardigheid','museum':'Museum','castle':'Kasteel','historic':'Historisch','natural':'Natuur','poi':'Bezienswaardigheid'}[String(t||'').toLowerCase()]||String(t||'POI').replaceAll('_',' '));
function unique(items=[]){const seen=new Set();return items.filter(x=>{const k=keyOf(x);if(!x||seen.has(k))return false;seen.add(k);return true})}

export function buildMapModel(plan){
  const routes=(plan.days||[]).map(d=>({day:d.day,kind:d.kind,from:d.from,to:d.to,geometry:(d.geometry||[]).filter(validCoordinate),source:d.routeSource||'offline-estimate',distanceKm:d.distanceKm,driveHours:d.driveHours,roadDetails:d.roadDetails||[]}));
  const dayPois=(plan.days||[]).flatMap(day=>(day.offlinePois||[]).filter(validCoordinate).map(p=>({...p,day:day.day})));
  const dayKeys=new Set(dayPois.map(keyOf));
  const extraPois=(plan.offlinePois||[]).filter(validCoordinate).filter(p=>!dayKeys.has(keyOf(p))).map(p=>({...p,day:null}));
  const pois=unique([...dayPois,...extraPois]);
  const rests=(plan.days||[]).flatMap(day=>(day.plannedStops||[]).filter(validCoordinate).map(stop=>({...stop,day:day.day})));
  const nights=(plan.overnights||[]).map(n=>({night:n.night,afterDay:n.afterDay,state:n.state,zone:n.zone,point:n.state==='SPECIFIC_LIVE_ACCOMMODATION'?n.property:n.zone,property:n.property||null,source:n.source||n.property?.source||'offline-catalog'})).filter(x=>validCoordinate(x.point));
  const cities=unique((plan.days||[]).flatMap(day=>[{...day.fromPoint,name:day.from,day:day.day,role:'from'},{...day.toPoint,name:day.to,day:day.day,role:'to'}]).filter(validCoordinate));
  return{routes,pois,rests,nights,cities,origin:plan.origin,destinationId:plan.destinationId};
}
export function mapConsistency(plan,model=buildMapModel(plan)){return{valid:model.routes.length===plan.days.length&&model.routes.every(r=>r.geometry.length>=1)&&model.nights.length===plan.overnights.length&&model.pois.length>0,routeDays:model.routes.length,nights:model.nights.length,pois:model.pois.length,rests:model.rests.length}}
function popupPoi(p){return`<strong>${esc(p.name)}</strong><span class="map-popup-meta">${esc(typeLabel(p.type))}${p.day?` · dag ${p.day}`:''}</span><span class="map-popup-meta">${p.live?'Live verrijkt':'Offline verpakt'} · ${esc(p.source||'ReisSlim reiskennis')}</span><span class="map-popup-meta">${Number(p.lat).toFixed(4)}, ${Number(p.lon).toFixed(4)}</span>${p.tags?.length?`<div class="map-popup-list">${p.tags.slice(0,5).map(x=>`<span>${esc(x)}</span>`).join(' · ')}</div>`:''}`}
function popupRest(p){return`<strong>☕ ${esc(p.name)}</strong><span class="map-popup-meta">Ruststop · dag ${p.day}${p.approxAfterKm?` · ±${p.approxAfterKm} km na vertrek`:''}</span><span class="map-popup-meta">${esc(p.reason||'Geplande rijpauze volgens voertuigprofiel')}</span><span class="map-popup-meta">${esc(p.source||'offline-catalog')}</span>`}
function popupNight(n){const p=n.point;return`<strong>▣ Nacht ${n.night} · ${esc(p.name||'Overnachting')}</strong><span class="map-popup-meta">${n.state==='SPECIFIC_LIVE_ACCOMMODATION'?'Specifiek live verblijf':'Geplande accommodatiezone'} · na dag ${n.afterDay}</span><span class="map-popup-meta">${esc(n.source||'offline-catalog')}</span>${n.zone?.preferredRadiusKm?`<span class="map-popup-meta">Zoekradius zone: ±${n.zone.preferredRadiusKm} km</span>`:''}`}
function popupRoute(r){const roads=[];const seen=new Set();for(const step of r.roadDetails||[]){const label=[step.ref,step.name].filter(Boolean).join(' · ');if(label&&!seen.has(label)){seen.add(label);roads.push(label)}if(roads.length>=7)break}return`<strong>Dag ${r.day} · ${esc(r.from)} → ${esc(r.to)}</strong><span class="map-popup-meta">${Math.round(r.distanceKm||0)} km · ${Number(r.driveHours||0).toFixed(1)} u · ${esc(r.source)}</span>${roads.length?`<div class="map-popup-list">${roads.map(esc).join(' · ')}</div>`:''}`}
function leafletReady(container){return typeof document!=='undefined'&&Boolean(globalThis.L)&&container&&typeof container.appendChild==='function'}
function clearInstance(container){const old=instances.get(container);if(old){try{old.remove()}catch{}instances.delete(container)}container.innerHTML=''}
function addTile(map,enabled){if(!enabled)return null;return globalThis.L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap-bijdragers'}).addTo(map)}
function fit(map,points){const latlngs=points.filter(validCoordinate).map(p=>[Number(p.lat),Number(p.lon)]);if(!latlngs.length)return;if(latlngs.length===1)map.setView(latlngs[0],10);else map.fitBounds(latlngs,{padding:[28,28],maxZoom:13})}
function makeLegend(container,entries){const legend=document.createElement('div');legend.className='map-layer-legend';for(const entry of entries){const label=document.createElement('label'),input=document.createElement('input'),swatch=document.createElement('i'),text=document.createElement('span');input.type='checkbox';input.checked=true;input.dataset.layerToggle=entry.id;swatch.style.setProperty('--swatch',entry.color||'#657a76');text.textContent=entry.label;label.append(input,swatch,text);legend.append(label);input.addEventListener('change',()=>entry.toggle(input.checked))}container.append(legend)}
function circle(map,group,p,options,popup){return globalThis.L.circleMarker([p.lat,p.lon],options).addTo(group).bindPopup(popup)}

function renderLeafletPlan(container,plan,{liveBasemap=true}={}){
  clearInstance(container);const canvas=document.createElement('div');canvas.className='leaflet-canvas';canvas.style.minHeight='260px';container.append(canvas);const map=globalThis.L.map(canvas,{zoomControl:true,preferCanvas:true});instances.set(container,map);addTile(map,liveBasemap);
  const model=buildMapModel(plan),entries=[],all=[plan.origin];
  model.routes.forEach(route=>{const group=globalThis.L.layerGroup().addTo(map),color=DAY_COLORS[(Math.max(1,Number(route.day))-1)%DAY_COLORS.length],coords=route.geometry.map(p=>[p.lat,p.lon]);all.push(...route.geometry);if(coords.length>=2)globalThis.L.polyline(coords,{color:'#fff',weight:8,opacity:.82}).addTo(group),globalThis.L.polyline(coords,{color,weight:5,opacity:.96}).addTo(group).bindPopup(popupRoute(route));entries.push({id:`day-${route.day}`,label:`Dag ${route.day} · ${route.from} → ${route.to}`,color,toggle:on=>on?map.addLayer(group):map.removeLayer(group)})});
  const poiGroup=globalThis.L.layerGroup().addTo(map);for(const p of model.pois){all.push(p);circle(map,poiGroup,p,{radius:7,color:'#fff',weight:2,fillColor:'#d67b30',fillOpacity:1},popupPoi(p))}entries.push({id:'poi',label:`POI's (${model.pois.length})`,color:'#d67b30',toggle:on=>on?map.addLayer(poiGroup):map.removeLayer(poiGroup)});
  const restGroup=globalThis.L.layerGroup().addTo(map);for(const p of model.rests){all.push(p);circle(map,restGroup,p,{radius:7,color:'#fff',weight:2,fillColor:'#3b72a8',fillOpacity:1},popupRest(p))}entries.push({id:'rest',label:`Ruststops (${model.rests.length})`,color:'#3b72a8',toggle:on=>on?map.addLayer(restGroup):map.removeLayer(restGroup)});
  const nightGroup=globalThis.L.layerGroup().addTo(map);for(const n of model.nights){all.push(n.point);circle(map,nightGroup,n.point,{radius:8,color:'#fff',weight:2,fillColor:'#123f3a',fillOpacity:1},popupNight(n))}entries.push({id:'night',label:`Accommodatie (${model.nights.length})`,color:'#123f3a',toggle:on=>on?map.addLayer(nightGroup):map.removeLayer(nightGroup)});
  const cityGroup=globalThis.L.layerGroup().addTo(map);for(const p of model.cities){all.push(p);circle(map,cityGroup,p,{radius:4,color:'#153b37',weight:2,fillColor:'#fff',fillOpacity:1},`<strong>${esc(p.name)}</strong><span class="map-popup-meta">Routeplaats · dag ${p.day||'–'}</span>`)}entries.push({id:'cities',label:`Plaatsen (${model.cities.length})`,color:'#657a76',toggle:on=>on?map.addLayer(cityGroup):map.removeLayer(cityGroup)});
  if(validCoordinate(plan.origin)){circle(map,globalThis.L.layerGroup().addTo(map),plan.origin,{radius:9,color:'#fff',weight:3,fillColor:'#153b37',fillOpacity:1},`<strong>Start · ${esc(plan.origin.name)}</strong>`)}
  fit(map,all);makeLegend(container,entries);setTimeout(()=>map.invalidateSize(),60);return{rendered:true,interactive:true,routeDays:model.routes.length,pois:model.pois.length,rests:model.rests.length,nights:model.nights.length};
}
function renderLeafletDiscovery(container,origin,candidates,{liveBasemap=true}={}){
  clearInstance(container);const canvas=document.createElement('div');canvas.className='leaflet-canvas';canvas.style.minHeight='280px';container.append(canvas);const map=globalThis.L.map(canvas,{zoomControl:true,preferCanvas:true});instances.set(container,map);addTile(map,liveBasemap);const entries=[],all=[origin];
  if(validCoordinate(origin))circle(map,globalThis.L.layerGroup().addTo(map),origin,{radius:9,color:'#fff',weight:3,fillColor:'#153b37',fillOpacity:1},`<strong>Start · ${esc(origin.name)}</strong>`);
  for(const c of candidates||[]){if(!validCoordinate(c.anchor))continue;all.push(c.anchor);const group=globalThis.L.layerGroup().addTo(map),color=DAY_COLORS[(Math.max(1,Number(c.rank))-1)%DAY_COLORS.length],ctx=c.context||{};circle(map,group,c.anchor,{radius:10,color:'#fff',weight:3,fillColor:color,fillOpacity:1},`<strong>#${c.rank} ${esc(c.name)}</strong><span class="map-popup-meta">${esc(c.country)} · match ${c.score}/100</span><span class="map-popup-meta">${Math.round(c.totalDistanceKm||0)} km · €${Math.round(c.estimate||0)} · max ${Number(c.maxDayDrive||0).toFixed(1)} u</span><span class="map-popup-meta">${ctx.poiCount||0} POI · ${ctx.plannedRestCount||0} rust · ${ctx.nightCount||0} nachten</span>`);entries.push({id:`option-${c.id}`,label:`#${c.rank} ${c.name}`,color,toggle:on=>on?map.addLayer(group):map.removeLayer(group)})}
  fit(map,all);makeLegend(container,entries);setTimeout(()=>map.invalidateSize(),60);return{rendered:true,interactive:true,options:(candidates||[]).length};
}

// Deterministic SVG fallback is intentionally retained for tests and when Leaflet fails to load.
const TILE=256,MAX_LAT=85.05112878;
function mercator(point,z){const lat=Math.max(-MAX_LAT,Math.min(MAX_LAT,Number(point.lat))),lon=Number(point.lon),scale=TILE*(2**z),x=(lon+180)/360*scale,rad=lat*Math.PI/180,y=(1-Math.log(Math.tan(rad)+1/Math.cos(rad))/Math.PI)/2*scale;return{x,y}}
function frame(points,W=900,H=520,pad=64){const valid=points.filter(validCoordinate);if(!valid.length)return null;let z=2;for(let test=14;test>=2;test--){const px=valid.map(p=>mercator(p,test)),xs=px.map(p=>p.x),ys=px.map(p=>p.y);if(Math.max(...xs)-Math.min(...xs)<=W-pad*2&&Math.max(...ys)-Math.min(...ys)<=H-pad*2){z=test;break}}const px=valid.map(p=>mercator(p,z)),xs=px.map(p=>p.x),ys=px.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);let width=Math.max(260,maxX-minX+pad*2),height=Math.max(220,maxY-minY+pad*2),aspect=W/H;if(width/height<aspect)width=height*aspect;else height=width/aspect;const cx=(minX+maxX)/2,cy=(minY+maxY)/2;return{z,x:cx-width/2,y:cy-height/2,width,height,xy:p=>mercator(p,z)}}
function tiles(f,enabled){if(!enabled)return`<rect x="${f.x}" y="${f.y}" width="${f.width}" height="${f.height}" fill="#e2ece9"/>`;const n=2**f.z,out=[];for(let tx=Math.floor(f.x/TILE);tx<=Math.floor((f.x+f.width)/TILE);tx++)for(let ty=Math.max(0,Math.floor(f.y/TILE));ty<=Math.min(n-1,Math.floor((f.y+f.height)/TILE));ty++)out.push(`<image href="https://tile.openstreetmap.org/${f.z}/${((tx%n)+n)%n}/${ty}.png" x="${tx*TILE}" y="${ty*TILE}" width="256" height="256"/>`);return out.join('')}
function svgLegend(entries){return`<div class="map-layer-legend">${entries.map(e=>`<label><input type="checkbox" checked disabled><i style="--swatch:${e.color}"></i><span>${esc(e.label)}</span></label>`).join('')}</div>`}
function svgPlan(container,plan,{liveBasemap=true}={}){const m=buildMapModel(plan),all=[plan.origin,...m.routes.flatMap(r=>r.geometry),...m.pois,...m.rests,...m.nights.map(n=>n.point)],f=frame(all);if(!f){container.textContent='Geen kaartgeometrie';return{rendered:false}}const routes=m.routes.map(r=>{const color=DAY_COLORS[(r.day-1)%DAY_COLORS.length],pts=r.geometry.map(p=>{const q=f.xy(p);return`${q.x},${q.y}`}).join(' ');return`<polyline data-day="${r.day}" points="${pts}" fill="none" stroke="#fff" stroke-width="8"/><polyline data-day="${r.day}" points="${pts}" fill="none" stroke="${color}" stroke-width="5"><title>Dag ${r.day}: ${esc(r.from)} → ${esc(r.to)}</title></polyline>`}).join(''),markers=m.pois.map(p=>{const q=f.xy(p);return`<circle cx="${q.x}" cy="${q.y}" r="7" fill="#d67b30"><title>${esc(p.name)}</title></circle>`}).join('')+m.rests.map(p=>{const q=f.xy(p);return`<circle cx="${q.x}" cy="${q.y}" r="7" fill="#3b72a8"><title>${esc(p.name)}</title></circle>`}).join('')+m.nights.map(n=>{const q=f.xy(n.point);return`<rect x="${q.x-6}" y="${q.y-6}" width="12" height="12" fill="#123f3a"><title>${esc(n.point.name)}</title></rect>`}).join('');const entries=[...m.routes.map(r=>({label:`Dag ${r.day} · ${r.from} → ${r.to}`,color:DAY_COLORS[(r.day-1)%DAY_COLORS.length]})),{label:`POI's (${m.pois.length})`,color:'#d67b30'},{label:`Ruststops (${m.rests.length})`,color:'#3b72a8'},{label:`Accommodatie (${m.nights.length})`,color:'#123f3a'}];container.innerHTML=`<svg viewBox="${f.x} ${f.y} ${f.width} ${f.height}" style="width:100%;height:300px">${tiles(f,liveBasemap)}${routes}${markers}</svg>${svgLegend(entries)}`;return{rendered:true,interactive:false,routeDays:m.routes.length,pois:m.pois.length,rests:m.rests.length,nights:m.nights.length}}
function svgDiscovery(container,origin,candidates,{liveBasemap=true}={}){const rows=(candidates||[]).filter(c=>validCoordinate(c.anchor)),f=frame([origin,...rows.map(c=>c.anchor)]);if(!f){container.textContent='Geen kaartgeometrie';return{rendered:false}}const oq=f.xy(origin),spokes=rows.map(c=>{const q=f.xy(c.anchor),color=DAY_COLORS[(c.rank-1)%DAY_COLORS.length];return`<line x1="${oq.x}" y1="${oq.y}" x2="${q.x}" y2="${q.y}" stroke="${color}" stroke-width="2" stroke-dasharray="7 7"/><circle cx="${q.x}" cy="${q.y}" r="11" fill="${color}"><title>#${c.rank} ${esc(c.name)} · ${c.score}/100</title></circle>`}).join('');container.innerHTML=`<svg viewBox="${f.x} ${f.y} ${f.width} ${f.height}" style="width:100%;height:320px">${tiles(f,liveBasemap)}${spokes}</svg>${svgLegend(rows.map(c=>({label:`#${c.rank} ${c.name}`,color:DAY_COLORS[(c.rank-1)%DAY_COLORS.length]})))}`;return{rendered:true,interactive:false,options:rows.length}}

export function renderMap(container,plan,options={}){return leafletReady(container)?renderLeafletPlan(container,plan,options):svgPlan(container,plan,options)}
export function renderDestinationComparisonMap(container,origin,candidates=[],options={}){return leafletReady(container)?renderLeafletDiscovery(container,origin,candidates,options):svgDiscovery(container,origin,candidates,options)}
export function invalidateMap(container){const map=container?instances.get(container):null;if(map)setTimeout(()=>map.invalidateSize(),40)}
