import { validCoordinate } from './config.js';
export function buildMapModel(plan){const routes=(plan.days||[]).map(d=>({day:d.day,kind:d.kind,geometry:(d.geometry||[]).filter(validCoordinate)}));const pois=(plan.offlinePois||[]).filter(validCoordinate);const nights=(plan.overnights||[]).map(n=>({night:n.night,state:n.state,point:n.state==='SPECIFIC_LIVE_ACCOMMODATION'?n.property:n.zone})).filter(x=>validCoordinate(x.point));return{routes,pois,nights,origin:plan.origin,destinationId:plan.destinationId}}
export function mapConsistency(plan,model=buildMapModel(plan)){return{valid:model.routes.length===plan.days.length&&model.routes.every(r=>r.geometry.length>=1)&&model.nights.length===plan.overnights.length&&model.pois.length>0,routeDays:model.routes.length,nights:model.nights.length,pois:model.pois.length}}
function bounds(points){let minLat=90,maxLat=-90,minLon=180,maxLon=-180;for(const p of points){if(!validCoordinate(p))continue;minLat=Math.min(minLat,p.lat);maxLat=Math.max(maxLat,p.lat);minLon=Math.min(minLon,p.lon);maxLon=Math.max(maxLon,p.lon)}if(minLat===90)return null;return{minLat,maxLat,minLon,maxLon}}
function projector(points,{W=900,H=480,pad=28}={}){const b=bounds(points);if(!b)return null;const dx=Math.max(.01,b.maxLon-b.minLon),dy=Math.max(.01,b.maxLat-b.minLat);return{W,H,xy:p=>[pad+(p.lon-b.minLon)/dx*(W-pad*2),H-pad-(p.lat-b.minLat)/dy*(H-pad*2)]}}
export function renderMap(container,plan){const m=buildMapModel(plan),all=[plan.origin,...m.routes.flatMap(r=>r.geometry),...m.pois,...m.nights.map(n=>n.point)],pr=projector(all);if(!pr){container.textContent='Geen kaartgeometrie';return}const {W,H,xy}=pr;const lines=m.routes.map(r=>`<polyline points="${r.geometry.map(p=>xy(p).join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="3" opacity=".62"/><text x="${xy(r.geometry[Math.floor(r.geometry.length/2)])[0]}" y="${xy(r.geometry[Math.floor(r.geometry.length/2)])[1]}" font-size="12">D${r.day}</text>`).join('');const poi=m.pois.map(p=>{const [x,y]=xy(p);return`<circle cx="${x}" cy="${y}" r="5"/><title>${p.name}</title>`}).join('');const night=m.nights.map(n=>{const [x,y]=xy(n.point);return`<rect x="${x-5}" y="${y-5}" width="10" height="10" rx="2"/><title>Nacht ${n.night}: ${n.point.name||''}</title>`}).join('');container.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Offline kaart van ${plan.destinationName}">${lines}${poi}${night}</svg>`}

export function renderDestinationComparisonMap(container,origin,candidates=[]){
  const rows=(candidates||[]).filter(x=>validCoordinate(x.anchor));const points=[origin,...rows.map(x=>x.anchor)].filter(validCoordinate),pr=projector(points,{W:900,H:520,pad:52});if(!pr){container.textContent='Geen kaartgeometrie voor voorstellen';return}
  const {W,H,xy}=pr,[ox,oy]=xy(origin);const spokes=rows.map(r=>{const [x,y]=xy(r.anchor);return`<line x1="${ox}" y1="${oy}" x2="${x}" y2="${y}" class="discovery-spoke"/>`}).join('');
  const pins=rows.map(r=>{const [x,y]=xy(r.anchor),labelX=x>W*.72?x-12:x+12,anchor=x>W*.72?'end':'start';return`<g class="discovery-pin" data-rank="${r.rank}"><circle cx="${x}" cy="${y}" r="14"/><text x="${x}" y="${y+4}" text-anchor="middle" class="pin-number">${r.rank}</text><text x="${labelX}" y="${y-8}" text-anchor="${anchor}" class="pin-label">${String(r.name||'')}</text><text x="${labelX}" y="${y+9}" text-anchor="${anchor}" class="pin-sub">${String(r.country||'')} · ${Math.round(r.totalDistanceKm||r.roughDistanceKm||0)} km</text><title>#${r.rank} ${r.name} · ${r.score}/100</title></g>`}).join('');
  container.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Vergelijkingskaart van ${rows.length} reisvoorstellen"><g class="discovery-map-grid"><line x1="0" y1="${H*.5}" x2="${W}" y2="${H*.5}"/><line x1="${W*.5}" y1="0" x2="${W*.5}" y2="${H}"/></g>${spokes}<g class="origin-pin"><circle cx="${ox}" cy="${oy}" r="10"/><text x="${ox+14}" y="${oy+4}">${String(origin.name||'Vertrek')}</text></g>${pins}</svg>`;
}
