import { rankDestinationGroups } from './destination-engine.js';
import { preferenceBonus } from './preference-engine.js';

const clamp01=value=>Math.max(0,Math.min(1,value));
const band=(value,size)=>Math.floor(Number(value||0)/size);
const overlap=(left=[],right=[])=>{const a=new Set(left),b=new Set(right),union=new Set([...a,...b]);return union.size?[...a].filter(item=>b.has(item)).length/union.size:0};
const focusProfiles=Object.freeze({balanced:{label:'Beste mix',keys:[]},closer:{label:'Dichterbij',keys:['driving']},cheaper:{label:'Voordeliger',keys:['budget']},surprising:{label:'Meer verrassend',keys:['crowds','scenery']},family:{label:'Gezinsvriendelijk',keys:['family']},scenic:{label:'Mooiste route',keys:['scenery','motorcycle']}});
function primaryStyle(item,trip){if(trip.transport==='motorcycle'&&item.motorcycle>=8)return['Beste motorroute','Sterke motor-match binnen je roadtripbereik'];if(['motorhome','caravan'].includes(trip.transport)&&item.camper>=8)return['Beste voor camper','Voertuigmatch en haalbare dagafstanden'];if(trip.children&&item.family>=9)return['Beste voor gezinnen','Gezinsmatch en haalbare dagafstanden'];if(item.distanceKm<=400)return['Makkelijkste reis','Weinig aanreisbelasting'];if(item.tags.includes('budget'))return['Beste prijs-kwaliteit','Sterke inhoudelijke match zonder onnodig budget'];return['Beste totaalbalans','Voorkeuren, route en haalbaarheid in balans']}
function focusBonus(item,focus){if(focus==='closer')return Math.max(0,12-item.distanceKm/90);if(focus==='cheaper')return Math.max(0,(100-item.dimensions.budget)*-.04+6);if(focus==='surprising')return(item.crowds||5)*.45;if(focus==='family')return(item.dimensions.family||50)*.06;if(focus==='scenic')return(item.dimensions.scenery||50)*.05+(item.dimensions.motorcycle||50)*.02;return 0}
function proposalFromDestination(item,trip,focus,learnedProfile=null){const[label,labelReason]=primaryStyle(item,trip),learned=preferenceBonus(item,learnedProfile),bases=item.bases?.length||1,recommendedBases=Math.max(1,Math.min(bases,trip.maxChanges<=2?1:trip.days>=10?3:2));return{...item,proposalId:item.id,destinationId:item.id,proposalLabel:label,labelReason,focusLabel:focusProfiles[focus]?.label||focusProfiles.balanced.label,portfolioScore:item.score+focusBonus(item,focus)+learned.score,learnedPreferenceReasons:learned.reasons,recommendedBases,routeCharacter:trip.routeStyle==='scenic'?'toeristische roadtrip met uitzichtstops':trip.routeStyle==='fastest'?'efficiënte roadtrip':'gebalanceerde roadtrip',tripShape:`${recommendedBases} uitvalsbasis${recommendedBases===1?'':'sen'} · ${trip.days} dagen · ${item.constraintStatus.travelLegs*2} reisetappes`,keyTradeoff:item.compromises?.[0]||'Geen harde overschrijding.',evidence:[`${item.dynamic?'Live ontdekt':'Offline regioprofiel'} met ${item.bases.length} geankerde bases`,`Voorkeursmatch ${Math.round((item.preferenceCoverage||0)*100)}%`,`Voertuigscore ${item.dimensions.transport}/100`],sourceLabel:item.dynamic?'Live ontdekt via OpenStreetMap binnen roadtripbereik':'ReisSlim offline regiocatalogus, hard gefilterd op roadtripbereik'}}
export function proposalDifference(left,right){if(!left||!right||left.destinationId===right.destinationId)return 0;const geography=left.country===right.country?.42:1,distance=Math.min(1,Math.abs(left.distanceKm-right.distanceKm)/600),cost=Math.min(1,Math.abs(left.estimate-right.estimate)/1600),tags=1-overlap(left.tags,right.tags),baseShape=left.recommendedBases===right.recommendedBases?.25:1;return clamp01(geography*.27+distance*.20+cost*.13+tags*.30+baseShape*.10)}
export function nearDuplicate(left,right){return Boolean(left&&right&&(left.destinationId===right.destinationId||(band(left.distanceKm,90)===band(right.distanceKm,90)&&band(left.estimate,400)===band(right.estimate,400)&&overlap(left.tags,right.tags)>=.86&&left.country===right.country)))}
function diversityPenalty(candidate,selected){const sameCountry=selected.filter(item=>item.country===candidate.country).length,sameDistance=selected.filter(item=>band(item.distanceKm,350)===band(candidate.distanceKm,350)).length;return sameCountry*2+sameDistance*.8}
export function selectDiversePortfolio(candidates,{limit=20,excludedIds=[]}={}){const excluded=new Set(excludedIds),pool=candidates.filter(item=>!excluded.has(item.id)&&!excluded.has(item.proposalId)),selected=[];while(pool.length&&selected.length<limit){const ranked=pool.map(candidate=>{const minDifference=selected.length?Math.min(...selected.map(existing=>proposalDifference(candidate,existing))):1,duplicatePenalty=selected.some(existing=>nearDuplicate(candidate,existing))?25:0,spreadPenalty=diversityPenalty(candidate,selected);return{candidate,merit:candidate.portfolioScore*.84+minDifference*16-duplicatePenalty-spreadPenalty}}).sort((a,b)=>b.merit-a.merit||b.candidate.preferenceCoverage-a.candidate.preferenceCoverage||b.candidate.score-a.candidate.score);const winner=ranked[0].candidate;selected.push(winner);pool.splice(pool.indexOf(winner),1)}return selected}
export function buildProposalPortfolio(trip,catalog,{limit=8,focus='balanced',excludedIds=[],preferenceProfile=null}={}){const ranking=rankDestinationGroups(trip,catalog),requestedMismatch=ranking.rejected.find(item=>item.intentMatch)||null,candidates=[...ranking.exact,...ranking.stretched].map(item=>proposalFromDestination(item,trip,focus,preferenceProfile)),portfolioLimit=Math.max(20,Math.min(30,Number(limit||8)*3)),visible=selectDiversePortfolio(candidates,{limit:portfolioLimit,excludedIds}),exact=visible.filter(item=>item.category==='exact'),stretched=visible.filter(item=>item.category==='stretch').slice(0,4),accepted=[...exact,...stretched];return{...ranking,exact:accepted.filter(item=>item.category==='exact'),stretched:accepted.filter(item=>item.category==='stretch'),visible:accepted,candidates,shortage:accepted.length>=12?null:{requested:12,available:accepted.length,explanation:`Er zijn ${accepted.length} haalbare roadtripopties binnen de huidige voorwaarden.`,relaxations:ranking.closestAdjustments.slice(0,5)},requestedMismatch,focus,focusOptions:focusProfiles}}
export function getMoreProposals(trip,catalog,shownIds,{limit=4,focus='balanced',preferenceProfile=null}={}){return buildProposalPortfolio(trip,catalog,{limit:Math.max(12,limit),focus,excludedIds:shownIds,preferenceProfile}).visible.slice(0,limit)}
