import { validCoordinate } from './config.js';
import { transportId } from './vehicle-intelligence.js';
const rules={
car:{accommodation:'Specifiek verblijf wordt live gezocht',stop:'Specifieke ruststop wordt live gezocht',restaurant:'Specifieke eetstop wordt live gezocht',activity:'Specifieke activiteit wordt live gezocht',service:'Specifieke voertuigservice wordt live gezocht'},
motorcycle:{accommodation:'Specifiek motorvriendelijk verblijf wordt live gezocht',stop:'Specifieke motorstop wordt live gezocht',restaurant:'Specifieke lunch/eetstop wordt live gezocht',activity:'Specifieke stop langs een mooie motorroute wordt live gezocht',service:'Specifiek tankstation wordt live gezocht'},
motorhome:{accommodation:'Specifieke camperplaats/camping wordt live gezocht',stop:'Specifieke camperstop wordt live gezocht',restaurant:'Specifieke eetstop met ruime parking wordt live gezocht',activity:'Specifieke campergeschikte activiteit wordt live gezocht',service:'Specifieke camperservice wordt live gezocht'},
caravan:{accommodation:'Specifieke caravancamping wordt live gezocht',stop:'Specifieke doorrijdbare rustplaats wordt live gezocht',restaurant:'Specifieke eetstop met trailerparking wordt live gezocht',activity:'Specifieke bereikbare activiteit wordt live gezocht',service:'Specifiek servicepunt wordt live gezocht'}};
function offsetPoint(point,seed=0){if(!validCoordinate(point))return null;const offset=((seed%3)-1)*.006;return{lat:Number((point.lat+offset).toFixed(5)),lon:Number((point.lon-offset).toFixed(5))}}
function midpoint(day){const points=[day.fromPoint,...(day.waypoints||[]),day.toPoint].filter(validCoordinate);if(!points.length)return day.toPoint||day.fromPoint;return points[Math.floor(points.length/2)]}
function proposal({day,type,name,reason,point,transport,seed=0,meal=null}){return{id:`day-${day}-${type}-${seed}`,day,type,name,reason,point:offsetPoint(point,seed),vehicleFit:[transport],confidence:'pending-live-place',verified:false,source:'ReisSlim zoekt live naam',detourKm:null,openingHours:null,url:null,lastChecked:null,genericFallback:true,meal}}
export function buildRecommendations(trip,destination,days){const transport=transportId(trip.transport),rule=rules[transport],all=[];for(const day of days){const recommendations=[],isTravel=['outward','return','transfer'].includes(day.kind),isHomecoming=day.kind==='return'&&day.to===trip.origin,anchor=day.toPoint||day.fromPoint||destination.bases[0];
 for(const[index,waypoint]of(day.waypoints||[]).entries())recommendations.push(proposal({day:day.day,type:waypoint.role==='fuel'?'fuel':'rest',name:rule.stop,reason:waypoint.role==='fuel'?`Zoek een concreet tank-/rustpunt rond de actieradius van ${trip.fuelRangeKm} km.`:'Zoek een concrete pauzeplaats op dit routepunt.',point:waypoint,transport,seed:index}));
 if(isTravel&&!isHomecoming)recommendations.push(proposal({day:day.day,type:'restaurant',name:rule.restaurant,reason:'Lunchstop: kies een specifieke, goed bereikbare eetgelegenheid dicht bij de route en rond het midden van de reisdag.',point:midpoint(day),transport,seed:20,meal:'lunch'}));
 if(!isHomecoming){recommendations.push(proposal({day:day.day,type:'accommodation',name:rule.accommodation,reason:'Kies een specifiek genoemd verblijf zo dicht mogelijk bij de geplande overnachtingsbasis, met voertuiggeschikte toegang.',point:anchor,transport,seed:4}));
 if(!isTravel)recommendations.push(proposal({day:day.day,type:'restaurant',name:rule.restaurant,reason:'Kies een concreet genoemd restaurant bij de uitvalsbasis.',point:anchor,transport,seed:5,meal:'dinner'}))}
 if(!isTravel)recommendations.push(proposal({day:day.day,type:'activity',name:rule.activity,reason:'Kies een specifieke locatie die aansluit bij de geselecteerde voorkeuren.',point:anchor,transport,seed:6}));
 if(['motorhome','caravan'].includes(transport)&&!isHomecoming)recommendations.push(proposal({day:day.day,type:'service',name:rule.service,reason:'Zoek een concreet servicepunt met geschikte voertuigtoegang.',point:anchor,transport,seed:7}));
 day.recommendations=recommendations;day.sleepProposal=recommendations.find(item=>item.type==='accommodation')||null;all.push(...recommendations)}return all}
export function collectRecommendationPoints(plan){return(plan?.recommendations||[]).filter(item=>validCoordinate(item.point)&&item.live).map(item=>({...item.point,...item,role:item.type}))}
