import test from 'node:test';import assert from 'node:assert/strict';import {enums,inputLimits} from './config.js';import {normalizeTripInput,validateInputBounds,createCanonicalPlan} from './canonical-plan-engine.js';import {loadData,regionByQuery,trip} from './test-helpers.mjs';
const {client}=loadData();
const base=trip({budget:10000,maxDrive:10,maxChanges:20,fuelRangeKm:800});
for(const [field,lim] of Object.entries(inputLimits)){
  const values=[lim.min,lim.min+lim.step,(lim.min+(lim.max??lim.min+10))/2];if(lim.max!=null)values.push(lim.max-lim.step,lim.max);
  test(`input boundary accepted: ${field}`,()=>{for(const v of values){const t=normalizeTripInput({...base,[field]:v});const e=validateInputBounds(t).filter(x=>x.field===field);assert.equal(e.length,0,`${field} ${v}`)}});
  test(`input below minimum rejected: ${field}`,()=>{const v=lim.min-lim.step,t=normalizeTripInput({...base,[field]:v}),e=validateInputBounds(t).find(x=>x.field===field);assert.ok(e);assert.match(e.code,/BELOW_MIN/)});
  if(lim.max!=null)test(`input above maximum rejected: ${field}`,()=>{const v=lim.max+lim.step,t=normalizeTripInput({...base,[field]:v}),e=validateInputBounds(t).find(x=>x.field===field);assert.ok(e);assert.match(e.code,/ABOVE_MAX/)});
}
for(const [field,values] of Object.entries(enums))test(`all enum values accepted: ${field}`,()=>{for(const v of values){const t=normalizeTripInput({...base,[field]:v});assert.equal(validateInputBounds(t).some(e=>e.field===field),false,`${field}:${v}`)}});

test('invalid enum rejected',()=>{const t=normalizeTripInput({...base,transport:'spaceship'});assert.equal(t.transport,'car')});
test('date month/year boundaries remain day-sequential',async()=>{const d=await regionByQuery(client,'Harz');for(const startDate of ['2026-12-31','2028-02-28','2028-02-29']){const r=createCanonicalPlan(trip({startDate,days:5,budget:10000,maxDrive:10}),d,client);assert.equal(r.ok,true);assert.equal(r.plan.days.length,5);assert.equal(new Set(r.plan.days.map(x=>x.date)).size,5)}});
test('coupled long distance + too few days gives exact diagnostic',async()=>{const d=await regionByQuery(client,'Spanish Pyrenees'),r=createCanonicalPlan(trip({days:2,maxDrive:2,budget:100000,maxChanges:20}),d,client);assert.equal(r.ok,false);assert.ok(['MAX_DRIVE_TRANSIT_GAP','INSUFFICIENT_DAYS_FOR_DISTANCE'].includes(r.failure.code));assert.ok(r.failure.possibleSolutions.length)});
test('minimum fuel range rejects remote Namibia with fuel diagnostic',async()=>{const d=await regionByQuery(client,'Fish River Canyon'),r=createCanonicalPlan(trip({origin:'Windhoek',days:14,transport:'car',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:100}),d,client);assert.equal(r.ok,false);assert.equal(r.failure.code,'FUEL_RANGE_REGION')});
test('maximum fuel range accepts remote Namibia',async()=>{const d=await regionByQuery(client,'Fish River Canyon'),r=createCanonicalPlan(trip({origin:'Windhoek',days:14,transport:'car',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:1500}),d,client);assert.equal(r.ok,true)});
test('island destination Malta generates canonical multimodal plan',async()=>{const d=await regionByQuery(client,'Valletta & Three Cities'),r=createCanonicalPlan(trip({origin:'Paris',days:24,transport:'car',routeTopology:'open-ended',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:800}),d,client);assert.equal(r.ok,true,r.failure&&JSON.stringify(r.failure));assert.ok(r.plan.days.some(x=>x.transportMode==='ferry'))});
test('island destination Cyprus generates canonical multimodal plan',async()=>{const d=await regionByQuery(client,'Troodos Mountains'),r=createCanonicalPlan(trip({origin:'Vienna',days:24,transport:'car',routeTopology:'open-ended',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:800}),d,client);assert.equal(r.ok,true,r.failure&&JSON.stringify(r.failure));assert.ok(r.plan.days.some(x=>x.transportMode==='ferry'))});

test('all preference categories and priority weights 0-3 normalize without corrupting input bounds',()=>{for(const key of ['natuur','bergen','zwemmen','wandelen','kinderen','motor','cultuur','eten','kust','budget'])for(const weight of [0,1,2,3]){const t=normalizeTripInput({...base,preferences:weight?[key]:[],preferenceWeights:{[key]:weight}});assert.equal(validateInputBounds(t).length,0);assert.equal(t.preferenceWeights[key],weight)}});
test('geographic coordinate origin extremes accepted when valid and rejected when unresolved',async()=>{const d=await regionByQuery(client,'Harz');const ok=createCanonicalPlan(trip({origin:'89, 0',days:60,maxDrive:10,maxChanges:20,budget:100000,routeTopology:'open-ended',transport:'car',fuelRangeKm:1500}),d,client);assert.ok(ok.ok||ok.failure?.code,'extreme valid coordinate must produce deterministic result or exact constraint diagnostic');const bad=createCanonicalPlan(trip({origin:'not-a-real-offline-origin',days:5}),d,client);assert.equal(bad.ok,false);assert.equal(bad.failure.code,'ORIGIN_NOT_IN_OFFLINE_CATALOG')});
