import test from 'node:test';import assert from 'node:assert/strict';import {createCanonicalPlan} from './canonical-plan-engine.js';import {validateCanonicalPlan} from './validator.js';import {runEnrichmentPipeline,enrichRouting,enrichAccommodations,enrichPois} from './enrichment.js';import {buildGpx,gpxConsistency} from './gpx-generator.js';import {serializeTrip,deserializeTrip} from './storage.js';import {loadData,regionByQuery,trip} from './test-helpers.mjs';
const {client}=loadData();
async function basePlan(){const d=await regionByQuery(client,'Harz'),r=createCanonicalPlan(trip({budget:10000}),d,client);assert.equal(r.ok,true);return r.plan}
const healthy={
 routing:async day=>({distanceKm:Math.max(1,day.distanceKm*.96),roadHours:Math.max(.1,day.roadHours*.96),driveHours:Math.max(.1,day.driveHours*.96),elapsedHours:Math.max(.1,day.elapsedHours*.96),geometry:[day.fromPoint,...(day.geometry||[]).slice(1,-1),day.toPoint]}),
 pois:async plan=>{const p=plan.offlinePois[0];return[{id:'live-poi-1',name:`Live verified near ${p.name}`,lat:p.lat+.001,lon:p.lon+.001,type:'viewpoint',source:'controlled'}]},
 accommodation:async night=>({name:`Verified stay ${night.night}`,lat:night.zone.lat+.001,lon:night.zone.lon+.001,source:'controlled'}),
 weather:async()=>({daily:{temperature_2m_max:[20],precipitation_probability_max:[10]}}),
 images:async plan=>({url:'https://example.invalid/harz.jpg',verifiedEntityId:plan.destinationId,source:'controlled'})
};
const outage=Object.fromEntries(Object.keys(healthy).map(k=>[k,async()=>{throw new Error('provider unavailable')}]))

test('A all live services healthy enrich without restructuring',async()=>{const p=await basePlan(),sig=p.canonicalSignature,out=await runEnrichmentPipeline(p,healthy);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.canonicalSignature,sig);assert.ok(out.offlinePois.some(x=>x.id==='live-poi-1'));assert.ok(out.overnights.every(n=>n.state==='SPECIFIC_LIVE_ACCOMMODATION'));assert.equal(out.enrichment.weather,'live');assert.equal(out.enrichment.images,'live-verified')});
test('B routing unavailable preserves every day and estimate',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{...healthy,routing:outage.routing});assert.equal(out.days.length,p.days.length);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.routing.status,'estimated')});
test('C POI providers unavailable retain offline POIs',async()=>{const p=await basePlan(),ids=p.offlinePois.map(x=>x.id),out=await runEnrichmentPipeline(p,{pois:outage.pois});assert.deepEqual(ids,out.offlinePois.map(x=>x.id));assert.equal(out.enrichment.pois,'offline-only')});
test('D accommodation unavailable leaves every night as planned zone',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{accommodation:outage.accommodation});assert.equal(out.overnights.length,p.overnights.length);assert.ok(out.overnights.every(n=>n.state==='PLANNED_ACCOMMODATION_ZONE'))});
test('E weather unavailable does not affect validity',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{weather:outage.weather});assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.enrichment.weather,'unavailable')});
test('F image provider unavailable uses placeholder identity',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{images:outage.images});assert.equal(validateCanonicalPlan(out).valid,true);assert.ok(out.images[0].placeholder)});
test('G all non-routing services unavailable while routing may enrich',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{routing:healthy.routing,pois:outage.pois,accommodation:outage.accommodation,weather:outage.weather,images:outage.images});assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.length,p.days.length);assert.equal(out.overnights.length,p.overnights.length)});
test('H ALL live services unavailable still has days, POIs, nights, GPX',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,outage),g=buildGpx(out);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.length,5);assert.equal(out.overnights.length,4);assert.ok(out.offlinePois.length);assert.equal(gpxConsistency(out,g).valid,true)});
test('I partial API responses add valid POI and ignore malformed',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{pois:async plan=>[{id:'good',name:'Good live POI',lat:plan.offlinePois[0].lat,lon:plan.offlinePois[0].lon+.01},{id:'bad',name:'Bad',lat:'x',lon:null}]});assert.ok(out.offlinePois.some(x=>x.id==='good'));assert.equal(out.offlinePois.some(x=>x.id==='bad'),false);assert.equal(validateCanonicalPlan(out).valid,true)});
test('J timeout errors are treated as unavailable enrichment',async()=>{const timeoutProvider=async()=>{const e=new Error('timeout');e.name='TimeoutError';throw e};const p=await basePlan(),out=await runEnrichmentPipeline(p,{routing:timeoutProvider,pois:timeoutProvider,accommodation:timeoutProvider,weather:timeoutProvider,images:timeoutProvider});assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.length,p.days.length)});
test('K malformed accommodation data cannot delete or corrupt nights',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{accommodation:async()=>({name:'Malformed',lat:999,lon:999})});assert.equal(out.overnights.length,4);assert.ok(out.overnights.every(n=>n.state==='PLANNED_ACCOMMODATION_ZONE'));assert.equal(validateCanonicalPlan(out).valid,true)});
test('L live routing conflicting with canonical endpoints is discarded',async()=>{const p=await basePlan(),sig=p.canonicalSignature,out=await runEnrichmentPipeline(p,{routing:async day=>({distanceKm:1,driveHours:.1,roadHours:.1,elapsedHours:.1,geometry:[day.fromPoint,{lat:0,lon:0}]})});assert.equal(out.canonicalSignature,sig);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.some(d=>d.routeSource==='live-routing'),false)});
test('M only some nights get live accommodation',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,{accommodation:async n=>n.night%2?healthy.accommodation(n):null});assert.ok(out.overnights.some(n=>n.state==='SPECIFIC_LIVE_ACCOMMODATION'));assert.ok(out.overnights.some(n=>n.state==='PLANNED_ACCOMMODATION_ZONE'));assert.equal(out.overnights.length,4)});
test('N only some days/live POIs enrich without deleting offline',async()=>{const p=await basePlan(),before=p.offlinePois.length,out=await runEnrichmentPipeline(p,{pois:healthy.pois});assert.ok(out.offlinePois.length>before);assert.ok(p.offlinePois.every(x=>out.offlinePois.some(y=>y.id===x.id)))});
test('P fully enriched plan restores valid',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,healthy),restored=deserializeTrip(serializeTrip(out));assert.equal(validateCanonicalPlan(restored).valid,true);assert.ok(restored.overnights.every(n=>n.state==='SPECIFIC_LIVE_ACCOMMODATION'))});
test('S GPX after live enrichment is consistent',async()=>{const p=await basePlan(),out=await runEnrichmentPipeline(p,healthy),g=buildGpx(out);assert.equal(gpxConsistency(out,g).valid,true)});
