import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {EU27} from './config.js';import {createCanonicalPlan} from './canonical-plan-engine.js';import {validateCanonicalPlan} from './validator.js';import {runEnrichmentPipeline} from './enrichment.js';import {loadData,trip,root} from './test-helpers.mjs';
const {client,countries,index}=loadData();
const outage={routing:async()=>{throw new Error('offline')},pois:async()=>{throw new Error('offline')},accommodation:async()=>{throw new Error('offline')},weather:async()=>{throw new Error('offline')},images:async()=>{throw new Error('offline')}};
const matrix=[];
for(const code of EU27)test(`EU offline coverage ${code}`,async()=>{const c=countries[code],d=c.regions[0],origin=d.bases[0].name;const t=trip({origin,destinationQuery:d.name,days:5,transport:'car',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:1500,liveData:false});const r=createCanonicalPlan(t,d,client);assert.equal(r.ok,true,r.failure&&JSON.stringify(r.failure));assert.equal(validateCanonicalPlan(r.plan).valid,true);const out=await runEnrichmentPipeline(r.plan,outage);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.length,5);assert.equal(out.overnights.length,4);assert.ok(out.offlinePois.length>=2);matrix.push({country:code,regions:c.regions.length,pois:c.regions.reduce((s,x)=>s+x.pois.length,0),scenicAnchors:c.regions.reduce((s,x)=>s+x.scenicAnchors.length,0),accommodationZones:c.regions.reduce((s,x)=>s+x.accommodationZones.length,0),offlineTrip:'PASS',providerOutage:'PASS',result:'PASS'})});

test('write EU coverage matrix',()=>{matrix.sort((a,b)=>a.country.localeCompare(b.country));assert.equal(matrix.length,27);fs.writeFileSync(path.join(root,'report-eu-coverage-matrix.json'),JSON.stringify(matrix,null,2))});
const origins=['Amsterdam','Berlin','Paris','Madrid','Rome','Warsaw','Stockholm','Vienna','Bucharest','Dublin','Athens'];
test('EU cross-border origins distributed across all 27 destinations',async()=>{for(let i=0;i<EU27.length;i++){const code=EU27[i],d=countries[code].regions[0],origin=origins[i%origins.length];const r=createCanonicalPlan(trip({origin,destinationQuery:d.name,days:24,transport:'car',tripStructure:'base',routeTopology:'open-ended',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:1500}),d,client);assert.equal(r.ok,true,`${origin}->${code}: ${r.failure&&JSON.stringify(r.failure)}`);assert.equal(validateCanonicalPlan(r.plan).valid,true,`${origin}->${code}`)}});

const saCases=[['Cape Town','Garden Route'],['Cape Town','Cederberg'],['Cape Town','Cape Winelands'],['Cape Town','Overberg'],['Johannesburg','Northern Drakensberg'],['Pretoria','Kruger & Lowveld'],['Durban','KwaZulu-Natal Midlands'],['Gqeberha','Addo Region']];
test('South Africa distributed offline origins/destinations',async()=>{for(const [origin,q] of saCases){const d=countries.ZA.regions.find(r=>r.name===q),r=createCanonicalPlan(trip({origin,destinationQuery:q,days:10,transport:'car',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:900}),d,client);assert.equal(r.ok,true,`${origin}->${q}: ${r.failure&&JSON.stringify(r.failure)}`);assert.equal(validateCanonicalPlan(r.plan).valid,true)}});
test('Cape Town 5 and 10 day provider-outage plans',async()=>{for(const days of [5,10]){const d=countries.ZA.regions.find(r=>r.name==='Cape Peninsula'),r=createCanonicalPlan(trip({origin:'Cape Town',destinationQuery:d.name,days,transport:'car',maxDrive:8,maxChanges:10,budget:30000,fuelRangeKm:800}),d,client);assert.equal(r.ok,true);const out=await runEnrichmentPipeline(r.plan,outage);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.days.length,days)}});
const naQueries=['Windhoek','Sossusvlei & Sesriem','Swakopmund','Etosha','Damaraland','Fish River Canyon','Zambezi Region'];
test('Namibia explicit offline roadtrips',async()=>{for(const q of naQueries){const d=countries.NA.regions.find(r=>r.name===q),r=createCanonicalPlan(trip({origin:'Windhoek',destinationQuery:q,days:18,transport:'car',maxDrive:10,maxChanges:20,budget:100000,fuelRangeKm:500}),d,client);assert.equal(r.ok,true,`${q}: ${r.failure&&JSON.stringify(r.failure)}`);assert.equal(validateCanonicalPlan(r.plan).valid,true);assert.ok(r.plan.datasetRegionSnapshot.fuelGapKm>0)}});
test('Namibia complete provider outage remains coherent',async()=>{const d=countries.NA.regions.find(r=>r.name==='Damaraland'),r=createCanonicalPlan(trip({origin:'Windhoek',destinationQuery:d.name,days:10,transport:'car',maxDrive:10,maxChanges:20,budget:40000,fuelRangeKm:500}),d,client);assert.equal(r.ok,true);const out=await runEnrichmentPipeline(r.plan,outage);assert.equal(validateCanonicalPlan(out).valid,true);assert.equal(out.overnights.length,9);assert.ok(out.offlinePois.length>=2)});
