import test from 'node:test';import assert from 'node:assert/strict';import {createCanonicalPlan} from './canonical-plan-engine.js';import {validateCanonicalPlan} from './validator.js';import {buildGpx,gpxConsistency} from './gpx-generator.js';import {buildMapModel,mapConsistency} from './map-view.js';import {MemoryStorage,serializeTrip,deserializeTrip} from './storage.js';import {loadData,regionByQuery,trip} from './test-helpers.mjs';
const {client}=loadData();
async function build(q,t){const d=await regionByQuery(client,q);const r=createCanonicalPlan({...t,destinationQuery:q},d,client);assert.equal(r.ok,true,r.failure&&JSON.stringify(r.failure));const v=validateCanonicalPlan(r.plan);assert.equal(v.valid,true,JSON.stringify(v.errors));return r.plan}

test('CASE A Saasveld Harz 5d motorcycle base 5h max5 offline',async()=>{const p=await build('Harz',trip());assert.equal(p.days.length,5);assert.equal(p.overnights.length,4);assert.ok(p.days.some(d=>d.canonicalRegionId===p.destinationId));assert.ok(p.offlinePois.some(x=>/Torfhaus|Goslar|Brocken|Oderteich|Rappbode/i.test(x.name)));for(const d of p.days)assert.ok(d.driveHours<=5.05);assert.ok(p.accommodationChanges<=5);const loops=p.days.filter(d=>d.kind==='daytrip');assert.ok(loops.length>=1);for(const d of loops){assert.equal(d.fromPoint.id,d.toPoint.id);assert.ok(d.geometry.some(x=>x.id!==d.fromPoint.id))}});
test('CASE B Saasveld Harz 5d moving',async()=>{const p=await build('Harz',trip({tripStructure:'moving'}));assert.equal(p.days.length,5);assert.ok(p.accommodationChanges<=5)});
test('CASE C Saasveld Dinant motorcycle',async()=>{const p=await build('Ardennes & Meuse',trip({destinationQuery:'Dinant',days:4}));assert.equal(p.destinationCountryCode,'BE')});
test('CASE D Cape Town 5-day roadtrip',async()=>{const p=await build('Cape Peninsula',trip({origin:'Cape Town',days:5,transport:'car',tripStructure:'moving',fuelRangeKm:600}));assert.equal(p.days.length,5)});
test('CASE E Cape Town 10-day roadtrip',async()=>{const p=await build('Garden Route',trip({origin:'Cape Town',days:10,transport:'car',tripStructure:'moving',fuelRangeKm:600,budget:12000,maxChanges:8,maxDrive:6}));assert.equal(p.days.length,10)});
test('CASE F Namibia 5-day from Windhoek',async()=>{const p=await build('Sossusvlei & Sesriem',trip({origin:'Windhoek',days:5,transport:'car',tripStructure:'base',fuelRangeKm:400,budget:9000,maxDrive:7,maxChanges:5}));assert.equal(p.days.length,5)});
test('CASE G Namibia 10-day from Windhoek',async()=>{const p=await build('Etosha',trip({origin:'Windhoek',days:10,transport:'car',tripStructure:'moving',fuelRangeKm:500,budget:15000,maxDrive:7,maxChanges:8}));assert.equal(p.days.length,10)});
test('CASE H 1-day minimum trip',async()=>{const p=await build('Veluwe',trip({origin:'Saasveld',days:1,transport:'car',maxDrive:6,budget:2000}));assert.equal(p.days.length,1);assert.equal(p.overnights.length,0)});
test('CASE I 60-day maximum trip',async()=>{const p=await build('Harz',trip({days:60,budget:100000,maxDrive:10,maxChanges:20,tripStructure:'base'}));assert.equal(p.days.length,60);assert.equal(p.overnights.length,59)});
test('CASE J base destination requiring multiple transit days',async()=>{const p=await build('Spanish Pyrenees',trip({days:12,budget:15000,maxDrive:5,maxChanges:10,tripStructure:'base'}));assert.ok(p.days.filter(d=>d.kind==='transfer'||d.kind==='outward').length>=2)});
test('CASE Q reload/restoration offline-only',async()=>{const p=await build('Harz',trip());const restored=deserializeTrip(serializeTrip(p));assert.equal(restored.canonicalSignature,p.canonicalSignature);assert.equal(validateCanonicalPlan(restored).valid,true)});
test('CASE R GPX offline-only',async()=>{const p=await build('Harz',trip());const g=buildGpx(p);assert.equal(gpxConsistency(p,g).valid,true)});
test('map consistency offline-only',async()=>{const p=await build('Harz',trip());assert.equal(mapConsistency(p,buildMapModel(p)).valid,true)});
test('memory storage roundtrip',async()=>{const p=await build('Harz',trip());const s=new MemoryStorage();s.setItem('x',serializeTrip(p));const r=deserializeTrip(s.getItem('x'));assert.equal(r.days.length,5)});
