import fs from 'node:fs';
const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const data=fs.readFileSync(new URL('./data.js',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('./package.json',import.meta.url),'utf8'));
const sw=fs.readFileSync(new URL('./service-worker.js',import.meta.url),'utf8');
let pass=0,fail=0;
const t=(name,ok)=>{if(ok){console.log('PASS ',name);pass++}else{console.log('FAIL ',name);fail++}};
const has=(...xs)=>xs.every(x=>app.includes(x));
t('version 1.14.1',data.includes("APP_VERSION = '1.14.1'")&&pkg.version==='1.14.1'&&sw.includes('labos-v1.14.1'));
t('authoritative custody helper exists',has('custodyPlanningState','custodySummary(state,d.programmeId)','currentCustody(state,dutId)'));
t('guided blocker uses authoritative custody',has('unavailableAllocatedDuts(l)','Authoritative custody:'));
t('replacement dialog no longer dead-ends',has('Resolve sample population','Register / receive new DUTs…','Controlled population change…','Reconcile current state now'));
t('empty pool still offers actions',has('No unused released DUTs are currently available','guided-custody-register','guided-custody-scope'));
t('stale blocker can be reconciled',has('reconcileCustodyBlocker','Stale custody blocker reconciled'));
t('reconciliation requires full indicated population',app.includes('allocated>=required'));
t('new physical DUT registration requires identities',has('guidedCustodyRegisterModal','Enter at least one physical DUT serial/identity'));
t('new DUT registration requires release evidence',has('Receipt / release evidence is required','moveDut(state,id,loc,\'Released\''));
t('new DUT registration records audit',app.includes('Additional DUTs registered with release evidence'));
t('new DUTs can replace bad allocation',has("status:'Replaced'","status:'Replacement assigned'"));
t('controlled population change is evidence gated',has('guidedCustodyScopeModal','Approved deviation / concession / change reference','Approved change reference and reason are required'));
t('controlled population change is auditable',app.includes('Controlled DUT population changed'));
t('programme DUT pool can be opened directly',has('guided-custody-open-pool','state.settings.custodyProgramme=id'));
t('custody actions protected-replan programme',has('scheduleProgramme(state,l.programmeId)','planningRestorePoint'));
t('custody actions retain undo',app.includes('pushPlanningUndo(restore)'));
t('per-DUT disposition remains available',has('guided-custody-disposition','Release / disposition →'));
t('full readiness action remains available',app.includes('Re-run full readiness check'));
console.log(`\n${pass}/${pass+fail} v1.14.1 focused checks passed.`);
if(fail)process.exit(1);
