import fs from 'node:fs';
const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const data=fs.readFileSync(new URL('./data.js',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('./package.json',import.meta.url),'utf8'));
const sw=fs.readFileSync(new URL('./service-worker.js',import.meta.url),'utf8');
let pass=0,fail=0;
const t=(name,ok)=>{if(ok){console.log('PASS ',name);pass++}else{console.log('FAIL ',name);fail++}};
const has=(...xs)=>xs.every(x=>app.includes(x));
t('version 1.14.0',data.includes("APP_VERSION = '1.14.0'")&&pkg.version==='1.14.0'&&sw.includes('labos-v1.14.0'));
t('prototype request stores scope type',has('linkedScopeType','linkedMainLegNo','linkedTestLegId'));
t('prototype can link to programme',app.includes('Entire programme sample gate'));
t('prototype can link to main Test Leg',app.includes('Specific Test Leg'));
t('prototype can link to specific test',app.includes('Specific test'));
t('prototype captures material availability',has('Material physically expected available','materialReadyDate'));
t('prototype captures expected completion',has('Build expected completed','targetBuildComplete'));
t('prototype update workflow exists',has('prototypeEditModal','Save & coordinate validation'));
t('prototype progress/delay workflow exists',has('prototypeProgressModal','Update build progress'));
t('prototype start requires physical material evidence',has('prototypeStartModal','Material availability evidence/reference'));
t('prototype completion remains evidence gated',has('completePrototypeRequest','Complete Build, Release Samples & Replan'));
t('prototype readiness date uses actual completion first',app.includes("r?.completedAt||r?.plannedReady||r?.targetBuildComplete"));
t('prototype dependency updates linked test sample-ready date',has('applyPrototypeDependency','l.sampleReadyDate=date','sampleReadyPrototypeId'));
t('default prototype coordination is protected',has('Default policy: protect every other programme','scheduleProgramme(state,pid)'));
t('prototype priority alternative selects flex programmes',has('Optional portfolio trade-off','protoFlex','scheduleProgrammeSet'));
t('portfolio alternative previews programme impact',has('replanProgrammeImpacts','impactTable(rows,pid)'));
t('portfolio alternative requires accept/reject',has('Accept this portfolio replan','Reject · keep protected plan'));
t('accepted prototype replan has undo restore point',has('pushPlanningUndo','Undo this schedule change'));
t('programme status surfaces guided blocker',has('guided-blocker','Resolve step-by-step'));
t('planning table surfaces Resolve blocker',app.includes('Resolve blocker →'));
t('blocker classifier covers custody',app.includes("type:'custody'"));
t('blocker classifier covers prototype',app.includes("type:'prototype'"));
t('blocker classifier covers method development',app.includes("type:'development'"));
t('blocker classifier covers calibration',app.includes("type:'calibration'"));
t('blocker classifier covers equipment',app.includes("type:'equipment'"));
t('blocker classifier covers staff/competency',app.includes("type:'people'"));
t('blocker classifier covers specification',app.includes("type:'spec'"));
t('blocker classifier covers predecessors',app.includes("type:'dependency'"));
t('custody workflow requires disposition evidence',has('guidedCustodyDispositionModal','Disposition evidence/reason is required'));
t('custody workflow can replace unavailable DUTs',has('guidedCustodyReplaceModal','Replace unavailable DUTs'));
t('custody resolution triggers programme replan',has('Before custody resolution','scheduleProgramme(state,l.programmeId)'));
t('blocker guide states evidence-based closure',app.includes('A blocker is never closed by acknowledgement alone'));
t('visual validation flow has drag support',has('draggable="true"','data-builder-drag','data-builder-drop-after'));
t('visual validation flow has touch Move action',has('data-act="builder-move"','builderMoveModal'));
t('drag/move writes executable predecessor',has('builderMoveAfter','src.dependsOn=[targetId]','rehomeBuilderLegFromPredecessors'));
t('drag/move rejects circular dependency',has('builderWouldCycle','circular validation dependency'));
t('visual flow advertises recursive splitting',has('any branch can split again','Nested branches stay side by side'));
t('visual flow retains no arrows between main legs',app.includes('No arrows between independent main Test Legs.'));
t('prototype page states guided physical action',app.includes('Tap any build for the next required physical action'));
t('prototype page distinguishes planning from completion',app.includes('Accepting/planning is never treated as physical completion'));

// Small deterministic contract checks mirroring the intended target selection semantics.
const legs=[{id:'L11',programmeId:'P',validationLegNo:1,sequence:1,predecessorIds:[]},{id:'L12',programmeId:'P',validationLegNo:1,sequence:2,predecessorIds:['L11']},{id:'L21',programmeId:'P',validationLegNo:2,sequence:3,predecessorIds:[]}];
const targets=(r)=>{const all=legs.filter(l=>l.programmeId===r.linkedProgrammeId);if(r.linkedScopeType==='test')return all.filter(l=>l.id===r.linkedTestLegId);if(r.linkedScopeType==='leg')return all.filter(l=>l.validationLegNo===r.linkedMainLegNo);const roots=all.filter(l=>!l.predecessorIds.length);return roots.length?roots:all};
t('target semantics: specific test',targets({linkedProgrammeId:'P',linkedScopeType:'test',linkedTestLegId:'L12'}).map(x=>x.id).join()==='L12');
t('target semantics: Test Leg',targets({linkedProgrammeId:'P',linkedScopeType:'leg',linkedMainLegNo:1}).map(x=>x.id).join()==='L11,L12');
t('target semantics: programme roots',targets({linkedProgrammeId:'P',linkedScopeType:'programme'}).map(x=>x.id).join()==='L11,L21');

console.log(`\n${pass}/${pass+fail} v1.14.0 focused checks passed.`);
if(fail) process.exit(1);
