import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('./app.js','utf8');
const planner=fs.readFileSync('./planner.js','utf8');
const css=fs.readFileSync('./styles.css','utf8');
const data=fs.readFileSync('./data.js','utf8');
const sw=fs.readFileSync('./service-worker.js','utf8');
const pkg=JSON.parse(fs.readFileSync('./package.json','utf8'));
let pass=0,fail=0;
function t(name,fn){try{fn();console.log('PASS ',name);pass++}catch(e){console.log('FAIL ',name,'—',e.message);fail++}}
t('release version is v1.17.0',()=>{assert.equal(pkg.version,'1.17.0');assert.match(data,/APP_VERSION\s*=\s*['"]1\.17\.0/);assert.match(sw,/labos-v1\.17\.0/)});
t('planner uses dependency depth/topological ordering',()=>{assert.match(planner,/function dependencyDepth/);assert.match(planner,/dependencyDepth\(data,a,depthMemo\)/)});
t('planner searches a 12-month horizon',()=>{assert.match(planner,/setUTCDate\(horizon\.getUTCDate\(\)\+366\)/);assert.doesNotMatch(planner,/within 90 days/)});
t('dedicated programme route exists',()=>assert.match(app,/programme:renderProgrammeWorkspace/));
t('programme entities navigate to workspace',()=>assert.match(app,/if\(type==='programme'\)return openProgrammeWorkspace\(id\)/));
t('programme cards expose Open programme action',()=>assert.match(app,/data-act="open-programme"[^>]*>Open programme/));
t('programme workspace consolidates test flow',()=>{assert.match(app,/function programmeWorkspaceFlow/);assert.match(app,/Validation test plan/)});
t('programme workspace consolidates planning',()=>{assert.match(app,/function programmeWorkspaceSchedule/);assert.match(app,/Planning & delivery/)});
t('programme workspace exposes Week Month Quarter Year',()=>{for(const x of ['Week','Month','Quarter','Year'])assert.ok(app.includes(`'${x}'`)||app.includes(`>${x}<`))});
t('programme workspace consolidates sample traceability',()=>assert.match(app,/Samples & traceability/));
t('programme workspace consolidates cost',()=>assert.match(app,/Cost & business position/));
t('programme workspace consolidates execution quality reports',()=>assert.match(app,/Execution, quality & reports/));
t('planner-owned blocker classifier exists',()=>assert.match(app,/function plannerResolvableReason/));
t('downstream predecessor blockers are collapsed to root blockers',()=>{assert.match(app,/function rootScheduleBlockers/);assert.match(app,/downstream test/)});
t('resource contention offers automated recovery',()=>{assert.match(app,/function automatedContentionRecoveryModal/);assert.match(app,/Automated contention recovery/)});
t('cross-programme recovery requires explicit acceptance',()=>{assert.match(app,/Accept recovery/);assert.match(app,/Reject · keep protected plan/)});
t('builder test cards expose sample assignment',()=>{assert.match(app,/function builderSampleAssignmentModal/);assert.match(app,/data-act="builder-samples"/)});
t('builder specific sample selection is serialized and persisted',()=>{assert.match(app,/cfg\.sampleSerials=picks/);assert.match(app,/sampleAssignmentMode='Specific'/)});
t('builder sample selection maps into created operational leg DUT IDs',()=>{assert.match(app,/explicitSerials/);assert.match(app,/explicitIds/);assert.match(app,/populationMode:explicitIds\.length\?'Specific samples'/)});
t('operational test legs expose specific sample assignment',()=>{assert.match(app,/function legSampleAssignmentModal/);assert.match(app,/data-act="leg-assign-samples"/)});
t('operational sample change invalidates booking and replans programme',()=>{assert.match(app,/l\.plannedStart=null/);assert.match(app,/smartProgrammeReplan\(l\.programmeId\)/)});
t('sample assignment UI is mobile-capable',()=>{assert.match(css,/\.sample-assignment-list/);assert.match(css,/\.sample-assignment-row/)});
t('programme workspace visual flow and swimlanes are styled',()=>{assert.match(css,/\.programme-flow-canvas/);assert.match(css,/\.programme-swimlanes/);assert.match(css,/\.swimlane-bar/)});
t('planning programme labels link into dedicated workspace',()=>assert.match(app,/programme-label-button/));
console.log(`\n${pass}/${pass+fail} passed`);if(fail)process.exit(1);
